export const PROJECTS = [
  {
    id: "via",
    slug: "via-holidays",
    path: "/work/via-holidays.html",
    url: "https://www.viaholidays.eu/",
    image: "/assets/work/via-holidays.jpg",
    service: "website",
    tags: ["travel", "web"],
    related: ["lodiamo", "nourvive"],
  },
  {
    id: "heba",
    slug: "heba",
    path: "/work/heba.html",
    url: "https://www.drhebaezz.com/",
    image: "/assets/work/heba.jpg",
    service: "website",
    tags: ["healthcare", "clinic", "web"],
    related: ["abdallah", "radwan"],
  },
  {
    id: "abdallah",
    slug: "abdallah",
    path: "/work/abdallah.html",
    url: "https://www.dr-abdallah-cardio-center.com/",
    image: "/assets/work/abdallah.jpg",
    service: "website",
    tags: ["healthcare", "clinic", "web"],
    related: ["heba", "radwan"],
  },
  {
    id: "radwan",
    slug: "radwan",
    path: "/work/radwan.html",
    url: "https://radwanezzelarab.vercel.app/",
    image: "/assets/work/radwan.jpg",
    service: "website",
    tags: ["legal", "web"],
    related: ["heba", "via"],
    preview: true,
  },
  {
    id: "medlab",
    slug: "medlab",
    path: "/work/medlab.html",
    url: "https://medlab-market.vercel.app/",
    image: "/assets/work/medlab.jpg",
    service: "ecommerce",
    tags: ["medical", "commerce"],
    related: ["adam", "nourvive"],
    preview: true,
  },
  {
    id: "adam",
    slug: "adam",
    path: "/work/adam.html",
    url: "https://adam-trending.vercel.app/",
    image: "/assets/work/adam.jpg",
    service: "ecommerce",
    tags: ["retail", "commerce"],
    related: ["medlab", "nourvive"],
    preview: true,
  },
  {
    id: "nourvive",
    slug: "nourvive",
    path: "/work/nourvive.html",
    url: "https://nourvive.vercel.app/",
    image: "/assets/work/nourvive.jpg",
    service: "ecommerce",
    tags: ["beauty", "commerce"],
    related: ["loofah", "uruz"],
    preview: true,
  },
  {
    id: "loofah",
    slug: "loofah",
    path: "/work/loofah.html",
    url: "https://loofahqueen.com/",
    image: "/assets/work/loofah.jpg",
    service: "ecommerce",
    tags: ["beauty", "commerce"],
    related: ["nourvive", "uruz"],
  },
  {
    id: "corolla",
    slug: "corolla",
    path: "/work/corolla.html",
    url: "https://corollaart.shop/",
    image: "/assets/work/corolla.jpg",
    service: "ecommerce",
    tags: ["food", "commerce", "retail"],
    related: ["nourvive", "lodiamo"],
  },
  {
    id: "uruz",
    slug: "uruz",
    path: "/work/uruz.html",
    url: "https://uruz-egypt.com/",
    image: "/assets/work/uruz.jpg",
    service: "ecommerce",
    tags: ["luxury", "beauty", "commerce"],
    related: ["nourvive", "corolla"],
  },
  {
    id: "lodiamo",
    slug: "lodiamo",
    path: "/work/lodiamo.html",
    url: "https://lodiamo.com/",
    image: "/assets/work/lodiamo.jpg",
    service: "website",
    tags: ["food", "platform"],
    related: ["via", "corolla"],
  },
  {
    id: "availio",
    slug: "availio",
    path: "/work/availio.html",
    url: "https://availio-green.vercel.app/",
    image: "/assets/work/availio.jpg",
    service: "saas",
    tags: ["saas", "property", "software"],
    related: ["haseb", "via"],
    preview: true,
  },
  {
    id: "haseb",
    slug: "haseb",
    path: "/work/haseb.html",
    url: "https://7asebb.wasmer.app/",
    image: "/assets/work/haseb.jpg",
    service: "bms",
    tags: ["systems", "saas", "business"],
    related: ["availio", "lodiamo"],
    preview: true,
  },
];

export const COPY = {
  en: {
    dir: "ltr",
    htmlLang: "en",
    metaTitle: "Power Shift | Web & Software Development Company",
    metaDesc:
      "Power Shift is a web and software development company in Cairo. We build business websites, ecommerce, landing pages and custom software for owners in Egypt and the GCC. Get a free website prototype.",
    skip: "Skip to content",
    a11y: {
      primaryNav: "Primary",
      mobileNav: "Mobile",
      language: "Language",
      projects: "Projects",
      clients: "Selected work names",
      breadcrumb: "Breadcrumb",
      reviews: "Client reviews",
    },
    nav: {
      work: "Work",
      services: "Services",
      approach: "Approach",
      about: "About",
      reviews: "Reviews",
      contact: "Contact",
      blog: "Blog",
      menuLabel: "Menu",
    },
    cta: {
      start: "Get a Free Website Prototype",
      startShort: "Free Prototype",
      whatsapp: "WhatsApp Us",
      leaveReview: "Leave a review",
      discuss: "Discuss this kind of work",
      specialist: "Talk through the right fit",
      continueWa: "Continue on WhatsApp",
      continueEmail: "Send by email",
      visit: "Open live site",
      visitPreview: "Open preview",
      similar: "I need something similar",
      menu: "Open menu",
      close: "Close",
      closeMenu: "Close menu",
    },
    lang: { en: "EN", ar: "عربي", switchTo: "العربية" },
    hero: {
      kicker: "Web & software studio · Cairo · Egypt & GCC",
      seoH1: "Power Shift — Web & Software Development Company",
      h1a: "We build websites and software",
      h1b: "for businesses that need both to work.",
      lead: "Company websites, ecommerce, landing pages, and custom software — built from Cairo for owners in Egypt and the GCC.",
      proof: "Live work you can open",
      proof2: "Arabic, English, and RTL included",
      shotName: "VIA Holidays",
      shotMeta: "Travel · live product",
    },
    engine: {
      code: "CODE",
      create: "CREATE",
      shift: "SHIFT",
    },
    clients: {
      kicker: "Selected work",
    },
    trust: {
      label: "How we work",
      figure: "Cairo",
      figureLabel: "based · shipping worldwide",
      body: "We work with small and mid-size businesses, startups, and teams that need software they can actually run. One partner from the first brief to launch and support.",
      a: "Bilingual products — Arabic, English, and proper RTL",
      b: "You speak with the people who build the work",
      c: "We will tell you what should wait — not only what to buy",
    },
    build: {
      kicker: "What we build",
      title: "The public face of the company. And the system underneath.",
      lead: "Some clients need a site that explains the business. Others need bookings, inventory, invoices, or a full operation. We do both — and we will say which one you actually need.",
      items: [
        {
          n: "01",
          title: "Websites",
          body: "Clear sites that load fast and turn a visit into a conversation.",
        },
        {
          n: "02",
          title: "Commerce",
          body: "Shops and catalogues that take orders — retail, wholesale, and brand stores.",
        },
        {
          n: "03",
          title: "Products & SaaS",
          body: "Web apps with real workflows: accounts, dashboards, calendars, and data.",
        },
        {
          n: "04",
          title: "Operations systems",
          body: "Internal tools that replace notebooks, spreadsheets, and scattered chats.",
        },
      ],
    },
    work: {
      kicker: "Work",
      title: "Our Work",
      lead: "Clinics, legal, medical supply, retail, travel, and operations — live products and previews from the same studio.",
      browseHint: "Drag, swipe, or use the arrows",
      previous: "Previous project",
      next: "Next project",
      navigation: "Project navigation",
      challenge: "The brief",
      solution: "What shipped",
      after: "Close to what you need?",
      afterCta: "Book a Scope Call",
      caseStudy: "Read the case study",
      previewNote: "Preview",
      liveNote: "Live",
      items: {
        via: {
          name: "VIA Holidays",
          category: "Travel & hospitality · Website",
          challenge:
            "Travellers searching for Egypt, Jordan, or Türkiye were not landing on one fast page they could trust and enquire from.",
          solution:
            "A page for each destination, built to be found, opening fast on a phone, with the enquiry on that same visit.",
        },
        heba: {
          name: "Dr. Heba Ezz El-Arab",
          category: "Healthcare · Clinic website",
          challenge:
            "Families looking for a geriatric doctor in Cairo were finding a directory listing, not a clinic page they could open and book from.",
          solution:
            "Clinic and location pages written to be found, fast on a phone, with WhatsApp booking before the family leaves.",
        },
        abdallah: {
          name: "Dr. Abdullah Ahmed Abdullah",
          category: "Healthcare · Cardiology clinic",
          challenge:
            "Someone in 10th of Ramadan looking for a heart clinic needed the exam and a way to book, on a phone, without waiting on the page.",
          solution:
            "A page for each exam, so it can be found, opens quickly, and books by phone or WhatsApp in the same visit.",
        },
        radwan: {
          name: "Radwan Ezz El-Arab",
          category: "Legal · Law office website",
          challenge:
            "A person searching for a specific kind of lawyer in Cairo will not call a one-page template that feels like a brochure.",
          solution:
            "A page for each practice area, fast in Arabic on a phone, with WhatsApp when they are ready to book.",
        },
        medlab: {
          name: "MedLab Market",
          category: "Medical supply · Commerce",
          challenge:
            "A hospital buyer looking for one product line should not dig through a heavy catalogue or send a blank contact form.",
          solution:
            "Sector pages a buyer can find, a catalogue that stays quick to browse, and a cart that becomes a quote.",
        },
        adam: {
          name: "Adam Trending",
          category: "Kids apparel · Commerce",
          challenge:
            "A parent on a phone should see the boys or girls collection and send the order, not wait on a slow shop.",
          solution:
            "Collection pages that can be found, a light storefront, and the order sent on WhatsApp.",
        },
        nourvive: {
          name: "Nourvive",
          category: "Beauty · Commerce",
          challenge:
            "Someone looking for a specific skincare or hair product should land on that product, on a shop that opens immediately.",
          solution:
            "Product pages that can be found in Arabic and English, on a shop that opens fast, with a cart that does not stall.",
        },
        loofah: {
          name: "Queen Loofah",
          category: "Natural bath · Commerce",
          challenge:
            "A buyer searching for natural Egyptian loofah should land on the product and order, or ask about export, without a slow brand page.",
          solution:
            "Product pages built to be found, a shop that opens fast on a phone, and checkout plus a real export path.",
        },
        corolla: {
          name: "Corolla",
          category: "Food · Commerce · Retail",
          challenge:
            "A household buyer and a wholesale buyer are two different searches. Both need a fast shop, not another generic food template.",
          solution:
            "Product pages a household buyer can find, a shop that stays quick, and a separate path for wholesale.",
        },
        uruz: {
          name: "URUZ",
          category: "Luxury beauty · Commerce",
          challenge:
            "A luxury brand still has to be found, and it still has to open fast. A heavy site that stalls loses the sale.",
          solution:
            "Collection pages search can understand, a site that stays quick on a phone, and the shop inside that structure.",
        },
        lodiamo: {
          name: "Lodiamo",
          category: "Food trade · Brand site",
          challenge:
            "A buyer searching for a product line should reach the catalogue and send an enquiry, not wait on a slow brochure.",
          solution:
            "Catalogue pages a Gulf buyer can find in Arabic or English, fast enough for a commercial enquiry in the same visit.",
        },
        availio: {
          name: "Availio",
          category: "Property · Custom software",
          challenge:
            "Operators were missing double bookings because the day ran in chats and spreadsheets. The screen they check all day has to be fast.",
          solution:
            "The occupancy screen opens fast enough to catch an overlap, with units, pricing, and guest links in one place.",
        },
        haseb: {
          name: "7aseb",
          category: "Operations · Finance · SaaS",
          challenge:
            "An owner who opens invoices several times a day cannot wait on a slow system, or lose the layout when they switch language.",
          solution:
            "Invoices, stock, and collections open fast on the phone they already use, in Arabic or English.",
        },
      },
    },
    why: {
      kicker: "Why POWER SHIFT",
      title: "Why Power Shift",
      lead: "Clients stay because the product ships, it can be maintained, and they are not handed off after launch.",
      items: [
        {
          title: "Arabic and English as a product, not a translation",
          body: "RTL, bilingual UI, and copy that holds up for Egypt and GCC clients — designed in from the start.",
        },
        {
          title: "One line from brief to support",
          body: "Discovery, design, build, launch, then maintenance. You are not assembling freelancers.",
        },
        {
          title: "Honest scope",
          body: "We will say what should be a site, a shop, or a system — and what should wait. That is the consultation.",
        },
      ],
    },
    reviews: {
      kicker: "Reviews",
      title: "What clients say",
      score: "5.0",
      scoreNote: "Average from 15 client reviews",
      count: "15 client reviews",
      heroProof: "5.0 from 15 client reviews",
      readAll: "Read all reviews",
      leave: "Leave a review",
      leaveHint: "Send your review on WhatsApp. We will add it here after we confirm it is from a real client.",
      featuredAria: "Selected client reviews",
      stars: "5 out of 5 stars",
      browseHint: "Swipe to read more",
      plaqueLabel: "Client rating",
    },
    services: {
      kicker: "Services",
      title: "What We Build",
      lead: "Pick the problem. We will tell you what should be built — and what should not.",
      specialist: "Talk through the right fit",
      pageCta: "Explore our web development and software services",
      also: "SaaS products and operations systems sit under custom software. Mobile apps are built when the product needs them — not as a separate brochure offer.",
      openPage: "Open this page",
      items: [
        {
          n: "01",
          id: "website",
          href: "/web-development-egypt",
          title: "Business Websites",
          body: "Company sites that explain the work and lead to a call or WhatsApp — not a generic template.",
        },
        {
          n: "02",
          id: "ecommerce",
          href: "/ecommerce-website-development",
          title: "Ecommerce",
          body: "Catalogues, carts, WhatsApp orders, checkout, or wholesale enquiry — whatever matches how you sell.",
        },
        {
          n: "03",
          id: "landing",
          href: "/web-design-egypt",
          title: "Landing Pages",
          body: "One offer, one audience, one action, when a full site is more than you need yet.",
        },
        {
          n: "04",
          id: "system",
          href: "/custom-software-development",
          title: "Custom Software",
          body: "Bookings, invoices, inventory, and the screens staff use every day — when a website is not enough.",
        },
        {
          n: "05",
          id: "mobile",
          href: "/custom-software-development",
          title: "Mobile Apps",
          body: "Built when the product needs an app. Not our main search offer — we will say if a site should come first.",
        },
      ],
    },
    industries: {
      kicker: "Industries",
      title: "Sectors we have already shipped in.",
      lead: "Not a wish list — these map to work you can open above.",
      items: [
        { title: "Tourism & hospitality", note: "VIA Holidays" },
        { title: "Healthcare & clinics", note: "Dr. Heba Ezz El-Arab" },
        { title: "Legal services", note: "Radwan Ezz El-Arab" },
        { title: "Beauty & wellness", note: "URUZ, Nourvive" },
        { title: "Luxury brands", note: "URUZ" },
        { title: "E-commerce & retail", note: "MedLab Market, Adam Trending, Corolla, Nourvive" },
        { title: "Food & beverage", note: "Corolla, Lodiamo" },
        { title: "Property operations", note: "Availio" },
        { title: "Business operations", note: "7aseb" },
        { title: "SaaS & startups", note: "Availio, 7aseb" },
        { title: "GCC trade", note: "Lodiamo" },
      ],
    },
    process: {
      kicker: "Approach",
      title: "Our Process",
      lead: "Nothing theatrical. You always know what you are getting next.",
      steps: [
        { n: "01", title: "Discover", body: "The business, the users, the constraint. Output: a written brief." },
        { n: "02", title: "Define", body: "Scope and the first version worth building. Output: a clear plan." },
        { n: "03", title: "Design", body: "Structure, interface, and the conversion path — both languages when needed." },
        { n: "04", title: "Build", body: "Engineering with a quality bar. Output: a staging URL you can click." },
        { n: "05", title: "Launch", body: "Go live with a named owner on our side — not a handoff email." },
        { n: "06", title: "Evolve", body: "Support, fixes, and the next version as the company grows." },
      ],
    },
    about: {
      kicker: "About",
      title: "A studio in Cairo that builds software, not decks.",
      who: "Who you are talking to",
      whoBody:
        "POWER SHIFT is a Cairo software studio founded by Nasser Ahmed. When you message us, you reach the people who will design and build the work — not a sales queue.",
      what: "Where we sit",
      whatBody:
        "Based in Cairo. We deliver for Egypt, the GCC, and international clients. Arabic and English are part of the product, not an afterthought.",
      whom: "Who we build for",
      whomBody:
        "Primarily small and mid-size businesses. Also founders and teams who need a serious counterpart for a site, a shop, or an operations system.",
      trust: "After launch",
      trustBody:
        "Maintenance is part of the offer. The work is specified so it can be changed later — not thrown over the wall.",
    },
    faq: {
      kicker: "Questions",
      title: "Straight answers before you message.",
      items: [
        {
          q: "How do we start?",
          a: "Request a free website prototype. Three short questions, then WhatsApp with your brief already written. We use that as a 20-minute conversation — not a pitch deck.",
        },
        {
          q: "Do you work in Arabic and English?",
          a: "Yes. Interfaces, copy, and RTL are designed together. That is normal for us, not an add-on.",
        },
        {
          q: "Where are you based?",
          a: "We are a remote-first team based in Cairo, Egypt, working online with local, GCC, and international clients. We do not operate a public walk-in office.",
        },
        {
          q: "How is pricing handled?",
          a: "After we understand the brief. There is no public rate card — the investment follows the scope, not a menu.",
        },
        {
          q: "What happens after launch?",
          a: "Updates, fixes, and the next version. You keep a named contact on our side.",
        },
        {
          q: "What do clients say about Power Shift?",
          a: "Fifteen published client reviews on this site are 5 stars. Clients mention clear communication, a site that is not a generic template, and a process they could follow.",
        },
      ],
    },
    qualify: {
      kicker: "Start",
      title: "Tell us what you need. We will take it to WhatsApp.",
      lead: "Three short questions. Then WhatsApp opens with your brief already written.",
      stepOf: "Step",
      of: "of",
      back: "Back",
      next: "Continue",
      q1: "What do you need?",
      q2: "What is the goal?",
      q3: "When should we start?",
      q4: "How can we reach you?",
      name: "Name",
      email: "Email",
      phone: "Phone (optional)",
      company: "Company (optional)",
      note: "Anything we should know (optional)",
      namePh: "Your name",
      emailPh: "you@company.com",
      phonePh: "+20 …",
      companyPh: "Company name",
      notePh: "Context, links, or constraints",
      errors: {
        name: "Enter your name.",
        email: "Enter a valid email address.",
        phone: "Enter a valid phone number, or leave this blank.",
      },
      opening: "Opening WhatsApp…",
      types: [
        { id: "website", label: "Website" },
        { id: "ecommerce", label: "Online store" },
        { id: "landing", label: "Landing page" },
        { id: "system", label: "App or system" },
        { id: "other", label: "Not sure yet" },
      ],
      goals: [
        { id: "launch", label: "Launch something new" },
        { id: "improve", label: "Improve what I have" },
        { id: "sales", label: "Get more sales" },
        { id: "explore", label: "Just exploring" },
      ],
      times: [
        { id: "asap", label: "As soon as possible" },
        { id: "month", label: "This month" },
        { id: "later", label: "Later" },
      ],
      priceNote: "We will discuss the right investment after we understand the work. No public rate card.",
      ready: "WhatsApp will open with this brief already written. If it does not, message us on the number in the footer.",
      privacy: "Your details are used to reply to this enquiry. We do not sell them.",
    },
    final: {
      kicker: "Next",
      title: "Have a business but no professional website?",
      body: "Get a free initial website prototype and see how the business could look online. Then we say what version one should include — and what can wait.",
    },
    offer: {
      kicker: "Free prototype",
      title: "Have a business but no professional website?",
      body: "Send what you sell and who the customer is. We prepare a first visual sample — not a finished site — then a written scope.",
    },
    wizard: {
      dialogLabel: "Get a free website prototype",
    },
    waPrefill: "Hi POWER SHIFT, I would like a free website prototype for my business.",
    footer: {
      rights: "All rights reserved.",
      note: "Software studio · Cairo · Egypt · GCC · International",
      contact: "Contact",
      whatsapp: "WhatsApp",
      follow: "Follow",
      instagram: "Instagram",
      facebook: "Facebook",
      linkedin: "LinkedIn",
      google: "Google",
      location: "Cairo, Egypt",
      privacy: "Briefs go to our WhatsApp. We do not sell your data.",
    },
  },
  ar: {
    dir: "rtl",
    htmlLang: "ar",
    metaTitle: "باور شيفت | شركة تطوير مواقع وبرمجيات في مصر",
    metaDesc:
      "باور شيفت شركة تطوير مواقع وبرمجيات في القاهرة. مواقع شركات ومتاجر وصفحات هبوط وأنظمة — عربي وإنجليزي. احصل على نموذج موقع مجاني. 15 تقييم 5 نجوم.",
    skip: "انتقل إلى المحتوى",
    a11y: {
      primaryNav: "القائمة الرئيسية",
      mobileNav: "قائمة الهاتف",
      language: "اللغة",
      projects: "المشاريع",
      clients: "أسماء الأعمال المختارة",
      breadcrumb: "مسار التنقل",
      reviews: "آراء العملاء",
    },
    nav: {
      work: "أعمالنا",
      services: "خدماتنا",
      approach: "طريقة العمل",
      about: "من نحن",
      reviews: "آراء العملاء",
      contact: "تواصل معنا",
      blog: "المدونة",
      menuLabel: "القائمة",
    },
    cta: {
      start: "احصل على نموذج موقع مجاني",
      startShort: "نموذج مجاني",
      whatsapp: "راسلنا واتساب",
      leaveReview: "اكتب تقييمك",
      discuss: "ناقش مشروعًا مشابهًا",
      specialist: "اعرف ما يناسب مشروعك",
      continueWa: "أكمل على واتساب",
      continueEmail: "أرسل بالبريد",
      visit: "افتح الموقع",
      visitPreview: "افتح المعاينة",
      similar: "أريد مشروعًا مثل هذا",
      menu: "افتح القائمة",
      close: "إغلاق",
      closeMenu: "إغلاق القائمة",
    },
    lang: { en: "EN", ar: "عربي", switchTo: "English" },
    hero: {
      kicker: "استوديو مواقع وبرمجيات · القاهرة · مصر والخليج",
      seoH1: "باور شيفت — شركة تطوير مواقع وبرمجيات",
      h1a: "نبني مواقع وأنظمة",
      h1b: "لأصحاب الشركات الذين يحتاجون إلى العمل عبر الإنترنت.",
      lead: "موقع شركة، متجر إلكتروني، صفحة هبوط، أو برنامج لفريقك — من القاهرة لمصر والخليج.",
      proof: "أعمال حقيقية يمكنك فتحها الآن",
      proof2: "عربي وإنجليزي بدعم RTL كامل",
      shotName: "VIA Holidays",
      shotMeta: "سياحة · منتج قيد التشغيل",
    },
    engine: {
      code: "نبرمج",
      create: "نبتكر",
      shift: "نحوّل",
    },
    clients: {
      kicker: "من أعمالنا",
    },
    trust: {
      label: "طريقة العمل",
      figure: "القاهرة",
      figureLabel: "نعمل عن بُعد من القاهرة · نخدم أسواقًا مختلفة",
      body: "نعمل مع الشركات الصغيرة والمتوسطة والشركات الناشئة والفرق التي تحتاج برمجيات تستخدمها فعليًا كل يوم. فريق واحد من أول اجتماع حتى الإطلاق والدعم.",
      a: "منتجات بلغتين: عربي وإنجليزي بدعم RTL حقيقي",
      b: "تتكلم مع من يبني المشروع، لا مع موظف مبيعات",
      c: "نوضح ما يحتاجه مشروعك الآن، وما يمكن تأجيله",
    },
    build: {
      kicker: "ماذا نبني",
      title: "واجهة تمثّل شركتك. ونظام يشغّلها.",
      lead: "عميل يحتاج موقعًا يشرح نشاطه، وآخر يحتاج حجوزات أو مخزونًا أو فواتير أو تشغيلًا كاملًا. نبني الاثنين، ونحدد معك ما تحتاجه فعلًا.",
      items: [
        {
          n: "01",
          title: "المواقع",
          body: "مواقع سريعة وواضحة، تحوّل الزيارة إلى تواصل حقيقي.",
        },
        {
          n: "02",
          title: "التجارة الإلكترونية",
          body: "متاجر وكتالوجات تستقبل طلبات التجزئة والجملة، وتخدم العلامات التجارية.",
        },
        {
          n: "03",
          title: "المنتجات ومنصات SaaS",
          body: "تطبيقات بمسارات عمل حقيقية: حسابات، ولوحات تحكم، وتقويمات، وبيانات.",
        },
        {
          n: "04",
          title: "أنظمة إدارة الأعمال",
          body: "أدوات داخلية تُغني عن الدفاتر وملفات Excel والمحادثات المتفرقة.",
        },
      ],
    },
    work: {
      kicker: "أعمالنا",
      title: "أعمالنا",
      lead: "عيادات، وقانون، ومستلزمات طبية، وتجزئة، وسياحة، وتشغيل — منتجات حقيقية ومعاينات من الاستوديو نفسه.",
      browseHint: "اسحب أو استخدم الأسهم للتنقل",
      previous: "المشروع السابق",
      next: "المشروع التالي",
      navigation: "التنقل بين المشاريع",
      challenge: "الاحتياج",
      solution: "ما أطلقناه",
      after: "قريب مما تحتاجه؟",
      afterCta: "تواصل معنا",
      previewNote: "معاينة",
      liveNote: "مباشر",
      caseStudy: "اقرأ دراسة الحالة",
      items: {
        via: {
          name: "VIA Holidays",
          category: "السياحة والضيافة · موقع",
          challenge:
            "من يبحث عن رحلة إلى مصر أو الأردن أو تركيا كان يقع على صفحات متفرقة، لا على صفحة واحدة يثق بها ويرسل منها استفساره.",
          solution:
            "لكل وجهة صفحتها. تفتح على الموبايل، والاستفسار يُرسل من الصفحة نفسها.",
        },
        heba: {
          name: "د. هبة عز العرب",
          category: "الرعاية الصحية · موقع عيادة",
          challenge:
            "عائلة تبحث عن طبيبة مسنين في القاهرة كانت تصل إلى بطاقة في دليل، لا إلى صفحة عيادة تفتحها وتحجز منها.",
          solution:
            "صفحة للعيادة ولكل فرع في القاهرة. تفتح على الموبايل فورًا، والحجز على واتساب من الشاشة الأولى.",
        },
        abdallah: {
          name: "د. عبدالله أحمد عبدالله",
          category: "الرعاية الصحية · مركز قلب",
          challenge:
            "مريض في العاشر من رمضان يريد أن يعرف الفحص المتاح ويحجز، لا أن ينتظر صفحة لا تفتح على موبايله.",
          solution:
            "لكل فحص صفحته. المريض يفتحها على موبايله ويحجز اتصالًا أو على واتساب.",
        },
        radwan: {
          name: "رضوان عز العرب",
          category: "القانون · موقع مكتب محاماة",
          challenge:
            "من يبحث عن محامٍ في مسألة بعينها لن يتصل بمكتب صفحته واحدة تشبه النشرة.",
          solution:
            "لكل مجال قانوني صفحته بالعربية. تفتح على الموبايل، وحجز الاستشارة على واتساب.",
        },
        medlab: {
          name: "MedLab Market",
          category: "المستلزمات الطبية · تجارة إلكترونية",
          challenge:
            "مسؤول المشتريات يبحث عن خط واحد من المستلزمات. كتالوج ثقيل، أو نموذج فارغ، يضيّع الطلب.",
          solution:
            "لكل قطاع صفحته. يتصفح الكتالوج على موبايله، والسلة تصبح طلب عرض سعر.",
        },
        adam: {
          name: "Adam Trending",
          category: "ملابس أطفال · تجارة إلكترونية",
          challenge:
            "ولي الأمر على الموبايل يريد أن يرى ترنجات الأولاد أو البنات ويرسل الطلب، لا أن ينتظر المتجر حتى يفتح.",
          solution:
            "صفحة للأولاد وصفحة للبنات. يختار المقاس على موبايله، والطلب يصل على واتساب.",
        },
        nourvive: {
          name: "Nourvive",
          category: "الجمال · تجارة إلكترونية",
          challenge:
            "من يبحث عن منتج بعينه للبشرة أو الشعر يصل إلى واجهة عامة، لا إلى صفحة هذا المنتج.",
          solution:
            "صفحة لكل منتج، بالعربي أو الإنجليزي. تفتح على الموبايل، والسلة لا تقف في منتصف الطريق.",
        },
        loofah: {
          name: "Queen Loofah",
          category: "عناية طبيعية · تجارة إلكترونية",
          challenge:
            "من يبحث عن ليفة مصرية طبيعية يريد المنتج والطلب، أو سؤال التصدير، لا صفحة علامة تتأخر في الفتح.",
          solution:
            "صفحة لكل منتج، والشراء يتم من السلة على الموبايل. ومن يريد التصدير يجد صفحة واضحة له.",
        },
        corolla: {
          name: "Corolla",
          category: "الأغذية · تجارة إلكترونية · تجزئة",
          challenge:
            "بيت يشتري للمنزل، وتاجر يشتري بالجملة. البحثان مختلفان، وكلاهما يحتاج متجرًا يفتح، لا قالب أغذية جاهزًا.",
          solution:
            "الأسرة تجد المنتج على متجر خفيف. الجملة لها مسارها، بعيدًا عن سلة البيت.",
        },
        uruz: {
          name: "URUZ",
          category: "جمال فاخر · تجارة إلكترونية",
          challenge:
            "الفخامة لا تعذر البطء. من يبحث عن المجموعة ثم تنتظر الصفحة، يذهب إلى غيرها.",
          solution:
            "لكل مجموعة صفحتها. الموقع فاخر ويبقى خفيفًا على الموبايل، والمتجر حيث يقف المشتري.",
        },
        lodiamo: {
          name: "Lodiamo",
          category: "تجارة غذائية · موقع مؤسسي",
          challenge:
            "مشتري في الخليج يبحث عن خط منتجات. إن تأخر الكتالوج، ضاع الاستفسار.",
          solution:
            "المشتري في الخليج يصل إلى خط المنتجات بالعربي أو الإنجليزي، ويرسل استفساره قبل أن يغلق الصفحة.",
        },
        availio: {
          name: "Availio",
          category: "عقارات · برمجيات مخصصة",
          challenge:
            "مدير الإيجار كان يفوّت تداخل الحجوزات لأن اليوم يجري على واتساب وفي Excel. الشاشة التي يفتحها طوال النهار لا تحتمل التأخير.",
          solution:
            "شاشة الإشغال تفتح بسرعة تكفي لرؤية الحجز المزدوج قبل تأكيده. الوحدة والسعر ورابط الضيف في الشاشة نفسها.",
        },
        haseb: {
          name: "7aseb",
          category: "تشغيل · مالية · SaaS",
          challenge:
            "صاحب العمل يفتح الفواتير عدة مرات في اليوم. نظام بطيء، أو شاشة تختل حين يبدّل اللغة، يوقف العمل.",
          solution:
            "الفاتورة والمخزون والتحصيل تفتح على الموبايل الذي يحمله، بالعربي أو الإنجليزي، دون انتظار.",
        },
      },
    },
    why: {
      kicker: "لماذا POWER SHIFT",
      title: "لماذا POWER SHIFT",
      lead: "نطلق المنتج، ونبنيه ليقبل التطوير، ونبقى معك بعد الإطلاق.",
      items: [
        {
          title: "العربي والإنجليزي منتج واحد، لا ترجمة لاحقة",
          body: "واجهة RTL ونصوص تناسب عملاء مصر والخليج — تُصمَّم من أول يوم.",
        },
        {
          title: "فريق واحد من أول اجتماع حتى الدعم",
          body: "فهم الاحتياج، تصميم، برمجة، إطلاق، ثم صيانة. لن تجمع فريقًا من المستقلين.",
        },
        {
          title: "نطاق واضح بلا مبالغة",
          body: "نقول لك: موقع أم متجر أم نظام — وما يمكن تأجيله. هذه هي الاستشارة.",
        },
      ],
    },
    reviews: {
      kicker: "آراء العملاء",
      title: "ماذا يقول العملاء",
      score: "5.0",
      scoreNote: "المتوسط من 15 مراجعة عملاء",
      count: "15 مراجعة من العملاء",
      heroProof: "تقييم 5.0 من 15 مراجعة",
      readAll: "اقرأ كل المراجعات",
      leave: "اكتب تقييمك",
      leaveHint: "أرسل تقييمك على واتساب. نضيفه هنا بعد التأكد أنه من عميل حقيقي.",
      featuredAria: "مراجعات مختارة من العملاء",
      stars: "5 من 5 نجوم",
      browseHint: "اسحب لقراءة المزيد",
      plaqueLabel: "تقييم العملاء",
    },
    services: {
      kicker: "الخدمات",
      title: "ماذا نبني",
      lead: "حدّد المشكلة، ونقول لك ما يستحق البناء وما لا يستحقه الآن.",
      specialist: "اعرف ما يناسب مشروعك",
      pageCta: "استكشف خدمات تطوير المواقع والبرمجيات",
      also: "منتجات SaaS وأنظمة التشغيل ضمن البرمجيات المخصصة. تطبيقات الموبايل بتتعمل لما المنتج يحتاجها — مش عرض بحث أساسي.",
      openPage: "افتح الصفحة",
      items: [
        {
          n: "01",
          id: "website",
          href: "/ar/شركة-برمجة-مواقع",
          title: "مواقع الشركات",
          body: "موقع يوضح النشاط ويقود لواتساب أو مكالمة — مش قالب جاهز.",
        },
        {
          n: "02",
          id: "ecommerce",
          href: "/ar/تصميم-متجر-الكتروني",
          title: "المتاجر الإلكترونية",
          body: "كتالوج وسلة وطلب واتساب أو دفع أو طلب جملة — حسب طريقة بيعك.",
        },
        {
          n: "03",
          id: "landing",
          href: "/ar/تصميم-مواقع-مصر",
          title: "صفحات الهبوط",
          body: "عرض واحد وجمهور واحد وفعل واحد، لما الموقع الكامل أكبر من احتياجك.",
        },
        {
          n: "04",
          id: "system",
          href: "/ar/برمجة-أنظمة-مخصصة",
          title: "أنظمة مخصصة",
          body: "حجوزات وفواتير ومخزون والشاشات اللي الفريق بيفتحها كل يوم — لما الموقع مش كفاية.",
        },
        {
          n: "05",
          id: "mobile",
          href: "/ar/برمجة-أنظمة-مخصصة",
          title: "تطبيقات الموبايل",
          body: "بتتعمل لما المنتج يحتاج تطبيق. مش عرضنا الأساسي في البحث — وهنقول لك لو الموقع لازم ييجي الأول.",
        },
      ],
    },
    industries: {
      kicker: "القطاعات",
      title: "قطاعات أطلقنا فيها مشاريع حقيقية.",
      lead: "ليست قائمة رغبات — كل قطاع يقابله عمل يمكنك فتحه بالأعلى.",
      items: [
        { title: "السياحة والضيافة", note: "VIA Holidays" },
        { title: "الرعاية الصحية والعيادات", note: "د. هبة عز العرب" },
        { title: "الخدمات القانونية", note: "رضوان عز العرب" },
        { title: "الجمال والعناية", note: "URUZ، Nourvive" },
        { title: "العلامات الفاخرة", note: "URUZ" },
        { title: "التجارة الإلكترونية والتجزئة", note: "MedLab Market، Adam Trending، Corolla، Nourvive" },
        { title: "الأغذية والمشروبات", note: "Corolla، Lodiamo" },
        { title: "تشغيل العقارات", note: "Availio" },
        { title: "إدارة الأعمال", note: "7aseb" },
        { title: "SaaS والشركات الناشئة", note: "Availio، 7aseb" },
        { title: "التجارة في الخليج", note: "Lodiamo" },
      ],
    },
    process: {
      kicker: "طريقة العمل",
      title: "طريقتنا",
      lead: "بلا إجراءات شكلية. تعرف دائمًا ما سنسلّمه لك بعد ذلك.",
      steps: [
        { n: "01", title: "فهم الاحتياج", body: "نفهم النشاط والمستخدم والقيود. النتيجة: ملخص مكتوب." },
        { n: "02", title: "تحديد النطاق", body: "نحدد ما يستحق البناء في النسخة الأولى. النتيجة: خطة واضحة." },
        { n: "03", title: "التصميم", body: "الهيكل والواجهة ومسار التحويل، وباللغتين عند الحاجة." },
        { n: "04", title: "البرمجة", body: "نبرمج وفق معايير واضحة. النتيجة: رابط تجريبي تفتحه بنفسك." },
        { n: "05", title: "الإطلاق", body: "ننطلق ومعك مسؤول محدد من فريقنا، لا رسالة تسليم ثم اختفاء." },
        { n: "06", title: "التطوير", body: "دعم وإصلاحات، ثم النسخة التالية مع نمو شركتك." },
      ],
    },
    about: {
      kicker: "من نحن",
      title: "استوديو في القاهرة يبني برمجيات حقيقية، لا عروضًا تقديمية.",
      who: "مع من تتكلم",
      whoBody:
        "أسس ناصر أحمد POWER SHIFT في القاهرة. حين تراسلنا تصل مباشرة إلى من سيصمّم مشروعك ويبنيه، لا إلى قسم مبيعات.",
      what: "أين نعمل",
      whatBody:
        "نعمل عن بُعد من القاهرة مع عملاء في مصر والخليج والأسواق الدولية. العربي والإنجليزي جزء من المنتج، لا خطوة لاحقة.",
      whom: "لمن نبني",
      whomBody:
        "الشركات الصغيرة والمتوسطة أولًا. وكذلك المؤسسون والفرق الباحثة عن طرف جاد لموقع أو متجر أو نظام إدارة أعمال.",
      trust: "بعد الإطلاق",
      trustBody:
        "الصيانة جزء من الاتفاق. نبني المشروع بحيث يسهل تطويره لاحقًا، ولا نتركه بعد التسليم.",
    },
    faq: {
      kicker: "أسئلة",
      title: "إجابات مباشرة قبل أن تراسلنا.",
      items: [
        {
          q: "كيف نبدأ؟",
          a: "اطلب نموذج موقع مجاني. تجيب عن ثلاثة أسئلة سريعة، ثم يفتح واتساب وتفاصيل مشروعك مكتوبة. نراجعها معك في مكالمة قصيرة لتحديد المطلوب.",
        },
        {
          q: "هل تعملون بالعربي والإنجليزي؟",
          a: "نعم. الواجهة والنصوص وRTL تُصمَّم معًا. هذه طريقتنا المعتادة، لا خدمة إضافية.",
        },
        {
          q: "من أين تعملون؟",
          a: "نعمل عن بُعد من القاهرة، مصر، مع شركات محلية وفرق في الخليج وأسواق دولية. لا يوجد مكتب عام لاستقبال الزوار.",
        },
        {
          q: "كيف تحددون التكلفة؟",
          a: "بعد فهم المشروع. لا توجد قائمة أسعار معلنة — التكلفة تتبع حجم العمل، لا قائمة جاهزة.",
        },
        {
          q: "ماذا بعد الإطلاق؟",
          a: "تحديثات وإصلاحات ونسخة تالية. يبقى معك مسؤول محدد من فريقنا.",
        },
        {
          q: "ماذا يقول العملاء عن باور شيفت؟",
          a: "المراجعات الخمس عشرة المنشورة في الموقع كلها 5 نجوم. يذكر العملاء وضوح التواصل، وموقعًا لا يبدو قالبًا جاهزًا، ومسار عمل يمكن متابعته.",
        },
      ],
    },
    qualify: {
      kicker: "ابدأ",
      title: "قل لنا ما تحتاجه، ونكمل على واتساب.",
      lead: "ثلاثة أسئلة سريعة. بعدها يفتح واتساب وتفاصيل طلبك مكتوبة.",
      stepOf: "الخطوة",
      of: "من",
      back: "السابق",
      next: "التالي",
      q1: "ماذا تحتاج؟",
      q2: "ما الهدف؟",
      q3: "متى نبدأ؟",
      q4: "كيف نصل إليك؟",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف (اختياري)",
      company: "الشركة (اختياري)",
      note: "أي تفاصيل إضافية (اختياري)",
      namePh: "اسمك",
      emailPh: "you@company.com",
      phonePh: "+20 …",
      companyPh: "اسم الشركة",
      notePh: "تفاصيل أو روابط أو قيود",
      errors: {
        name: "أدخل اسمك.",
        email: "أدخل بريدًا إلكترونيًا صحيحًا.",
        phone: "أدخل رقم هاتف صحيحًا، أو اترك الحقل فارغًا.",
      },
      opening: "جارٍ فتح واتساب…",
      types: [
        { id: "website", label: "موقع إلكتروني" },
        { id: "ecommerce", label: "متجر إلكتروني" },
        { id: "landing", label: "صفحة هبوط" },
        { id: "system", label: "تطبيق أو نظام" },
        { id: "other", label: "لست متأكدًا بعد" },
      ],
      goals: [
        { id: "launch", label: "إطلاق شيء جديد" },
        { id: "improve", label: "تحسين ما لدي" },
        { id: "sales", label: "زيادة المبيعات" },
        { id: "explore", label: "أستكشف الخيارات" },
      ],
      times: [
        { id: "asap", label: "في أقرب وقت" },
        { id: "month", label: "هذا الشهر" },
        { id: "later", label: "لاحقًا" },
      ],
      priceNote: "نحدد التكلفة المناسبة بعد فهم المشروع. لا توجد قائمة أسعار ثابتة.",
      ready: "سيُفتح واتساب وتفاصيل طلبك مكتوبة. إن لم يُفتح، راسلنا على الرقم أسفل الصفحة.",
      privacy: "تُستخدم بياناتك للرد على هذا الطلب. لا نبيعها.",
    },
    final: {
      kicker: "الخطوة التالية",
      title: "عندك نشاط ومفيش موقع احترافي؟",
      body: "احصل على نموذج أولي لموقعك وشوف شكل النشاط أونلاين. وبعدين نحدد إيه يدخل النسخة الأولى وإيه يتأجل.",
    },
    offer: {
      kicker: "نموذج مجاني",
      title: "عندك نشاط ومفيش موقع احترافي؟",
      body: "ابعت إيه اللي بتبيعه ومين عميلك. نجهّز عيّنة بصرية أولى — مش موقع نهائي — وبعدين نطاق مكتوب.",
    },
    footer: {
      rights: "جميع الحقوق محفوظة.",
      note: "استوديو برمجيات · القاهرة · مصر · الخليج · الأسواق الدولية",
      contact: "تواصل",
      whatsapp: "واتساب",
      follow: "تابعنا",
      instagram: "Instagram",
      facebook: "Facebook",
      linkedin: "LinkedIn",
      google: "Google",
      location: "القاهرة، مصر",
      privacy: "تصل تفاصيل مشروعك إلى واتساب. لا نبيع بياناتك.",
    },
    wizard: {
      dialogLabel: "احصل على نموذج موقع مجاني",
    },
    waPrefill: "مرحبًا فريق POWER SHIFT، أرغب في نموذج موقع مجاني لنشاطي.",
  },
};
