export const PROJECTS = [
  {
    id: "via",
    slug: "via-holidays",
    path: "/work/via-holidays.html",
    url: "https://www.viaholidays.eu/",
    image: "/assets/work/via-holidays.jpg",
    service: "website",
    tags: ["travel", "web"],
    related: ["lodiamo", "nourvive"],
  },
  {
    id: "nourvive",
    slug: "nourvive",
    path: "/work/nourvive.html",
    url: "https://nourvive.vercel.app/",
    image: "/assets/work/nourvive.jpg",
    service: "ecommerce",
    tags: ["beauty", "commerce"],
    related: ["uruz", "corolla"],
    preview: true,
  },
  {
    id: "corolla",
    slug: "corolla",
    path: "/work/corolla.html",
    url: "https://corollaart.shop/",
    image: "/assets/work/corolla.jpg",
    service: "ecommerce",
    tags: ["food", "commerce", "retail"],
    related: ["nourvive", "lodiamo"],
  },
  {
    id: "uruz",
    slug: "uruz",
    path: "/work/uruz.html",
    url: "https://uruz-egypt.com/",
    image: "/assets/work/uruz.jpg",
    service: "ecommerce",
    tags: ["luxury", "beauty", "commerce"],
    related: ["nourvive", "corolla"],
  },
  {
    id: "lodiamo",
    slug: "lodiamo",
    path: "/work/lodiamo.html",
    url: "https://lodiamo.com/",
    image: "/assets/work/lodiamo.jpg",
    service: "website",
    tags: ["food", "platform"],
    related: ["via", "corolla"],
  },
  {
    id: "availio",
    slug: "availio",
    path: "/work/availio.html",
    url: "https://availio-green.vercel.app/",
    image: "/assets/work/availio.jpg",
    service: "saas",
    tags: ["saas", "property", "software"],
    related: ["haseb", "via"],
    preview: true,
  },
  {
    id: "haseb",
    slug: "haseb",
    path: "/work/haseb.html",
    url: "https://7asebb.wasmer.app/",
    image: "/assets/work/haseb.jpg",
    service: "bms",
    tags: ["systems", "saas", "business"],
    related: ["availio", "lodiamo"],
    preview: true,
  },
];

export const COPY = {
  en: {
    dir: "ltr",
    htmlLang: "en",
    metaTitle: "Power Shift | Software & Web Development Agency in Cairo",
    metaDesc:
      "Power Shift is a software studio in Cairo building high-performance websites, e-commerce platforms, SaaS products, and custom business systems for companies across Egypt and the GCC.",
    skip: "Skip to content",
    a11y: {
      primaryNav: "Primary",
      mobileNav: "Mobile",
      language: "Language",
      projects: "Projects",
      clients: "Selected work names",
      breadcrumb: "Breadcrumb",
    },
    nav: {
      work: "Work",
      services: "Services",
      approach: "Approach",
      about: "About",
      contact: "Contact",
      menuLabel: "Menu",
    },
    cta: {
      start: "Book a Scope Call",
      startShort: "Book a Call",
      whatsapp: "WhatsApp",
      discuss: "Discuss this kind of work",
      specialist: "Talk through the right fit",
      continueWa: "Continue on WhatsApp",
      continueEmail: "Send by email",
      visit: "Open live site",
      visitPreview: "Open preview",
      similar: "I need something similar",
      menu: "Open menu",
      close: "Close",
      closeMenu: "Close menu",
    },
    lang: { en: "EN", ar: "عربي", switchTo: "العربية" },
    hero: {
      kicker: "Software studio · Cairo · GCC & international",
      seoH1: "Software & Web Development Agency in Cairo",
      h1a: "We build the website.",
      h1b: "Then we build what runs behind it.",
      lead: "A serious site, a shop that takes orders, or the system your team uses every day — designed, built, and supported from Cairo.",
      proof: "Live work you can open",
      proof2: "Arabic, English, and RTL included",
      shotName: "VIA Holidays",
      shotMeta: "Travel · live product",
    },
    engine: {
      code: "CODE",
      create: "CREATE",
      shift: "SHIFT",
    },
    clients: {
      kicker: "Selected work",
    },
    trust: {
      label: "How we work",
      figure: "Cairo",
      figureLabel: "based · shipping worldwide",
      body: "We work with small and mid-size businesses, startups, and teams that need software they can actually run. One partner from the first brief to launch and support.",
      a: "Bilingual products — Arabic, English, and proper RTL",
      b: "You speak with the people who build the work",
      c: "We will tell you what should wait — not only what to buy",
    },
    build: {
      kicker: "What we build",
      title: "The public face of the company. And the system underneath.",
      lead: "Some clients need a site that explains the business. Others need bookings, inventory, invoices, or a full operation. We do both — and we will say which one you actually need.",
      items: [
        {
          n: "01",
          title: "Websites",
          body: "Clear sites that load fast and turn a visit into a conversation.",
        },
        {
          n: "02",
          title: "Commerce",
          body: "Shops and catalogues that take orders — retail, wholesale, and brand stores.",
        },
        {
          n: "03",
          title: "Products & SaaS",
          body: "Web apps with real workflows: accounts, dashboards, calendars, and data.",
        },
        {
          n: "04",
          title: "Operations systems",
          body: "Internal tools that replace notebooks, spreadsheets, and scattered chats.",
        },
      ],
    },
    work: {
      kicker: "Work",
      title: "Our Work",
      lead: "Travel, beauty, food, property, and operations — these are running, not mockups.",
      browseHint: "Drag, swipe, or use the arrows",
      previous: "Previous project",
      next: "Next project",
      navigation: "Project navigation",
      challenge: "The brief",
      solution: "What shipped",
      after: "Close to what you need?",
      afterCta: "Book a Scope Call",
      caseStudy: "Read the case study",
      previewNote: "Preview",
      liveNote: "Live",
      items: {
        via: {
          name: "VIA Holidays",
          category: "Travel & hospitality · Website",
          challenge:
            "A travel operator needed one place for Czech travellers booking Egypt, Jordan, and Türkiye — tours, transfers, and enquiries.",
          solution:
            "A Czech-and-English site for destinations, transfers, and VIP holidays, with a clear path to enquire.",
        },
        nourvive: {
          name: "Nourvive",
          category: "Beauty · Commerce",
          challenge:
            "A Cairo beauty brand needed a bilingual shop for skincare, hair care, and mesotherapy — a real catalogue, not a brochure.",
          solution:
            "A storefront with categories, product pages, cart, and English / Arabic switching.",
        },
        corolla: {
          name: "Corolla",
          category: "Food · Commerce · Retail",
          challenge:
            "An Egyptian dried-fruit brand needed to sell to households and take wholesale enquiries without looking generic.",
          solution:
            "A brand shop for the collection, the farm story, and a bulk-order path.",
        },
        uruz: {
          name: "URUZ",
          category: "Luxury beauty · Commerce",
          challenge:
            "A natural-beauty house needed a brand world — collections, rituals, ingredients — not only a product grid.",
          solution:
            "A high-end beauty site with editorial structure, collections, and a shop at uruz-egypt.com.",
        },
        lodiamo: {
          name: "Lodiamo",
          category: "Food trade · Brand site",
          challenge:
            "A UAE import/export food company needed a bilingual presence for premium agricultural products.",
          solution:
            "A corporate site for the catalogue and a direct commercial contact path, live at lodiamo.com.",
        },
        availio: {
          name: "Availio",
          category: "Property · Custom software",
          challenge:
            "Short-term rental operators were running units in chats and spreadsheets — overlaps and pricing were easy to miss.",
          solution:
            "A booking-control product: occupancy calendar, units, pricing, guest links, and reporting.",
        },
        haseb: {
          name: "7aseb",
          category: "Operations · Finance · SaaS",
          challenge:
            "Small businesses needed invoicing, stock, customers, and payment follow-up in one place — Arabic and English.",
          solution:
            "An operations system for invoices, inventory, CRM, treasury, and WhatsApp sharing, with full RTL.",
        },
      },
    },
    why: {
      kicker: "Why POWER SHIFT",
      title: "Why Power Shift",
      lead: "Clients stay because the product ships, it can be maintained, and they are not handed off after launch.",
      items: [
        {
          title: "Arabic and English as a product, not a translation",
          body: "RTL, bilingual UI, and copy that holds up for Egypt and GCC clients — designed in from the start.",
        },
        {
          title: "One line from brief to support",
          body: "Discovery, design, build, launch, then maintenance. You are not assembling freelancers.",
        },
        {
          title: "Honest scope",
          body: "We will say what should be a site, a shop, or a system — and what should wait. That is the consultation.",
        },
      ],
    },
    services: {
      kicker: "Services",
      title: "What We Build",
      lead: "Pick the problem. We will tell you what should be built — and what should not.",
      specialist: "Talk through the right fit",
      pageCta: "Explore our web development and software services",
      also: "Also when the work needs it: mobile apps, AI inside the product, payments and WhatsApp integrations, automation, and ongoing maintenance.",
      items: [
        {
          n: "01",
          id: "website",
          title: "Custom Websites",
          body: "Marketing and product sites that load fast, read clearly, and can be maintained.",
        },
        {
          n: "02",
          id: "ecommerce",
          title: "E-commerce Platforms",
          body: "Catalogues, checkout, wholesale enquiry, and brand shops that take real orders.",
        },
        {
          n: "03",
          id: "saas",
          title: "SaaS Products",
          body: "Multi-user apps with dashboards, roles, and workflows — not a brochure with a login.",
        },
        {
          n: "04",
          id: "bms",
          title: "Custom Operations Systems",
          body: "Invoicing, inventory, CRM, booking, and the software staff use every day.",
        },
      ],
    },
    industries: {
      kicker: "Industries",
      title: "Sectors we have already shipped in.",
      lead: "Not a wish list — these map to work you can open above.",
      items: [
        { title: "Tourism & hospitality", note: "VIA Holidays" },
        { title: "Beauty & wellness", note: "URUZ, Nourvive" },
        { title: "Luxury brands", note: "URUZ" },
        { title: "E-commerce & retail", note: "Corolla, Nourvive" },
        { title: "Food & beverage", note: "Corolla, Lodiamo" },
        { title: "Property operations", note: "Availio" },
        { title: "Business operations", note: "7aseb" },
        { title: "SaaS & startups", note: "Availio, 7aseb" },
        { title: "GCC trade", note: "Lodiamo" },
      ],
    },
    process: {
      kicker: "Approach",
      title: "Our Process",
      lead: "Nothing theatrical. You always know what you are getting next.",
      steps: [
        { n: "01", title: "Discover", body: "The business, the users, the constraint. Output: a written brief." },
        { n: "02", title: "Define", body: "Scope and the first version worth building. Output: a clear plan." },
        { n: "03", title: "Design", body: "Structure, interface, and the conversion path — both languages when needed." },
        { n: "04", title: "Build", body: "Engineering with a quality bar. Output: a staging URL you can click." },
        { n: "05", title: "Launch", body: "Go live with a named owner on our side — not a handoff email." },
        { n: "06", title: "Evolve", body: "Support, fixes, and the next version as the company grows." },
      ],
    },
    about: {
      kicker: "About",
      title: "A studio in Cairo that builds software, not decks.",
      who: "Who you are talking to",
      whoBody:
        "POWER SHIFT is a small software studio. When you message us, you reach the people who will design and build the work — not a sales queue.",
      what: "Where we sit",
      whatBody:
        "Based in Cairo. We deliver for Egypt, the GCC, and international clients. Arabic and English are part of the product, not an afterthought.",
      whom: "Who we build for",
      whomBody:
        "Primarily small and mid-size businesses. Also founders and teams who need a serious counterpart for a site, a shop, or an operations system.",
      trust: "After launch",
      trustBody:
        "Maintenance is part of the offer. The work is specified so it can be changed later — not thrown over the wall.",
    },
    faq: {
      kicker: "Questions",
      title: "Straight answers before you message.",
      items: [
        {
          q: "How do we start?",
          a: "Three short questions, then WhatsApp with your brief already written. We use that as a 20-minute conversation — not a pitch deck.",
        },
        {
          q: "Do you work in Arabic and English?",
          a: "Yes. Interfaces, copy, and RTL are designed together. That is normal for us, not an add-on.",
        },
        {
          q: "Where are you based?",
          a: "Cairo, Egypt. We build for local companies and for GCC and international teams.",
        },
        {
          q: "How is pricing handled?",
          a: "After we understand the brief. There is no public rate card — the investment follows the scope, not a menu.",
        },
        {
          q: "What happens after launch?",
          a: "Updates, fixes, and the next version. You keep a named contact on our side.",
        },
      ],
    },
    qualify: {
      kicker: "Start",
      title: "Tell us what you need. We will take it to WhatsApp.",
      lead: "Three short questions. Then WhatsApp opens with your brief already written.",
      stepOf: "Step",
      of: "of",
      back: "Back",
      next: "Continue",
      q1: "What do you need?",
      q2: "What is the goal?",
      q3: "When should we start?",
      q4: "How can we reach you?",
      name: "Name",
      email: "Email",
      phone: "Phone (optional)",
      company: "Company (optional)",
      note: "Anything we should know (optional)",
      namePh: "Your name",
      emailPh: "you@company.com",
      phonePh: "+20 …",
      companyPh: "Company name",
      notePh: "Context, links, or constraints",
      errors: {
        name: "Enter your name.",
        email: "Enter a valid email address.",
        phone: "Enter a valid phone number, or leave this blank.",
      },
      opening: "Opening WhatsApp…",
      types: [
        { id: "website", label: "Website" },
        { id: "ecommerce", label: "Online store" },
        { id: "system", label: "App or system" },
        { id: "other", label: "Not sure yet" },
      ],
      goals: [
        { id: "launch", label: "Launch something new" },
        { id: "improve", label: "Improve what I have" },
        { id: "sales", label: "Get more sales" },
        { id: "explore", label: "Just exploring" },
      ],
      times: [
        { id: "asap", label: "As soon as possible" },
        { id: "month", label: "This month" },
        { id: "later", label: "Later" },
      ],
      priceNote: "We will discuss the right investment after we understand the work. No public rate card.",
      ready: "WhatsApp will open with this brief already written. If it does not, message us on the number in the footer.",
      privacy: "Your details are used to reply to this enquiry. We do not sell them.",
    },
    final: {
      kicker: "Next",
      title: "Let's Build Something Powerful",
      body: "If it needs to look serious and actually work, book a 20-minute scope call. We will tell you what should be built — and what should wait.",
    },
    footer: {
      rights: "All rights reserved.",
      note: "Software studio · Cairo · Egypt · GCC · International",
      contact: "Contact",
      whatsapp: "WhatsApp",
      follow: "Follow",
      instagram: "Instagram",
      facebook: "Facebook",
      linkedin: "LinkedIn",
      location: "Cairo, Egypt",
      privacy: "Briefs go to our WhatsApp. We do not sell your data.",
    },
    wizard: {
      dialogLabel: "Book a scope call",
    },
    waPrefill: "Hi POWER SHIFT, I would like to book a 20-minute scope call.",
  },
  ar: {
    dir: "rtl",
    htmlLang: "ar",
    metaTitle: "Power Shift | شركة تطوير برمجيات ومواقع في القاهرة",
    metaDesc:
      "Power Shift استوديو برمجيات في القاهرة يبني مواقع عالية الأداء ومتاجر إلكترونية ومنتجات SaaS وأنظمة أعمال مخصصة للشركات في مصر والخليج.",
    skip: "انتقل إلى المحتوى",
    a11y: {
      primaryNav: "القائمة الرئيسية",
      mobileNav: "قائمة الهاتف",
      language: "اللغة",
      projects: "المشاريع",
      clients: "أسماء الأعمال المختارة",
      breadcrumb: "مسار التنقل",
    },
    nav: {
      work: "أعمالنا",
      services: "خدماتنا",
      approach: "طريقة العمل",
      about: "من نحن",
      contact: "تواصل معنا",
      menuLabel: "القائمة",
    },
    cta: {
      start: "تواصل معنا",
      startShort: "تواصل معنا",
      whatsapp: "واتساب",
      discuss: "ناقش مشروعًا مشابهًا",
      specialist: "اعرف ما يناسب مشروعك",
      continueWa: "أكمل على واتساب",
      continueEmail: "أرسل بالبريد",
      visit: "افتح الموقع",
      visitPreview: "افتح المعاينة",
      similar: "أريد مشروعًا مثل هذا",
      menu: "افتح القائمة",
      close: "إغلاق",
      closeMenu: "إغلاق القائمة",
    },
    lang: { en: "EN", ar: "عربي", switchTo: "English" },
    hero: {
      kicker: "مصر · الخليج · الأسواق الدولية",
      seoH1: "شركة تطوير برمجيات ومواقع إلكترونية في القاهرة",
      h1a: "موقع يقنع عميلك.",
      h1b: "ونظام يسهّل عمل فريقك.",
      lead: "نصمّم ونبرمج المواقع والمتاجر وأنظمة إدارة الأعمال — من التخطيط إلى الإطلاق والدعم.",
      proof: "أعمال حقيقية يمكنك فتحها الآن",
      proof2: "عربي وإنجليزي بدعم RTL كامل",
      shotName: "VIA Holidays",
      shotMeta: "سياحة · منتج قيد التشغيل",
    },
    engine: {
      code: "نبرمج",
      create: "نبتكر",
      shift: "نحوّل",
    },
    clients: {
      kicker: "من أعمالنا",
    },
    trust: {
      label: "طريقة العمل",
      figure: "القاهرة",
      figureLabel: "مقرّنا · نعمل مع أسواق مختلفة",
      body: "نعمل مع الشركات الصغيرة والمتوسطة والشركات الناشئة والفرق التي تحتاج برمجيات تستخدمها فعليًا كل يوم. فريق واحد من أول اجتماع حتى الإطلاق والدعم.",
      a: "منتجات بلغتين: عربي وإنجليزي بدعم RTL حقيقي",
      b: "تتكلم مع من يبني المشروع، لا مع موظف مبيعات",
      c: "نوضح ما يحتاجه مشروعك الآن، وما يمكن تأجيله",
    },
    build: {
      kicker: "ماذا نبني",
      title: "واجهة تمثّل شركتك. ونظام يشغّلها.",
      lead: "عميل يحتاج موقعًا يشرح نشاطه، وآخر يحتاج حجوزات أو مخزونًا أو فواتير أو تشغيلًا كاملًا. نبني الاثنين، ونحدد معك ما تحتاجه فعلًا.",
      items: [
        {
          n: "01",
          title: "المواقع",
          body: "مواقع سريعة وواضحة، تحوّل الزيارة إلى تواصل حقيقي.",
        },
        {
          n: "02",
          title: "التجارة الإلكترونية",
          body: "متاجر وكتالوجات تستقبل طلبات التجزئة والجملة، وتخدم العلامات التجارية.",
        },
        {
          n: "03",
          title: "المنتجات ومنصات SaaS",
          body: "تطبيقات بمسارات عمل حقيقية: حسابات، ولوحات تحكم، وتقويمات، وبيانات.",
        },
        {
          n: "04",
          title: "أنظمة إدارة الأعمال",
          body: "أدوات داخلية تُغني عن الدفاتر وملفات Excel والمحادثات المتفرقة.",
        },
      ],
    },
    work: {
      kicker: "أعمالنا",
      title: "أعمالنا",
      lead: "سياحة، وجمال، وأغذية، وعقارات، وتشغيل — كلها مشاريع قيد التشغيل، لا نماذج عرض.",
      browseHint: "اسحب أو استخدم الأسهم للتنقل",
      previous: "المشروع السابق",
      next: "المشروع التالي",
      navigation: "التنقل بين المشاريع",
      challenge: "الاحتياج",
      solution: "ما أطلقناه",
      after: "قريب مما تحتاجه؟",
      afterCta: "تواصل معنا",
      previewNote: "معاينة",
      liveNote: "مباشر",
      caseStudy: "اقرأ دراسة الحالة",
      items: {
        via: {
          name: "VIA Holidays",
          category: "السياحة والضيافة · موقع",
          challenge:
            "شركة سياحة تحتاج منصة واحدة تخدم المسافرين التشيكيين إلى مصر والأردن وتركيا، وتجمع الجولات والانتقالات والاستفسارات.",
          solution:
            "موقع بالتشيكية والإنجليزية يعرض الوجهات والانتقالات وبرامج VIP، بمسار واضح لطلب الاستفسار.",
        },
        nourvive: {
          name: "Nourvive",
          category: "الجمال · تجارة إلكترونية",
          challenge:
            "علامة جمال في القاهرة تحتاج متجرًا بلغتين للعناية بالبشرة والشعر والميزوثيرابي — كتالوج كامل لا صفحة تعريف.",
          solution:
            "متجر بأقسام وصفحات منتجات وسلة شراء، وتبديل فوري بين العربي والإنجليزي.",
        },
        corolla: {
          name: "Corolla",
          category: "الأغذية · تجارة إلكترونية · تجزئة",
          challenge:
            "علامة مصرية للفواكه المجففة تريد البيع للمستهلك واستقبال طلبات الجملة، من خلال متجر يعكس هويتها ولا يبدو كقالب جاهز.",
          solution:
            "متجر يعرض المجموعة وقصة المنتج، ومسار مستقل لطلبات الجملة.",
        },
        uruz: {
          name: "URUZ",
          category: "جمال فاخر · تجارة إلكترونية",
          challenge:
            "دار عناية طبيعية تحتاج عالمًا كاملًا للعلامة: المجموعات والطقوس والمكوّنات — لا شبكة منتجات فقط.",
          solution:
            "تجربة رقمية فاخرة تجمع المحتوى التحريري والمجموعات والمتجر على uruz-egypt.com.",
        },
        lodiamo: {
          name: "Lodiamo",
          category: "تجارة غذائية · موقع مؤسسي",
          challenge:
            "شركة إماراتية للاستيراد والتصدير الغذائي تحتاج حضورًا بلغتين لمنتجات زراعية فاخرة.",
          solution:
            "موقع مؤسسي يعرض الكتالوج ويفتح مسار تواصل تجاري مباشر على lodiamo.com.",
        },
        availio: {
          name: "Availio",
          category: "عقارات · برمجيات مخصصة",
          challenge:
            "مشغّلو الإيجار قصير المدة يديرون وحداتهم بالمحادثات وملفات Excel، فيتكرر تداخل الحجوزات ويصعب ضبط التسعير.",
          solution:
            "منتج لضبط الحجوزات: تقويم إشغال، ووحدات، وتسعير، وروابط للضيوف، وتقارير.",
        },
        haseb: {
          name: "7aseb",
          category: "تشغيل · مالية · SaaS",
          challenge:
            "شركات صغيرة تحتاج الفواتير والمخزون والعملاء ومتابعة التحصيل في مكان واحد، بالعربي والإنجليزي.",
          solution:
            "نظام يدير الفواتير والمخزون وCRM والخزينة والمشاركة عبر واتساب، بدعم RTL كامل.",
        },
      },
    },
    why: {
      kicker: "لماذا POWER SHIFT",
      title: "لماذا POWER SHIFT",
      lead: "نطلق المنتج، ونبنيه ليقبل التطوير، ونبقى معك بعد الإطلاق.",
      items: [
        {
          title: "العربي والإنجليزي منتج واحد، لا ترجمة لاحقة",
          body: "واجهة RTL ونصوص تناسب عملاء مصر والخليج — تُصمَّم من أول يوم.",
        },
        {
          title: "فريق واحد من أول اجتماع حتى الدعم",
          body: "فهم الاحتياج، تصميم، برمجة، إطلاق، ثم صيانة. لن تجمع فريقًا من المستقلين.",
        },
        {
          title: "نطاق واضح بلا مبالغة",
          body: "نقول لك: موقع أم متجر أم نظام — وما يمكن تأجيله. هذه هي الاستشارة.",
        },
      ],
    },
    services: {
      kicker: "الخدمات",
      title: "ماذا نبني",
      lead: "حدّد المشكلة، ونقول لك ما يستحق البناء وما لا يستحقه الآن.",
      specialist: "اعرف ما يناسب مشروعك",
      pageCta: "استكشف خدمات تطوير المواقع والبرمجيات",
      also: "وعند الحاجة: تطبيقات موبايل، وذكاء اصطناعي داخل المنتج، وربط المدفوعات وواتساب، وأتمتة، وصيانة مستمرة.",
      items: [
        {
          n: "01",
          id: "website",
          title: "مواقع مخصصة",
          body: "مواقع تعريفية وتسويقية سريعة وواضحة وسهلة الصيانة.",
        },
        {
          n: "02",
          id: "ecommerce",
          title: "منصات التجارة الإلكترونية",
          body: "كتالوج ودفع وطلبات جملة، ومتاجر تستقبل طلبات حقيقية.",
        },
        {
          n: "03",
          id: "saas",
          title: "منتجات SaaS",
          body: "تطبيقات متعددة المستخدمين بلوحات تحكم وصلاحيات ومسارات عمل.",
        },
        {
          n: "04",
          id: "bms",
          title: "أنظمة تشغيل مخصصة",
          body: "فواتير ومخزون وعملاء وحجوزات: البرنامج الذي يفتحه فريقك كل يوم.",
        },
      ],
    },
    industries: {
      kicker: "القطاعات",
      title: "قطاعات أطلقنا فيها مشاريع حقيقية.",
      lead: "ليست قائمة رغبات — كل قطاع يقابله عمل يمكنك فتحه بالأعلى.",
      items: [
        { title: "السياحة والضيافة", note: "VIA Holidays" },
        { title: "الجمال والعناية", note: "URUZ، Nourvive" },
        { title: "العلامات الفاخرة", note: "URUZ" },
        { title: "التجارة الإلكترونية والتجزئة", note: "Corolla، Nourvive" },
        { title: "الأغذية والمشروبات", note: "Corolla، Lodiamo" },
        { title: "تشغيل العقارات", note: "Availio" },
        { title: "إدارة الأعمال", note: "7aseb" },
        { title: "SaaS والشركات الناشئة", note: "Availio، 7aseb" },
        { title: "التجارة في الخليج", note: "Lodiamo" },
      ],
    },
    process: {
      kicker: "طريقة العمل",
      title: "طريقتنا",
      lead: "بلا إجراءات شكلية. تعرف دائمًا ما سنسلّمه لك بعد ذلك.",
      steps: [
        { n: "01", title: "فهم الاحتياج", body: "نفهم النشاط والمستخدم والقيود. النتيجة: ملخص مكتوب." },
        { n: "02", title: "تحديد النطاق", body: "نحدد ما يستحق البناء في النسخة الأولى. النتيجة: خطة واضحة." },
        { n: "03", title: "التصميم", body: "الهيكل والواجهة ومسار التحويل، وباللغتين عند الحاجة." },
        { n: "04", title: "البرمجة", body: "نبرمج وفق معايير واضحة. النتيجة: رابط تجريبي تفتحه بنفسك." },
        { n: "05", title: "الإطلاق", body: "ننطلق ومعك مسؤول محدد من فريقنا، لا رسالة تسليم ثم اختفاء." },
        { n: "06", title: "التطوير", body: "دعم وإصلاحات، ثم النسخة التالية مع نمو شركتك." },
      ],
    },
    about: {
      kicker: "من نحن",
      title: "استوديو في القاهرة يبني برمجيات حقيقية، لا عروضًا تقديمية.",
      who: "مع من تتكلم",
      whoBody:
        "POWER SHIFT استوديو برمجيات صغير. حين تراسلنا تصل مباشرة إلى من سيصمّم مشروعك ويبنيه، لا إلى قسم مبيعات.",
      what: "أين نعمل",
      whatBody:
        "مقرّنا في القاهرة، ونعمل مع عملاء في مصر والخليج والأسواق الدولية. العربي والإنجليزي جزء من المنتج، لا خطوة لاحقة.",
      whom: "لمن نبني",
      whomBody:
        "الشركات الصغيرة والمتوسطة أولًا. وكذلك المؤسسون والفرق الباحثة عن طرف جاد لموقع أو متجر أو نظام إدارة أعمال.",
      trust: "بعد الإطلاق",
      trustBody:
        "الصيانة جزء من الاتفاق. نبني المشروع بحيث يسهل تطويره لاحقًا، ولا نتركه بعد التسليم.",
    },
    faq: {
      kicker: "أسئلة",
      title: "إجابات مباشرة قبل أن تراسلنا.",
      items: [
        {
          q: "كيف نبدأ؟",
          a: "تجيب عن ثلاثة أسئلة سريعة، ثم يفتح واتساب وتفاصيل مشروعك مكتوبة. نراجعها معك في مكالمة قصيرة لتحديد المطلوب.",
        },
        {
          q: "هل تعملون بالعربي والإنجليزي؟",
          a: "نعم. الواجهة والنصوص وRTL تُصمَّم معًا. هذه طريقتنا المعتادة، لا خدمة إضافية.",
        },
        {
          q: "أين مقرّكم؟",
          a: "القاهرة، مصر. نبني لشركات محلية ولفرق في الخليج وأسواق دولية.",
        },
        {
          q: "كيف تحددون التكلفة؟",
          a: "بعد فهم المشروع. لا توجد قائمة أسعار معلنة — التكلفة تتبع حجم العمل، لا قائمة جاهزة.",
        },
        {
          q: "ماذا بعد الإطلاق؟",
          a: "تحديثات وإصلاحات ونسخة تالية. يبقى معك مسؤول محدد من فريقنا.",
        },
      ],
    },
    qualify: {
      kicker: "ابدأ",
      title: "قل لنا ما تحتاجه، ونكمل على واتساب.",
      lead: "ثلاثة أسئلة سريعة. بعدها يفتح واتساب وتفاصيل طلبك مكتوبة.",
      stepOf: "الخطوة",
      of: "من",
      back: "السابق",
      next: "التالي",
      q1: "ماذا تحتاج؟",
      q2: "ما الهدف؟",
      q3: "متى نبدأ؟",
      q4: "كيف نصل إليك؟",
      name: "الاسم",
      email: "البريد الإلكتروني",
      phone: "الهاتف (اختياري)",
      company: "الشركة (اختياري)",
      note: "أي تفاصيل إضافية (اختياري)",
      namePh: "اسمك",
      emailPh: "you@company.com",
      phonePh: "+20 …",
      companyPh: "اسم الشركة",
      notePh: "تفاصيل أو روابط أو قيود",
      errors: {
        name: "أدخل اسمك.",
        email: "أدخل بريدًا إلكترونيًا صحيحًا.",
        phone: "أدخل رقم هاتف صحيحًا، أو اترك الحقل فارغًا.",
      },
      opening: "جارٍ فتح واتساب…",
      types: [
        { id: "website", label: "موقع إلكتروني" },
        { id: "ecommerce", label: "متجر إلكتروني" },
        { id: "system", label: "تطبيق أو نظام" },
        { id: "other", label: "لست متأكدًا بعد" },
      ],
      goals: [
        { id: "launch", label: "إطلاق شيء جديد" },
        { id: "improve", label: "تحسين ما لدي" },
        { id: "sales", label: "زيادة المبيعات" },
        { id: "explore", label: "أستكشف الخيارات" },
      ],
      times: [
        { id: "asap", label: "في أقرب وقت" },
        { id: "month", label: "هذا الشهر" },
        { id: "later", label: "لاحقًا" },
      ],
      priceNote: "نحدد التكلفة المناسبة بعد فهم المشروع. لا توجد قائمة أسعار ثابتة.",
      ready: "سيُفتح واتساب وتفاصيل طلبك مكتوبة. إن لم يُفتح، راسلنا على الرقم أسفل الصفحة.",
      privacy: "تُستخدم بياناتك للرد على هذا الطلب. لا نبيعها.",
    },
    final: {
      kicker: "الخطوة التالية",
      title: "لنبنِ شيئًا يستحق",
      body: "إذا أردت مشروعًا يبدو احترافيًا ويعمل كما يجب، تواصل معنا. نحدد معك ما يستحق التنفيذ الآن وما يمكن تأجيله.",
    },
    footer: {
      rights: "جميع الحقوق محفوظة.",
      note: "استوديو برمجيات · القاهرة · مصر · الخليج · الأسواق الدولية",
      contact: "تواصل",
      whatsapp: "واتساب",
      follow: "تابعنا",
      instagram: "Instagram",
      facebook: "Facebook",
      linkedin: "LinkedIn",
      location: "القاهرة، مصر",
      privacy: "تصل تفاصيل مشروعك إلى واتساب. لا نبيع بياناتك.",
    },
    wizard: {
      dialogLabel: "تواصل معنا",
    },
    waPrefill: "مرحبًا فريق POWER SHIFT، أرغب في حجز مكالمة 20 دقيقة لتحديد نطاق مشروعي.",
  },
};
