export const PAGE_EXTRAS = {
  en: {
    via: {
      h1: "VIA Holidays — Travel Booking Platform",
      overview:
        "A page for each destination, built to be found, opening fast on a phone, with the enquiry on that same visit.",
      stack:
        "Light destination pages with their own addresses, in Czech and English, so search can match the trip and the phone does not wait. We do not publish a vendor stack or a speed score for this project.",
      results: "The product is live at viaholidays.eu. We do not publish traffic or conversion figures for this project.",
      liveLabel: "Open the live VIA Holidays website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty shop",
      relatedB: "GCC brand website",
      metaTitle: "VIA Holidays Case Study | Travel Website by Power Shift",
      metaDesc:
        "How Power Shift built VIA Holidays so travellers can find Egypt, Jordan, and Türkiye holidays on a fast phone page and enquire in the same visit.",
      goals: [
        "Be found for the country they are searching, not one vague homepage.",
        "Open fast while they compare trips on a phone.",
        "Turn that visit into an enquiry before they leave.",
      ],
      features: [
        "Its own page for Egypt, Jordan, and Türkiye, so search can match the trip.",
        "Transfers and VIP holidays on pages that stay light.",
        "Czech and English, each able to be found on its own.",
        "The enquiry sits on the page, not behind a slow form.",
      ],
    },
    heba: {
      h1: "Dr. Heba Ezz El-Arab — Clinic Website Families Can Find",
      overview:
        "Clinic and location pages written to be found, fast on a phone, with WhatsApp booking before the family leaves.",
      stack:
        "Separate pages for the practice and each Cairo clinic, light enough for a phone, with WhatsApp as the booking action. We do not publish a vendor stack or a speed score for this project.",
      results: "The site is live at drhebaezz.com. We do not publish appointment or traffic figures for this project.",
      liveLabel: "Open the live Dr. Heba Ezz website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Law office website",
      relatedB: "Cardiology clinic",
      metaTitle: "Dr. Heba Ezz El-Arab Case Study | Clinic Website by Power Shift",
      metaDesc:
        "How Power Shift built Dr. Heba Ezz El-Arab's clinic site so families in Cairo can find the practice, open it on a phone, and book on WhatsApp.",
      goals: [
        "Be found for the practice and the Cairo clinics, not only the doctor's name.",
        "Open quickly for an older patient or the relative beside them.",
        "Make WhatsApp the booking action on the first screen.",
      ],
      features: [
        "Its own page for the practice, New Cairo, and Mohandessin.",
        "Arabic and English on separate addresses, so both can be found.",
        "Copy a family can read without a medical brochure.",
        "WhatsApp booking that does not wait on a heavy page.",
      ],
    },
    abdallah: {
      h1: "Dr. Abdullah Ahmed Abdullah — Cardiology Clinic Website",
      overview:
        "A page for each exam, so it can be found, opens quickly, and books by phone or WhatsApp in the same visit.",
      stack:
        "A separate light page for each exam, with the 10th of Ramadan clinic where search expects it. We do not publish a vendor stack or a speed score for this project.",
      results: "The site is live at dr-abdallah-cardio-center.com. We do not publish appointment or traffic figures for this project.",
      liveLabel: "Open the live Cardio Care Center website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Clinic website",
      relatedB: "Law office website",
      metaTitle: "Dr. Abdullah Ahmed Abdullah Case Study | Clinic Website by Power Shift",
      metaDesc:
        "How Power Shift built the Cardio Care Center site so patients in 10th of Ramadan can find each exam, open it on a phone, and book.",
      goals: [
        "Be found for cardiology in 10th of Ramadan, not only the center's name.",
        "Open fast when someone is deciding whether to call.",
        "Put the phone and WhatsApp on the page before they leave.",
      ],
      features: [
        "Its own page for the consultation, echo, ECG, and pediatric echo.",
        "The clinic, hours, and 10th of Ramadan address on the page search can read.",
        "Arabic and English, each on an address that can be found.",
        "Booking by phone or WhatsApp on a page that stays light.",
      ],
    },
    radwan: {
      h1: "Radwan Ezz El-Arab — Arabic Law Office Website",
      overview:
        "A page for each practice area, fast in Arabic on a phone, with WhatsApp when they are ready to book.",
      stack:
        "A light page for each practice area, in Arabic, so the search matches the legal problem and the phone does not wait. We do not publish a vendor stack or a speed score for this project.",
      results: "A preview site is published for review. We do not invent case or enquiry results.",
      liveLabel: "Open the Radwan Ezz El-Arab preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Clinic website",
      relatedB: "Travel website",
      metaTitle: "Radwan Ezz El-Arab Case Study | Law Office Website by Power Shift",
      metaDesc:
        "How Power Shift built Radwan Ezz El-Arab's law office site so a Cairo searcher finds the practice area, opens it fast, and books on WhatsApp.",
      goals: [
        "Be found for the legal problem, not a generic lawyer page.",
        "Open fast in Arabic on the phone they are already holding.",
        "Book the consultation on WhatsApp from that page.",
      ],
      features: [
        "Its own page for civil, commercial, company, criminal and cyber, family, and State Council work.",
        "Anonymized case examples that explain the work without naming clients.",
        "Arabic copy search can read, on a page that stays light.",
        "WhatsApp booking on the page, not a buried form.",
      ],
    },
    medlab: {
      h1: "MedLab Market — Medical & Laboratory Catalogue",
      overview:
        "Sector pages a buyer can find, a catalogue that stays quick to browse, and a cart that becomes a quote.",
      stack:
        "Light sector pages and product cards, so a buyer finds the line and requests a quote without a heavy catalogue. We do not publish a vendor stack or a speed score for this project.",
      results:
        "A preview storefront is published for review. Login and contact fields in the preview are interface-only. We do not invent sales or quote results.",
      liveLabel: "Open the MedLab Market preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Kids apparel shop",
      relatedB: "Beauty commerce",
      metaTitle: "MedLab Market Case Study | Medical Catalogue by Power Shift",
      metaDesc:
        "How Power Shift built MedLab Market so a buyer can find a sector, browse it quickly, and turn the cart into a quote.",
      goals: [
        "Be found for the sector, not a single dumped catalogue.",
        "Stay quick to browse on the phone a purchasing officer uses.",
        "Turn the cart into a quote without a blank contact form.",
      ],
      features: [
        "Its own path for hospitals, labs, scientific, personal care, and chemicals.",
        "Product cards that stay light while the buyer compares.",
        "A cart that becomes a quote request.",
        "Arabic pages search can read. This build is still a review preview.",
      ],
    },
    adam: {
      h1: "Adam Trending — Kids Tracksuit Shop",
      overview:
        "Collection pages that can be found, a light storefront, and the order sent on WhatsApp.",
      stack:
        "Light collection pages and a WhatsApp checkout, so a parent finds the set and sends the order. We do not publish a vendor stack or a speed score for this project.",
      results: "A preview shop is published for review. We do not invent sales or conversion results.",
      liveLabel: "Open the Adam Trending preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Medical catalogue",
      relatedB: "Beauty commerce",
      metaTitle: "Adam Trending Case Study | Kids Apparel Shop by Power Shift",
      metaDesc:
        "How Power Shift built Adam Trending so a parent can find the boys or girls collection on a phone and send the order on WhatsApp.",
      goals: [
        "Be found for the collection, not a generic kids-shop homepage.",
        "Open fast on the phone a parent is already using.",
        "Send the order on WhatsApp instead of a form they abandon.",
      ],
      features: [
        "Separate paths for boys and girls, each able to be found.",
        "Product pages that stay light while they choose a size.",
        "WhatsApp checkout from the cart.",
        "Arabic pages. This build is still a review preview.",
      ],
    },
    nourvive: {
      h1: "Nourvive — Beauty Shop Built to Be Found",
      overview: "Product pages that can be found in Arabic and English, on a shop that opens fast, with a cart that does not stall.",
      stack: "Light product pages in Arabic and English, so a search can land on the item and the cart still moves. We do not publish a vendor stack or a speed score for this project.",
      results: "A preview storefront is published for review. We do not invent sales or conversion results.",
      liveLabel: "Open the Nourvive preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Luxury beauty commerce",
      relatedB: "Food retail store",
      metaTitle: "Nourvive Case Study | Beauty E-commerce by Power Shift",
      metaDesc:
        "How Power Shift built Nourvive so a shopper can find a skincare or hair product, open it fast, and add it to the cart.",
      goals: [
        "Land on the product they searched for, not a brochure.",
        "Open fast on a phone in Arabic or English.",
        "Reach the cart without the page stalling.",
      ],
      features: [
        "Its own page for skincare, hair care, and mesotherapy.",
        "Product pages with their own addresses, so search can match the item.",
        "A cart that stays light.",
        "Arabic and English. This build is still a review preview.",
      ],
    },
    loofah: {
      h1: "Queen Loofah — A Shop Buyers Can Find",
      overview:
        "Product pages built to be found, a shop that opens fast on a phone, and checkout plus a real export path.",
      stack:
        "Light product pages and a checkout that does not wait, plus an export page buyers can find. We do not publish a vendor stack or a speed score for this project.",
      results: "The shop is live at loofahqueen.com. We do not publish sales figures for this project.",
      liveLabel: "Open the live Queen Loofah shop",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty commerce",
      relatedB: "Luxury beauty commerce",
      metaTitle: "Queen Loofah Case Study | Bath Shop by Power Shift",
      metaDesc:
        "How Power Shift built Queen Loofah so a buyer can find natural Egyptian loofah, open the shop fast, and check out or ask about export.",
      goals: [
        "Be found for the product, not only the brand name.",
        "Open fast on the phone a buyer uses to decide.",
        "Check out, or reach export, without leaving for a social page.",
      ],
      features: [
        "Product and collection pages with their own addresses.",
        "A shop that stays light on a phone.",
        "Checkout from the cart.",
        "An export page partners can find and use.",
      ],
    },
    corolla: {
      h1: "Corolla — Food E-commerce & Wholesale",
      overview: "Product pages a household buyer can find, a shop that stays quick, and a separate path for wholesale.",
      stack: "Light product pages for retail, and a separate wholesale path, so each search lands in the right place. We do not publish a vendor stack or a speed score for this project.",
      results: "The shop is live at corollaart.shop. We do not publish sales figures for this project.",
      liveLabel: "Open the live Corolla shop",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty commerce",
      relatedB: "Food trade website",
      metaTitle: "Corolla Case Study | Food E-commerce by Power Shift",
      metaDesc: "How Power Shift built Corolla so a household buyer can find the product on a fast shop, and wholesale has its own path.",
      goals: [
        "Be found for the product a household is searching for.",
        "Stay quick on a phone, including the farm story.",
        "Give wholesale its own path so it does not slow the shop.",
      ],
      features: ["Product pages search can match.", "A light shop, with the farm story beside the products.", "A wholesale path that does not sit inside the retail cart."],
    },
    uruz: {
      h1: "URUZ — Luxury Beauty Commerce",
      overview: "Collection pages search can understand, a site that stays quick on a phone, and the shop inside that structure.",
      stack: "Editorial pages that stay light, with a real address for each collection, so luxury does not mean a slow site. We do not publish a vendor stack or a speed score for this project.",
      results: "The site is live at uruz-egypt.com. We do not publish sales figures for this project.",
      liveLabel: "Open the live URUZ website",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty commerce",
      relatedB: "Brand retail shop",
      metaTitle: "URUZ Case Study | Luxury Beauty Website by Power Shift",
      metaDesc: "How Power Shift built URUZ so a buyer can find a collection, open a luxury site that stays fast, and reach the shop.",
      goals: [
        "Be found for the collection, not a single mood page.",
        "Keep a luxury site fast on a phone.",
        "Put the shop where the buyer already is, not behind a heavy intro.",
      ],
      features: ["A page for each collection, rituals, and ingredients.", "Images and type that do not stall the first screen.", "The shop inside the same fast structure."],
    },
    lodiamo: {
      h1: "Lodiamo — UAE Food Trade Website",
      overview: "Catalogue pages a Gulf buyer can find in Arabic or English, fast enough for a commercial enquiry in the same visit.",
      stack: "Light catalogue pages in Arabic and English, each with its own address, and a commercial enquiry on the page. We do not publish a vendor stack or a speed score for this project.",
      results: "The site is live at lodiamo.com. We do not publish lead or traffic figures for this project.",
      liveLabel: "Open the live Lodiamo website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "International brand site",
      relatedB: "Food commerce",
      metaTitle: "Lodiamo Case Study | Bilingual Corporate Site by Power Shift",
      metaDesc:
        "How Power Shift built Lodiamo so a Gulf buyer can find a product line in Arabic or English and send a commercial enquiry on a fast page.",
      goals: [
        "Be found for the product line, in the language the buyer searched.",
        "Open fast enough that a buyer still sends the enquiry.",
        "Keep that enquiry on the catalogue page.",
      ],
      features: ["Catalogue pages with their own addresses.", "Arabic and English, each able to be found.", "A commercial contact path that does not wait on a heavy brochure."],
    },
    availio: {
      h1: "Availio — Property Operations Software",
      overview: "The occupancy screen opens fast enough to catch an overlap, with units, pricing, and guest links in one place.",
      stack: "A light operations screen for the calendar an operator opens all day. Search ranking is not the job of this product. We do not publish a vendor stack or a speed score for this project.",
      results: "A preview of the product is published for review. We do not invent occupancy or revenue results.",
      liveLabel: "Open the Availio preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#saas">SaaS product development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Operations system",
      relatedB: "Hospitality website",
      metaTitle: "Availio Case Study | Property SaaS by Power Shift",
      metaDesc:
        "How Power Shift built Availio so a rental operator opens occupancy fast enough to catch a double booking before it is confirmed.",
      goals: [
        "See the clash before the second guest is confirmed.",
        "Keep the daily screen fast, because it is opened all day.",
        "Change price, units, and guest links without leaving that screen.",
      ],
      features: ["An occupancy calendar that stays quick to scan.", "Units and pricing on the same workflow.", "Guest links without a second tool.", "Reporting that does not freeze the day view."],
    },
    haseb: {
      h1: "7aseb — Operations & Finance System",
      overview: "Invoices, stock, and collections open fast on the phone they already use, in Arabic or English.",
      stack: "A light operations app for the screens an owner opens several times a day, in Arabic and English. Search ranking is not the job of this product. We do not publish a vendor stack or a speed score for this project.",
      results: "A preview of the system is published for review. We do not invent finance or usage metrics.",
      liveLabel: "Open the 7aseb preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#bms">custom operations systems</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Property operations software",
      relatedB: "Business website",
      metaTitle: "7aseb Case Study | Operations Software by Power Shift",
      metaDesc:
        "How Power Shift built 7aseb so an owner opens invoices, stock, and collections fast on a phone, in Arabic or English.",
      goals: [
        "Open an invoice without waiting, several times a day.",
        "Keep Arabic and English equally fast, including right-to-left.",
        "Send the follow-up on WhatsApp from the same screen.",
      ],
      features: ["Invoices that open on a phone.", "Stock and customers on the same light system.", "Collections and treasury without a second login.", "WhatsApp sharing from the record, in Arabic or English."],
    },
  },
  ar: {
    via: {
      h1: "VIA Holidays — موقع لحجز الرحلات",
      overview: "لكل وجهة صفحتها. تفتح على الموبايل، والاستفسار يُرسل من الصفحة نفسها.",
      stack: "صفحة خفيفة لكل وجهة، بالتشيكية والإنجليزية، حتى يصل المسافر إلى الرحلة التي يبحث عنها دون انتظار. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "المنتج يعمل على viaholidays.eu. لا ننشر أرقام زيارات أو حجوزات لهذا المشروع.",
      liveLabel: "افتح موقع VIA Holidays",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "متجر جمال",
      relatedB: "موقع علامة في الخليج",
      metaTitle: "دراسة حالة VIA Holidays | موقع سياحي من Power Shift",
      metaDesc: "موقع VIA Holidays: صفحة لكل وجهة، تفتح على الموبايل، والاستفسار يُرسل من الصفحة نفسها.",
      goals: [
        "أن يصل المسافر إلى بلد الرحلة، لا إلى صفحة عامة.",
        "أن تُفتح الصفحة وهو يقارن على الموبايل.",
        "أن يرسل الاستفسار قبل أن يغلقها.",
      ],
      features: [
        "صفحة لمصر، وصفحة للأردن، وصفحة لتركيا.",
        "الانتقالات وبرامج VIP على صفحات لا تثقُل.",
        "التشيكية والإنجليزية، ولكل لغة عنوانها.",
        "الاستفسار على الصفحة، لا خلف نموذج يُترك.",
      ],
    },
    heba: {
      h1: "د. هبة عز العرب — موقع عيادة يُحجز منه",
      overview:
        "صفحة للعيادة ولكل فرع في القاهرة. تفتح على الموبايل فورًا، والحجز على واتساب من الشاشة الأولى.",
      stack: "صفحة للعيادة وصفحة لكل فرع، خفيفة على الموبايل، والحجز على واتساب من أول شاشة. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "الموقع يعمل على drhebaezz.com. لا ننشر أرقام حجوزات أو زيارات لهذا المشروع.",
      liveLabel: "افتح موقع د. هبة عز العرب",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "موقع مكتب محاماة",
      relatedB: "موقع مركز قلب",
      metaTitle: "دراسة حالة د. هبة عز العرب | موقع عيادة من Power Shift",
      metaDesc:
        "موقع د. هبة عز العرب: صفحة للعيادة ولكل فرع في القاهرة، تفتح على الموبايل، والحجز على واتساب من الشاشة الأولى.",
      goals: [
        "أن تصل العائلة إلى العيادة والفرع، لا إلى الاسم وحده.",
        "أن تُفتح الصفحة للمريض أو لمن معه على الموبايل.",
        "أن يكون واتساب هو الحجز، من أول ما تظهر الصفحة.",
      ],
      features: [
        "صفحة للعيادة، وصفحة للقاهرة الجديدة، وصفحة للمهندسين.",
        "عربي وإنجليزي، ولكل لغة عنوانها.",
        "كلام تقرؤه العائلة، لا نشرة طبية.",
        "واتساب ظاهر، والصفحة لا تتأخر قبله.",
      ],
    },
    abdallah: {
      h1: "د. عبدالله أحمد عبدالله — موقع مركز قلب",
      overview: "لكل فحص صفحته. المريض يفتحها على موبايله ويحجز اتصالًا أو على واتساب.",
      stack: "صفحة خفيفة لكل فحص، وعنوان العيادة في العاشر من رمضان في مكانه الطبيعي. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "الموقع يعمل على dr-abdallah-cardio-center.com. لا ننشر أرقام حجوزات أو زيارات لهذا المشروع.",
      liveLabel: "افتح موقع مركز القلب التخصصي",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "موقع عيادة",
      relatedB: "موقع مكتب محاماة",
      metaTitle: "دراسة حالة د. عبدالله أحمد عبدالله | موقع عيادة من Power Shift",
      metaDesc:
        "موقع مركز القلب في العاشر من رمضان: صفحة لكل فحص، تُفتح على الموبايل، والحجز اتصال أو واتساب.",
      goals: [
        "أن يجد المريض عيادة القلب في العاشر من رمضان، لا اسم المركز فقط.",
        "أن تُفتح الصفحة في اللحظة التي يقرر فيها الاتصال.",
        "أن يرى رقم الهاتف وواتساب قبل أن يرجع.",
      ],
      features: [
        "صفحة للكشف، وصفحة للإيكو، ورسم القلب، وإيكو الأطفال.",
        "العنوان والمواعيد والعاشر من رمضان مكتوبة بوضوح.",
        "عربي وإنجليزي، ولكل لغة عنوانها.",
        "الحجز اتصال أو واتساب، على صفحة لا تثقُل.",
      ],
    },
    radwan: {
      h1: "رضوان عز العرب — موقع مكتب محاماة بالعربية",
      overview: "لكل مجال قانوني صفحته بالعربية. تفتح على الموبايل، وحجز الاستشارة على واتساب.",
      stack: "صفحة خفيفة لكل مجال، بالعربية، حتى يصل الباحث إلى المسألة التي يسأل عنها. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "نُشرت معاينة للموقع للمراجعة. لا نختلق أرقام قضايا أو استفسارات.",
      liveLabel: "افتح معاينة رضوان عز العرب",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "موقع عيادة",
      relatedB: "موقع سفر",
      metaTitle: "دراسة حالة رضوان عز العرب | موقع مكتب محاماة من Power Shift",
      metaDesc: "موقع رضوان عز العرب: صفحة لكل مجال قانوني بالعربية، تُفتح على الموبايل، والاستشارة تُحجز على واتساب.",
      goals: [
        "أن يصل الزائر إلى المسألة القانونية، لا إلى صفحة محامٍ عامة.",
        "أن تُفتح بالعربية على الموبايل الذي في يده.",
        "أن يحجز الاستشارة على واتساب من الصفحة نفسها.",
      ],
      features: [
        "صفحة للمدني، والتجاري، والشركات، والجنائي، والسيبراني، والأسرة، ومجلس الدولة.",
        "أمثلة قضايا بلا أسماء، تشرح العمل دون ذكر الموكلين.",
        "عربي واضح، على صفحة لا تثقُل.",
        "واتساب على الصفحة، لا نموذج في آخرها.",
      ],
    },
    medlab: {
      h1: "MedLab Market — كتالوج طبي ومخبري",
      overview: "لكل قطاع صفحته. يتصفح الكتالوج على موبايله، والسلة تصبح طلب عرض سعر.",
      stack: "صفحة خفيفة لكل قطاع، وبطاقة لكل منتج، حتى يصل مسؤول المشتريات إلى الخط ويطلب السعر دون كتالوج يثقُل. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results:
        "نُشرت معاينة للمتجر للمراجعة. حقول الدخول والتواصل في المعاينة واجهة فقط. لا نختلق أرقام مبيعات أو عروض سعر.",
      liveLabel: "افتح معاينة MedLab Market",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "متجر ملابس أطفال",
      relatedB: "تجارة جمال",
      metaTitle: "دراسة حالة MedLab Market | كتالوج طبي من Power Shift",
      metaDesc: "كتالوج MedLab: صفحة لكل قطاع، تصفح خفيف على الموبايل، والسلة تتحول إلى طلب عرض سعر.",
      goals: [
        "أن يصل إلى قطاعه، لا إلى كتالوج واحد مكدّس.",
        "أن يتصفح على موبايل مسؤول المشتريات دون انتظار.",
        "أن تخرج السلة عرض سعر، لا نموذجًا فارغًا.",
      ],
      features: [
        "مسار للمستشفيات، والمختبرات، والعلمي، والعناية، والكيماويات.",
        "بطاقات منتجات تبقى خفيفة وهو يقارن.",
        "السلة تصبح طلب عرض سعر.",
        "صفحات بالعربية. هذا العمل ما زال معاينة للمراجعة.",
      ],
    },
    adam: {
      h1: "Adam Trending — متجر ترنجات أطفال",
      overview: "صفحة للأولاد وصفحة للبنات. يختار المقاس على موبايله، والطلب يصل على واتساب.",
      stack: "صفحة خفيفة لكل مجموعة، والطلب يُرسل على واتساب، حتى يختار ولي الأمر الطقم دون انتظار. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "نُشرت معاينة للمتجر للمراجعة. لا نختلق أرقام مبيعات أو تحويل.",
      liveLabel: "افتح معاينة Adam Trending",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "كتالوج طبي",
      relatedB: "تجارة جمال",
      metaTitle: "دراسة حالة Adam Trending | متجر ملابس أطفال من Power Shift",
      metaDesc: "متجر Adam Trending: صفحة للأولاد وصفحة للبنات، واختيار المقاس على الموبايل، والطلب على واتساب.",
      goals: [
        "أن يصل ولي الأمر إلى المجموعة، لا إلى واجهة عامة.",
        "أن تُفتح الصفحة على الموبايل الذي في يده.",
        "أن يُرسل الطلب على واتساب، لا في نموذج يُترك.",
      ],
      features: [
        "مسار للأولاد ومسار للبنات.",
        "صفحة المنتج تبقى خفيفة عند اختيار المقاس.",
        "الطلب يخرج من السلة إلى واتساب.",
        "صفحات بالعربية. هذا العمل ما زال معاينة للمراجعة.",
      ],
    },
    nourvive: {
      h1: "Nourvive — متجر جمال يصل إلى المنتج",
      overview: "صفحة لكل منتج، بالعربي أو الإنجليزي. تفتح على الموبايل، والسلة لا تقف في منتصف الطريق.",
      stack: "صفحة خفيفة لكل منتج، بالعربي والإنجليزي، حتى يصل الزائر إلى الصنف وتكمل السلة. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "نُشرت معاينة للمتجر للمراجعة. لا نختلق أرقام مبيعات أو تحويل.",
      liveLabel: "افتح معاينة Nourvive",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال فاخرة",
      relatedB: "متجر أغذية",
      metaTitle: "دراسة حالة Nourvive | متجر جمال من Power Shift",
      metaDesc: "متجر Nourvive: صفحة لكل منتج بالعربي أو الإنجليزي، تُفتح على الموبايل، والسلة تكمل الطريق.",
      goals: [
        "أن يصل إلى المنتج الذي يبحث عنه، لا إلى نشرة.",
        "أن تُفتح الصفحة على الموبايل، بالعربي أو الإنجليزي.",
        "أن تبلغ السلة دون أن تقف الصفحة.",
      ],
      features: [
        "صفحة للعناية بالبشرة، وصفحة للشعر، وصفحة للميزوثيرابي.",
        "لكل منتج عنوانه، حتى يصل البحث إلى الصنف.",
        "سلة خفيفة.",
        "عربي وإنجليزي. هذا العمل ما زال معاينة للمراجعة.",
      ],
    },
    loofah: {
      h1: "Queen Loofah — متجر يُشترى منه على الموبايل",
      overview: "صفحة لكل منتج، والشراء يتم من السلة على الموبايل. ومن يريد التصدير يجد صفحة واضحة له.",
      stack: "صفحة خفيفة لكل منتج، وإتمام للطلب لا يتأخر، وصفحة تصدير لمن يسأل عنها. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "المتجر يعمل على loofahqueen.com. لا ننشر أرقام مبيعات لهذا المشروع.",
      liveLabel: "افتح متجر Queen Loofah",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال",
      relatedB: "جمال فاخر",
      metaTitle: "دراسة حالة Queen Loofah | متجر عناية من Power Shift",
      metaDesc: "متجر Queen Loofah: صفحة لكل منتج، شراء من السلة على الموبايل، وصفحة واضحة للتصدير.",
      goals: [
        "أن يصل المشتري إلى المنتج، لا إلى اسم العلامة فقط.",
        "أن يقرر على الموبايل والصفحة مفتوحة.",
        "أن يتم الطلب، أو يسأل عن التصدير، دون الرجوع إلى صفحة على السوشيال.",
      ],
      features: [
        "صفحة لكل منتج ولكل مجموعة.",
        "المتجر يبقى خفيفًا على الموبايل.",
        "الشراء يتم من السلة.",
        "صفحة تصدير يفتحها الشريك ويعرف ماذا يفعل.",
      ],
    },
    corolla: {
      h1: "Corolla — متجر أغذية وجملة",
      overview: "الأسرة تجد المنتج على متجر خفيف. الجملة لها مسارها، بعيدًا عن سلة البيت.",
      stack: "صفحات خفيفة لمن يشتري للبيت، ومسار مستقل للجملة، حتى لا يختلط البحثان. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "المتجر يعمل على corollaart.shop. لا ننشر أرقام مبيعات لهذا المشروع.",
      liveLabel: "افتح متجر Corolla",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال",
      relatedB: "موقع تجارة غذائية",
      metaTitle: "دراسة حالة Corolla | متجر أغذية من Power Shift",
      metaDesc: "متجر Corolla: الأسرة تجد المنتج على متجر خفيف، والجملة لها مسار لا يبطئ المتجر.",
      goals: ["أن تجد الأسرة المنتج الذي تبحث عنه.", "أن يبقى المتجر خفيفًا على الموبايل، وقصة المزرعة معه.", "أن تسلك الجملة طريقها دون أن تُثقل سلة البيت."],
      features: ["صفحات منتجات يطابقها البحث.", "متجر خفيف، وقصة المزرعة بجانب المنتجات.", "مسار جملة لا يجلس داخل سلة التجزئة."],
    },
    uruz: {
      h1: "URUZ — موقع جمال فاخر",
      overview: "لكل مجموعة صفحتها. الموقع فاخر ويبقى خفيفًا على الموبايل، والمتجر حيث يقف المشتري.",
      stack: "صفحات أنيقة تبقى خفيفة، ولكل مجموعة عنوانها، حتى لا تصبح الفخامة سببًا في البطء. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "الموقع يعمل على uruz-egypt.com. لا ننشر أرقام مبيعات لهذا المشروع.",
      liveLabel: "افتح موقع URUZ",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال",
      relatedB: "متجر علامة",
      metaTitle: "دراسة حالة URUZ | موقع جمال فاخر من Power Shift",
      metaDesc: "موقع URUZ: صفحة لكل مجموعة، موقع فاخر يبقى خفيفًا على الموبايل، والمتجر في مكانه.",
      goals: ["أن يصل المشتري إلى المجموعة، لا إلى صفحة مزاج واحدة.", "أن يبقى الموقع الفاخر خفيفًا على الموبايل.", "أن يكون المتجر حيث يقف، لا خلف مقدمة ثقيلة."],
      features: ["صفحة لكل مجموعة، وللطقوس، وللمكوّنات.", "الصور والخط لا يعطّلان الشاشة الأولى.", "المتجر في البنية الخفيفة نفسها."],
    },
    lodiamo: {
      h1: "Lodiamo — موقع تجارة غذائية في الإمارات",
      overview: "المشتري في الخليج يصل إلى خط المنتجات بالعربي أو الإنجليزي، ويرسل استفساره قبل أن يغلق الصفحة.",
      stack: "صفحات كتالوج خفيفة بالعربي والإنجليزي، ولكل خط عنوانه، والاستفسار على الصفحة. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "الموقع يعمل على lodiamo.com. لا ننشر أرقام زيارات أو عملاء محتملين لهذا المشروع.",
      liveLabel: "افتح موقع Lodiamo",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "موقع علامة دولية",
      relatedB: "تجارة أغذية",
      metaTitle: "دراسة حالة Lodiamo | موقع مؤسسي من Power Shift",
      metaDesc: "موقع Lodiamo: المشتري في الخليج يصل إلى خط المنتجات بالعربي أو الإنجليزي ويرسل استفساره قبل أن يغلق الصفحة.",
      goals: ["أن يصل إلى الخط باللغة التي يبحث بها.", "أن تُفتح الصفحة بما يكفي ليُرسل الاستفسار.", "أن يبقى الاستفسار على صفحة الكتالوج."],
      features: ["صفحة لكل خط في الكتالوج.", "عربي وإنجليزي، ولكل لغة عنوانها.", "تواصل تجاري على الصفحة، لا نشرة تنتظر."],
    },
    availio: {
      h1: "Availio — برنامج تشغيل للعقارات",
      overview: "شاشة الإشغال تفتح بسرعة تكفي لرؤية الحجز المزدوج قبل تأكيده. الوحدة والسعر ورابط الضيف في الشاشة نفسها.",
      stack: "شاشة خفيفة للتقويم الذي يفتحه المدير طوال النهار. ظهور الموقع في البحث ليس عمل هذا البرنامج. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "نُشرت معاينة للمنتج للمراجعة. لا نختلق أرقام إشغال أو إيرادات.",
      liveLabel: "افتح معاينة Availio",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#saas">تطوير منتجات SaaS</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "نظام تشغيل",
      relatedB: "موقع ضيافة",
      metaTitle: "دراسة حالة Availio | برمجيات عقارية من Power Shift",
      metaDesc: "Availio: شاشة الإشغال تفتح بسرعة تكفي لرؤية الحجز المزدوج قبل تأكيده.",
      goals: ["أن يرى التداخل قبل أن يؤكد الضيف الثاني.", "أن تبقى شاشة اليوم سريعة، لأنها تُفتح طوال النهار.", "أن يغيّر السعر والوحدة ورابط الضيف دون أن يغادرها."],
      features: ["تقويم إشغال يُمسح بنظرة.", "الوحدات والسعر في مسار العمل نفسه.", "رابط الضيف دون أداة ثانية.", "التقارير لا تجمّد عرض اليوم."],
    },
    haseb: {
      h1: "7aseb — نظام للفواتير والتشغيل",
      overview: "الفاتورة والمخزون والتحصيل تفتح على الموبايل الذي يحمله، بالعربي أو الإنجليزي، دون انتظار.",
      stack: "شاشات خفيفة لما يفتحه صاحب العمل عدة مرات في اليوم، بالعربي والإنجليزي. ظهور الموقع في البحث ليس عمل هذا النظام. لا ننشر اسم التقنية ولا رقم سرعة لهذا المشروع.",
      results: "نُشرت معاينة للنظام للمراجعة. لا نختلق أرقام استخدام أو مالية.",
      liveLabel: "افتح معاينة 7aseb",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/ar/services#bms">أنظمة التشغيل المخصصة</a>. اطّلع على <a href="/ar/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "برمجيات تشغيل عقاري",
      relatedB: "موقع أعمال",
      metaTitle: "دراسة حالة 7aseb | نظام تشغيل من Power Shift",
      metaDesc: "7aseb: الفاتورة والمخزون والتحصيل تفتح على الموبايل، بالعربي أو الإنجليزي، دون انتظار.",
      goals: ["أن تُفتح الفاتورة بلا انتظار، عدة مرات في اليوم.", "أن يبقى العربي والإنجليزي بالسرعة نفسها، والاتجاه من اليمين سليم.", "أن تخرج المتابعة على واتساب من الشاشة نفسها."],
      features: ["فاتورة تُفتح على الموبايل.", "المخزون والعملاء في النظام نفسه.", "التحصيل والخزينة دون تسجيل دخول ثانٍ.", "مشاركة على واتساب من السجل، بالعربي أو الإنجليزي."],
    },
  },
};

export const PAGE_TEXT = {
  en: {
    home: "Home",
    ourWork: "Our Work",
    viaCase: "VIA Holidays case study",
    nourviveCase: "Nourvive e-commerce work",
    servicesLink: "Web & software services",
    breadcrumb: "Breadcrumb",
    caseKicker: {},
    challenge: "The Challenge",
    goals: "Goals",
    solution: "The Solution",
    stack: "Technology Stack",
    features: "Key Features",
    results: "Results",
    relatedServices: "Related services",
    relatedProjects: "Related projects",
    ctaTitle: "Build Your Next Digital Product",
    ctaBody: "If you need a serious site, shop, or operations system, book a 20-minute scope call. We will tell you what should be built — and what should wait.",
    workKicker: "Portfolio",
    workH1: "Power Shift Work — Live Products from Cairo",
    workLead: "Clinics, legal, medical supply, retail, travel, and operations — live products and previews from the same studio in Cairo.",
    workServicesCta: "Explore our e-commerce development work",
    workMetaTitle: "Our Work | Power Shift Software Studio in Cairo",
    workMetaDesc: "Selected Power Shift work: clinic and legal websites, medical and retail shops, travel, and operations products built for companies in Egypt and the GCC.",
    servicesKicker: "Services",
    servicesH1: "Power Shift — Web Development & Custom Software in Cairo",
    servicesLead:
      "POWER SHIFT is a software studio in Cairo. We build the public face of a company and the system underneath it — for teams in Egypt and across the GCC, without claiming offices we do not have.",
    servicesSeeWork: "See live products",
    servicesWebsiteExtra:
      "Typical work includes bilingual Arabic/English sites, RTL interfaces, and a conversion path that leads to a call or WhatsApp — not a generic template.",
    servicesWebsiteRelated: 'Related work: <a href="/work/heba.html">Dr. Heba Ezz clinic website</a>, <a href="/work/radwan.html">Radwan Ezz El-Arab law office</a>, <a href="/work/via-holidays.html">VIA Holidays travel website</a>, and <a href="/work/lodiamo.html">Lodiamo corporate site</a>. More on <a href="/web-development-egypt">web development in Egypt</a> and <a href="/web-design-egypt">website design in Egypt</a>. From the blog: <a href="/blog/what-a-business-website-needs.html">what a business website actually needs</a>.',
    servicesCommerceExtra: "Built for retail, wholesale, and brand stores that need more than a brochure.",
    servicesCommerceRelated:
      'Related work: <a href="/work/medlab.html">MedLab Market catalogue</a>, <a href="/work/adam.html">Adam Trending kids shop</a>, <a href="/work/nourvive.html">Nourvive beauty store</a>, <a href="/work/corolla.html">Corolla food shop</a>, and <a href="/work/uruz.html">URUZ luxury beauty commerce</a>. Details: <a href="/ecommerce-website-development">ecommerce website development</a>. From the blog: <a href="/blog/ecommerce-website-or-catalogue-egypt.html">when you need a shop versus a catalogue</a>.',
    servicesSaasExtra: "We will say when a SaaS product is the right shape, and when a simpler site or operations tool should come first.",
    servicesSaasRelated:
      'Related work: <a href="/work/availio.html">Availio property operations software</a>. More on <a href="/custom-software-development">custom software development</a>. From the blog: <a href="/blog/website-or-custom-software.html">when a website is not enough and you need software</a>.',
    servicesOpsExtra: "These replace notebooks, spreadsheets, and scattered chats when the operation has outgrown them.",
    servicesOpsRelated:
      'Related work: <a href="/work/haseb.html">7aseb operations and finance system</a> and <a href="/work/availio.html">Availio booking control</a>. From the blog: <a href="/blog/website-or-custom-software.html">website versus a custom operations system</a>.',
    servicesFinal:
      "If you are searching for a software development company in Cairo, or a studio that can ship bilingual products for the GCC, start with a 20-minute scope call.",
    servicesMetaTitle: "Power Shift | Web Development & Custom Software in Cairo",
    servicesMetaDesc: "Power Shift builds custom websites, e-commerce platforms, SaaS products, and operations systems for companies in Egypt and the GCC.",
    contactH1: "Get a Free Website Prototype",
    contactLead:
      "Tell us what you sell and who the customer is. We prepare a first visual sample of how the business could look online, then take the brief to WhatsApp. POWER SHIFT is based in Cairo and builds for Egypt and the GCC.",
    contactMetaTitle: "Contact Power Shift | Free Website Prototype — Cairo",
    contactMetaDesc:
      "Request a free website prototype on WhatsApp or email. We reply with scope questions before any price. Cairo studio for Egypt and the GCC — 15 five-star reviews.",
    errorCode: "404",
    errorH1: "This page is unavailable.",
    errorLead: "The URL may have moved, or it may never have existed. The studio, the work, and the scope call are still here.",
    errorHome: "Back to the homepage",
    errorWork: "See our work",
    errorMetaTitle: "Page not found | POWER SHIFT",
    errorMetaDesc: "This Power Shift page is unavailable. Return to the homepage, portfolio, or book a scope call.",
    blogMetaTitle: "Blog | Websites, Search & Software Notes from Power Shift",
    blogMetaDesc:
      "Practical notes from Power Shift in Cairo: website cost in Egypt, Facebook versus a site, Google visibility, speed, leads, shops, and when to build software.",
  },
  ar: {
    home: "الرئيسية",
    ourWork: "أعمالنا",
    viaCase: "دراسة حالة VIA Holidays",
    nourviveCase: "عمل Nourvive في التجارة الإلكترونية",
    servicesLink: "خدمات الويب والبرمجيات",
    breadcrumb: "مسار التنقل",
    challenge: "التحدي",
    goals: "الأهداف",
    solution: "الحل",
    stack: "الأساس التقني",
    features: "أبرز الخصائص",
    results: "النتائج",
    relatedServices: "خدمات ذات صلة",
    relatedProjects: "مشاريع ذات صلة",
    ctaTitle: "ابنِ منتجك الرقمي التالي",
    ctaBody: "إذا احتجت موقعًا أو متجرًا أو نظام تشغيل جادًا، تواصل معنا. نحدد ما يستحق البناء وما يمكن أن ينتظر.",
    workKicker: "الأعمال",
    workH1: "أعمال Power Shift — منتجات حقيقية من القاهرة",
    workLead: "عيادات، وقانون، ومستلزمات طبية، وتجزئة، وسياحة، وتشغيل — منتجات حقيقية ومعاينات من الاستوديو نفسه في القاهرة.",
    workServicesCta: "استكشف أعمال التجارة الإلكترونية",
    workMetaTitle: "أعمال باور شيفت | نماذج مواقع ومتاجر نفذناها في مصر والخليج",
    workMetaDesc: "نماذج حقيقية من أعمال باور شيفت: مواقع عيادات ومكاتب محاماة، ومتاجر طبية وتجزئة، وسياحة، وأنظمة تشغيل لشركات في مصر والخليج. افتح كل موقع بنفسك.",
    servicesKicker: "الخدمات",
    servicesH1: "خدماتنا: مواقع شركات ومتاجر إلكترونية وأنظمة برمجية",
    servicesLead:
      "POWER SHIFT استوديو برمجيات في القاهرة. نبني الواجهة العامة للشركة والنظام الذي يشغّلها — لفرق في مصر والخليج، دون ادعاء مكاتب لا نملكها.",
    servicesSeeWork: "شاهد المنتجات العاملة",
    servicesWebsiteExtra: "يشمل العمل عادة مواقع عربي/إنجليزي، وواجهات RTL، ومسار تحويل يصل إلى مكالمة أو واتساب — لا قالبًا عامًا.",
    servicesWebsiteRelated:
      'أعمال ذات صلة: <a href="/work/heba.html">موقع عيادة د. هبة عز العرب</a>، و<a href="/work/radwan.html">موقع مكتب رضوان عز العرب</a>، و<a href="/work/via-holidays.html">موقع VIA Holidays السياحي</a>، و<a href="/work/lodiamo.html">موقع Lodiamo المؤسسي</a>. اعرف أكثر عن <a href="/ar/شركة-برمجة-مواقع">شركة برمجة مواقع</a> و<a href="/ar/تصميم-موقع-شركة">تصميم موقع شركة</a>.',
    servicesCommerceExtra: "للتجزئة والجملة ومتاجر العلامات التي تحتاج أكثر من صفحة تعريف.",
    servicesCommerceRelated:
      'أعمال ذات صلة: <a href="/work/medlab.html">كتالوج MedLab Market</a>، و<a href="/work/adam.html">متجر Adam Trending</a>، و<a href="/work/nourvive.html">متجر Nourvive</a>، و<a href="/work/corolla.html">متجر Corolla</a>، و<a href="/work/uruz.html">تجارة URUZ الفاخرة</a>. من المدونة: <a href="/ar/blog/ecommerce-website-or-catalogue-egypt.html">متى تحتاج متجرًا ومتى يكفي كتالوج</a>. التفاصيل في <a href="/ar/تصميم-متجر-الكتروني">تصميم متجر إلكتروني في مصر</a>.',
    servicesSaasExtra: "نوضح متى يكون منتج SaaS الشكل الصحيح، ومتى يكفي موقع أو أداة تشغيل أبسط.",
    servicesSaasRelated: 'أعمال ذات صلة: <a href="/work/availio.html">برمجيات Availio لتشغيل العقارات</a>. التفاصيل في <a href="/ar/برمجة-أنظمة-مخصصة">برمجة أنظمة مخصصة</a>. من المدونة: <a href="/ar/blog/website-or-custom-software.html">متى لا يكفي الموقع وتحتاج برنامجًا</a>.',
    servicesOpsExtra: "تحل محل الدفاتر وملفات Excel والمحادثات المتفرقة عندما يتجاوز التشغيل ذلك.",
    servicesOpsRelated:
      'أعمال ذات صلة: <a href="/work/haseb.html">نظام 7aseb للتشغيل والمالية</a> و<a href="/work/availio.html">ضبط حجوزات Availio</a>. من المدونة: <a href="/ar/blog/website-or-custom-software.html">الموقع مقابل نظام التشغيل المخصص</a>.',
    servicesFinal: "إذا كنت تبحث عن شركة برمجيات في القاهرة، أو استوديو يبني منتجات بلغتين للخليج، ابدأ باستشارة عشرين دقيقة.",
    servicesMetaTitle: "خدمات باور شيفت | مواقع شركات ومتاجر إلكترونية وأنظمة برمجية",
    servicesMetaDesc: "كل خدمات باور شيفت من القاهرة: موقع شركة، متجر إلكتروني، منتج SaaS، أو نظام تشغيل للفواتير والمخزون — عربي وإنجليزي وRTL. اعرف ما يناسب نشاطك قبل السعر.",
    contactH1: "احصل على نموذج موقع مجاني",
    contactLead:
      "قول لنا بتبيع إيه ومين عميلك. نجهّز عيّنة بصرية أولى لشكل النشاط أونلاين، ونحوّل الطلب لواتساب. POWER SHIFT في القاهرة، وتبني للشركات في مصر والخليج.",
    contactMetaTitle: "تواصل مع باور شيفت | نموذج موقع مجاني على واتساب",
    contactMetaDesc: "اطلب نموذج موقع مجاني على واتساب أو البريد. نرد بأسئلة النطاق قبل أي سعر. استوديو في القاهرة لمصر والخليج — 15 تقييم 5 نجوم.",
    errorCode: "404",
    errorH1: "هذه الصفحة غير متاحة.",
    errorLead: "ربما نُقل الرابط، أو لم يكن موجودًا. الاستوديو والأعمال والاستشارة ما زالت هنا.",
    errorHome: "العودة إلى الصفحة الرئيسية",
    errorWork: "شاهد أعمالنا",
    errorMetaTitle: "الصفحة غير موجودة | POWER SHIFT",
    errorMetaDesc: "هذه الصفحة غير متاحة. عد إلى الرئيسية أو الأعمال أو تواصل معنا.",
    blogMetaTitle: "المدونة | ملاحظات عن المواقع والبحث والبرمجيات من Power Shift",
    blogMetaDesc:
      "ملاحظات عملية من Power Shift في القاهرة: تكلفة الموقع في مصر، فيسبوك مقابل الموقع، الظهور على جوجل، السرعة، تحويل الزوار، المتاجر، ومتى تبني برنامجًا.",
  },
};
