export const PAGE_EXTRAS = {
  en: {
    via: {
      h1: "VIA Holidays — Travel Booking Platform",
      overview:
        "VIA Holidays needed one place for Czech travellers booking Egypt, Jordan, and Türkiye — tours, transfers, and enquiries — rather than scattered pages and messages.",
      stack:
        "A custom marketing website with Czech and English content, destination and transfer pages, and an enquiry path. We do not publish a vendor stack for this project.",
      results: "The product is live at viaholidays.eu. We do not publish traffic or conversion figures for this project.",
      liveLabel: "Open the live VIA Holidays website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Bilingual commerce",
      relatedB: "GCC brand website",
      metaTitle: "VIA Holidays Case Study | Travel Website by Power Shift",
      metaDesc:
        "How Power Shift built the VIA Holidays website for Czech travellers booking Egypt, Jordan, and Türkiye — destinations, transfers, and a clear enquiry path.",
      goals: [
        "Give travellers a single destination for Egypt, Jordan, and Türkiye holidays.",
        "Make tours, transfers, and VIP holidays easy to browse.",
        "Create a clear path to enquire without a confusing booking maze.",
      ],
      features: [
        "Destination pages for Egypt, Jordan, and Türkiye.",
        "Transfer and VIP holiday information in one place.",
        "Czech and English content for travellers from Czechia and beyond.",
        "A direct enquiry path instead of a generic contact dump.",
      ],
    },
    nourvive: {
      h1: "Nourvive — Bilingual Beauty Store",
      overview: "A Cairo beauty brand needed a bilingual shop for skincare, hair care, and mesotherapy — a real catalogue, not a brochure.",
      stack: "A custom e-commerce storefront with bilingual catalogue pages and cart flows. We do not publish a vendor stack for this project.",
      results: "A preview storefront is published for review. We do not invent sales or conversion results.",
      liveLabel: "Open the Nourvive preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Luxury beauty commerce",
      relatedB: "Food retail store",
      metaTitle: "Nourvive Case Study | Beauty E-commerce by Power Shift",
      metaDesc:
        "How Power Shift built a bilingual Cairo beauty storefront for Nourvive — categories, product pages, cart, and English / Arabic switching.",
      goals: [
        "Sell products through a real catalogue rather than a static lookbook.",
        "Support English and Arabic in the same storefront.",
        "Give shoppers categories, product pages, and a cart.",
      ],
      features: [
        "Category browsing for skincare, hair care, and mesotherapy.",
        "Product pages built for a real catalogue.",
        "Cart and storefront flows.",
        "English / Arabic switching.",
      ],
    },
    corolla: {
      h1: "Corolla — Food E-commerce & Wholesale",
      overview: "An Egyptian dried-fruit brand needed to sell to households and take wholesale enquiries without looking generic.",
      stack: "A custom brand e-commerce site with retail browsing and a wholesale enquiry path. We do not publish a vendor stack for this project.",
      results: "The shop is live at corollaart.shop. We do not publish sales figures for this project.",
      liveLabel: "Open the live Corolla shop",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty commerce",
      relatedB: "Food trade website",
      metaTitle: "Corolla Case Study | Food E-commerce by Power Shift",
      metaDesc: "How Power Shift built a brand shop for Corolla, an Egyptian dried-fruit company selling to households and taking wholesale enquiries.",
      goals: [
        "Sell the collection to households through a brand shop.",
        "Tell the farm story without burying the products.",
        "Keep a separate path for bulk and wholesale enquiries.",
      ],
      features: ["Collection-led product browsing.", "Brand and farm story pages.", "A bulk-order path alongside retail."],
    },
    uruz: {
      h1: "URUZ — Luxury Beauty Commerce",
      overview: "A natural-beauty house needed a brand world — collections, rituals, ingredients — not only a product grid.",
      stack: "A custom editorial commerce website. We do not publish a vendor stack for this project.",
      results: "The site is live at uruz-egypt.com. We do not publish sales figures for this project.",
      liveLabel: "Open the live URUZ website",
      relatedHtml:
        'This project sits with our <a href="/services#ecommerce">e-commerce development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Beauty commerce",
      relatedB: "Brand retail shop",
      metaTitle: "URUZ Case Study | Luxury Beauty Website by Power Shift",
      metaDesc: "How Power Shift built a high-end beauty site for URUZ with editorial structure, collections, and a shop at uruz-egypt.com.",
      goals: [
        "Present collections, rituals, and ingredients as a brand world.",
        "Keep the shop inside that editorial structure.",
        "Hold a luxury tone without hiding the products.",
      ],
      features: ["Editorial structure around collections and rituals.", "Ingredient and brand storytelling.", "A shop integrated into the brand site."],
    },
    lodiamo: {
      h1: "Lodiamo — UAE Food Trade Website",
      overview: "A UAE import/export food company needed a bilingual presence for premium agricultural products.",
      stack: "A custom bilingual corporate website. We do not publish a vendor stack for this project.",
      results: "The site is live at lodiamo.com. We do not publish lead or traffic figures for this project.",
      liveLabel: "Open the live Lodiamo website",
      relatedHtml:
        'This project sits with our <a href="/services#website">custom website development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "International brand site",
      relatedB: "Food commerce",
      metaTitle: "Lodiamo Case Study | Bilingual Corporate Site by Power Shift",
      metaDesc:
        "How Power Shift built a bilingual corporate site for Lodiamo, a UAE import/export food company, with catalogue and commercial contact paths.",
      goals: [
        "Give the company a bilingual corporate presence.",
        "Show the catalogue of premium agricultural products.",
        "Open a direct commercial contact path.",
      ],
      features: ["Bilingual corporate presence.", "Catalogue of premium agricultural products.", "Direct commercial contact path."],
    },
    availio: {
      h1: "Availio — Property Operations Software",
      overview: "Short-term rental operators were running units in chats and spreadsheets — overlaps and pricing were easy to miss.",
      stack: "A custom web application for property operations. We do not publish a vendor stack for this project.",
      results: "A preview of the product is published for review. We do not invent occupancy or revenue results.",
      liveLabel: "Open the Availio preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#saas">SaaS product development</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Operations system",
      relatedB: "Hospitality website",
      metaTitle: "Availio Case Study | Property SaaS by Power Shift",
      metaDesc:
        "How Power Shift built Availio, a booking-control product for short-term rental operators: occupancy calendar, units, pricing, guest links, and reporting.",
      goals: [
        "Replace chat-and-spreadsheet operations with one booking-control product.",
        "Show occupancy clearly so overlaps are harder to miss.",
        "Keep units, pricing, guest links, and reporting together.",
      ],
      features: ["Occupancy calendar.", "Unit and pricing control.", "Guest links.", "Reporting for operators."],
    },
    haseb: {
      h1: "7aseb — Operations & Finance System",
      overview: "Small businesses needed invoicing, stock, customers, and payment follow-up in one place — Arabic and English.",
      stack: "A custom operations web application with bilingual RTL support. We do not publish a vendor stack for this project.",
      results: "A preview of the system is published for review. We do not invent finance or usage metrics.",
      liveLabel: "Open the 7aseb preview",
      previewNote: "This project is shown as a preview, not a claim of public launch metrics.",
      relatedHtml:
        'This project sits with our <a href="/services#bms">custom operations systems</a> work. See all <a href="/services">software and web development services</a>.',
      relatedA: "Property operations software",
      relatedB: "Business website",
      metaTitle: "7aseb Case Study | Operations Software by Power Shift",
      metaDesc:
        "How Power Shift built 7aseb, an Arabic and English operations system for invoices, inventory, CRM, treasury, and WhatsApp sharing.",
      goals: [
        "Put invoices, inventory, customers, and payment follow-up in one system.",
        "Support Arabic and English, including RTL.",
        "Make sharing operational updates over WhatsApp part of the workflow.",
      ],
      features: ["Invoicing.", "Inventory.", "CRM.", "Treasury and payment follow-up.", "WhatsApp sharing.", "Full RTL."],
    },
  },
  ar: {
    via: {
      h1: "VIA Holidays — منصة حجز سياحي",
      overview:
        "احتاج VIA Holidays مكانًا واحدًا للمسافرين التشيكيين إلى مصر والأردن وتركيا: الجولات والانتقالات والاستفسارات، بدل صفحات ومحادثات متفرقة.",
      stack: "موقع تسويقي مخصص بالتشيكية والإنجليزية، مع صفحات وجهات وانتقالات ومسار استفسار واضح. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "المنتج يعمل على viaholidays.eu. لا ننشر أرقام زيارات أو تحويلات لهذا المشروع.",
      liveLabel: "افتح موقع VIA Holidays",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة إلكترونية بلغتين",
      relatedB: "موقع علامة في الخليج",
      metaTitle: "دراسة حالة VIA Holidays | موقع سياحي من Power Shift",
      metaDesc: "كيف بنت Power Shift موقع VIA Holidays للمسافرين التشيكيين إلى مصر والأردن وتركيا — وجهات وانتقالات ومسار استفسار واضح.",
      goals: [
        "مكان واحد لرحلات مصر والأردن وتركيا.",
        "تصفح سهل للجولات والانتقالات وبرامج VIP.",
        "مسار واضح لطلب الاستفسار دون تشتيت.",
      ],
      features: [
        "صفحات وجهات لمصر والأردن وتركيا.",
        "معلومات الانتقالات وبرامج VIP في مكان واحد.",
        "محتوى بالتشيكية والإنجليزية.",
        "مسار استفسار مباشر.",
      ],
    },
    nourvive: {
      h1: "Nourvive — متجر جمال بلغتين",
      overview: "علامة جمال في القاهرة احتاجت متجرًا بلغتين للعناية بالبشرة والشعر والميزوثيرابي — كتالوج حقيقي لا صفحة تعريف.",
      stack: "متجر إلكتروني مخصص بكتالوج بلغتين ومسار سلة. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "نُشرت معاينة للمتجر للمراجعة. لا نختلق أرقام مبيعات أو تحويل.",
      liveLabel: "افتح معاينة Nourvive",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال فاخرة",
      relatedB: "متجر أغذية",
      metaTitle: "دراسة حالة Nourvive | متجر جمال من Power Shift",
      metaDesc: "كيف بنت Power Shift متجر Nourvive في القاهرة بلغتين — أقسام ومنتجات وسلة وتبديل بين العربي والإنجليزي.",
      goals: ["بيع عبر كتالوج حقيقي لا كتيب ثابت.", "دعم العربي والإنجليزي في المتجر نفسه.", "أقسام وصفحات منتجات وسلة شراء."],
      features: ["تصفح أقسام العناية بالبشرة والشعر والميزوثيرابي.", "صفحات منتجات لكتالوج كامل.", "سلة ومسار شراء.", "تبديل بين العربي والإنجليزي."],
    },
    corolla: {
      h1: "Corolla — تجارة أغذية وجملة",
      overview: "علامة مصرية للفواكه المجففة أرادت البيع للمستهلك واستقبال طلبات الجملة من متجر يعكس هويتها.",
      stack: "متجر علامة مخصص للتجزئة مع مسار لطلبات الجملة. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "المتجر يعمل على corollaart.shop. لا ننشر أرقام مبيعات لهذا المشروع.",
      liveLabel: "افتح متجر Corolla",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال",
      relatedB: "موقع تجارة غذائية",
      metaTitle: "دراسة حالة Corolla | متجر أغذية من Power Shift",
      metaDesc: "كيف بنت Power Shift متجر Corolla لعلامة فواكه مجففة مصرية تبيع للمستهلك وتستقبل طلبات الجملة.",
      goals: ["بيع المجموعة للأسر عبر متجر العلامة.", "رواية قصة المنتج دون إخفاء السلع.", "مسار مستقل لطلبات الجملة."],
      features: ["تصفح حسب المجموعة.", "صفحات قصة العلامة والمزرعة.", "مسار طلبات جملة بجانب التجزئة."],
    },
    uruz: {
      h1: "URUZ — تجارة جمال فاخرة",
      overview: "دار عناية طبيعية احتاجت عالمًا للعلامة: المجموعات والطقوس والمكوّنات — لا شبكة منتجات فقط.",
      stack: "موقع تجارة تحريري مخصص. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "الموقع يعمل على uruz-egypt.com. لا ننشر أرقام مبيعات لهذا المشروع.",
      liveLabel: "افتح موقع URUZ",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#ecommerce">تطوير التجارة الإلكترونية</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "تجارة جمال",
      relatedB: "متجر علامة",
      metaTitle: "دراسة حالة URUZ | موقع جمال فاخر من Power Shift",
      metaDesc: "كيف بنت Power Shift موقع URUZ بهيكل تحريري ومجموعات ومتجر على uruz-egypt.com.",
      goals: ["عرض المجموعات والطقوس والمكوّنات كعالم علامة.", "إبقاء المتجر داخل هذا الهيكل.", "نبرة فاخرة دون إخفاء المنتجات."],
      features: ["هيكل تحريري حول المجموعات والطقوس.", "سرد المكوّنات والعلامة.", "متجر مدمج في موقع العلامة."],
    },
    lodiamo: {
      h1: "Lodiamo — موقع تجارة غذائية إماراتي",
      overview: "شركة إماراتية للاستيراد والتصدير الغذائي احتاجت حضورًا بلغتين لمنتجات زراعية فاخرة.",
      stack: "موقع مؤسسي مخصص بلغتين. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "الموقع يعمل على lodiamo.com. لا ننشر أرقام زيارات أو عملاء محتملين لهذا المشروع.",
      liveLabel: "افتح موقع Lodiamo",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#website">تطوير المواقع المخصصة</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "موقع علامة دولية",
      relatedB: "تجارة أغذية",
      metaTitle: "دراسة حالة Lodiamo | موقع مؤسسي من Power Shift",
      metaDesc: "كيف بنت Power Shift موقع Lodiamo بلغتين لشركة إماراتية للاستيراد والتصدير الغذائي.",
      goals: ["حضور مؤسسي بلغتين.", "عرض كتالوج المنتجات الزراعية الفاخرة.", "مسار تواصل تجاري مباشر."],
      features: ["حضور مؤسسي بلغتين.", "كتالوج منتجات زراعية فاخرة.", "مسار تواصل تجاري مباشر."],
    },
    availio: {
      h1: "Availio — برمجيات تشغيل عقاري",
      overview: "مشغّلو الإيجار قصير المدة كانوا يديرون الوحدات بالمحادثات وملفات Excel، فيسهل تداخل الحجوزات ويصعب ضبط السعر.",
      stack: "تطبيق ويب مخصص لتشغيل العقارات. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "نُشرت معاينة للمنتج للمراجعة. لا نختلق أرقام إشغال أو إيرادات.",
      liveLabel: "افتح معاينة Availio",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#saas">تطوير منتجات SaaS</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "نظام تشغيل",
      relatedB: "موقع ضيافة",
      metaTitle: "دراسة حالة Availio | برمجيات عقارية من Power Shift",
      metaDesc: "كيف بنت Power Shift Availio لضبط حجوزات الإيجار قصير المدة: تقويم إشغال ووحدات وتسعير وروابط للضيوف وتقارير.",
      goals: ["استبدال المحادثات وExcel بمنتج واحد لضبط الحجوزات.", "إظهار الإشغال بوضوح لتقليل التداخل.", "جمع الوحدات والتسعير وروابط الضيوف والتقارير."],
      features: ["تقويم إشغال.", "ضبط الوحدات والتسعير.", "روابط للضيوف.", "تقارير للمشغّلين."],
    },
    haseb: {
      h1: "7aseb — نظام تشغيل ومالية",
      overview: "شركات صغيرة احتاجت الفواتير والمخزون والعملاء ومتابعة التحصيل في مكان واحد، بالعربي والإنجليزي.",
      stack: "تطبيق تشغيل مخصص بدعم RTL ولغتين. لا ننشر حزمة تقنية لهذا المشروع.",
      results: "نُشرت معاينة للنظام للمراجعة. لا نختلق أرقام استخدام أو مالية.",
      liveLabel: "افتح معاينة 7aseb",
      previewNote: "يُعرض هذا المشروع كمعاينة، لا كأرقام إطلاق معلنة.",
      relatedHtml:
        'يندرج هذا المشروع ضمن <a href="/services#bms">أنظمة التشغيل المخصصة</a>. اطّلع على <a href="/services">خدمات تطوير البرمجيات والمواقع</a>.',
      relatedA: "برمجيات تشغيل عقاري",
      relatedB: "موقع أعمال",
      metaTitle: "دراسة حالة 7aseb | نظام تشغيل من Power Shift",
      metaDesc: "كيف بنت Power Shift نظام 7aseb بالعربي والإنجليزي للفواتير والمخزون وCRM والخزينة والمشاركة عبر واتساب.",
      goals: ["جمع الفواتير والمخزون والعملاء ومتابعة التحصيل في نظام واحد.", "دعم العربي والإنجليزي بما في ذلك RTL.", "جعل المشاركة عبر واتساب جزءًا من العمل."],
      features: ["فواتير.", "مخزون.", "CRM.", "خزينة ومتابعة تحصيل.", "مشاركة واتساب.", "RTL كامل."],
    },
  },
};

export const PAGE_TEXT = {
  en: {
    home: "Home",
    ourWork: "Our Work",
    viaCase: "VIA Holidays case study",
    nourviveCase: "Nourvive e-commerce work",
    servicesLink: "Web & software services",
    breadcrumb: "Breadcrumb",
    caseKicker: {},
    challenge: "The Challenge",
    goals: "Goals",
    solution: "The Solution",
    stack: "Technology Stack",
    features: "Key Features",
    results: "Results",
    relatedServices: "Related services",
    relatedProjects: "Related projects",
    ctaTitle: "Build Your Next Digital Product",
    ctaBody: "If you need a serious site, shop, or operations system, book a 20-minute scope call. We will tell you what should be built — and what should wait.",
    workKicker: "Portfolio",
    workH1: "Our Work",
    workLead: "Travel, beauty, food, property, and operations — live products and previews from the same studio in Cairo.",
    workServicesCta: "Explore our e-commerce development work",
    workMetaTitle: "Our Work | Power Shift Software Studio in Cairo",
    workMetaDesc: "Selected Power Shift work: travel, beauty, food, property, and operations products built for companies in Egypt and the GCC.",
    servicesKicker: "Services",
    servicesH1: "Web Development & Custom Software in Cairo",
    servicesLead:
      "POWER SHIFT is a software studio in Cairo. We build the public face of a company and the system underneath it — for teams in Egypt and across the GCC, without claiming offices we do not have.",
    servicesSeeWork: "See live products",
    servicesWebsiteExtra:
      "Typical work includes bilingual Arabic/English sites, RTL interfaces, and a conversion path that leads to a call or WhatsApp — not a generic template.",
    servicesWebsiteRelated: 'Related work: <a href="/work/via-holidays.html">VIA Holidays travel website</a> and <a href="/work/lodiamo.html">Lodiamo corporate site</a>.',
    servicesCommerceExtra: "Built for retail, wholesale, and brand stores that need more than a brochure.",
    servicesCommerceRelated:
      'Related work: <a href="/work/nourvive.html">Nourvive beauty store</a>, <a href="/work/corolla.html">Corolla food shop</a>, and <a href="/work/uruz.html">URUZ luxury beauty commerce</a>.',
    servicesSaasExtra: "We will say when a SaaS product is the right shape, and when a simpler site or operations tool should come first.",
    servicesSaasRelated: 'Related work: <a href="/work/availio.html">Availio property operations software</a>.',
    servicesOpsExtra: "These replace notebooks, spreadsheets, and scattered chats when the operation has outgrown them.",
    servicesOpsRelated:
      'Related work: <a href="/work/haseb.html">7aseb operations and finance system</a> and <a href="/work/availio.html">Availio booking control</a>.',
    servicesFinal:
      "If you are searching for a software development company in Cairo, or a studio that can ship bilingual products for the GCC, start with a 20-minute scope call.",
    servicesMetaTitle: "Web & Software Development Services in Cairo | Power Shift",
    servicesMetaDesc: "Power Shift builds custom websites, e-commerce platforms, SaaS products, and operations systems for companies in Egypt and the GCC.",
    contactH1: "Book a Scope Call",
    contactLead:
      "Tell us what you need. We will take it to WhatsApp with the brief already written. POWER SHIFT is based in Cairo, Egypt, and builds for companies in Egypt and the GCC.",
    contactMetaTitle: "Book a Scope Call | Power Shift Cairo",
    contactMetaDesc:
      "Book a 20-minute Power Shift scope call. Software studio in Cairo — websites, e-commerce, SaaS, and operations systems for Egypt and the GCC.",
    errorCode: "404",
    errorH1: "This page is unavailable.",
    errorLead: "The URL may have moved, or it may never have existed. The studio, the work, and the scope call are still here.",
    errorHome: "Back to the homepage",
    errorWork: "See our work",
    errorMetaTitle: "Page not found | POWER SHIFT",
    errorMetaDesc: "This Power Shift page is unavailable. Return to the homepage, portfolio, or book a scope call.",
  },
  ar: {
    home: "الرئيسية",
    ourWork: "أعمالنا",
    viaCase: "دراسة حالة VIA Holidays",
    nourviveCase: "عمل Nourvive في التجارة الإلكترونية",
    servicesLink: "خدمات الويب والبرمجيات",
    breadcrumb: "مسار التنقل",
    challenge: "التحدي",
    goals: "الأهداف",
    solution: "الحل",
    stack: "الأساس التقني",
    features: "أبرز الخصائص",
    results: "النتائج",
    relatedServices: "خدمات ذات صلة",
    relatedProjects: "مشاريع ذات صلة",
    ctaTitle: "ابنِ منتجك الرقمي التالي",
    ctaBody: "إذا احتجت موقعًا أو متجرًا أو نظام تشغيل جادًا، تواصل معنا. نحدد ما يستحق البناء وما يمكن أن ينتظر.",
    workKicker: "الأعمال",
    workH1: "أعمالنا",
    workLead: "سياحة، وجمال، وأغذية، وعقارات، وتشغيل — منتجات حقيقية ومعاينات من الاستوديو نفسه في القاهرة.",
    workServicesCta: "استكشف أعمال التجارة الإلكترونية",
    workMetaTitle: "أعمالنا | Power Shift استوديو برمجيات في القاهرة",
    workMetaDesc: "أعمال مختارة من Power Shift: سياحة وجمال وأغذية وعقارات وأنظمة تشغيل لشركات في مصر والخليج.",
    servicesKicker: "الخدمات",
    servicesH1: "تطوير مواقع وبرمجيات مخصصة في القاهرة",
    servicesLead:
      "POWER SHIFT استوديو برمجيات في القاهرة. نبني الواجهة العامة للشركة والنظام الذي يشغّلها — لفرق في مصر والخليج، دون ادعاء مكاتب لا نملكها.",
    servicesSeeWork: "شاهد المنتجات العاملة",
    servicesWebsiteExtra: "يشمل العمل عادة مواقع عربي/إنجليزي، وواجهات RTL، ومسار تحويل يصل إلى مكالمة أو واتساب — لا قالبًا عامًا.",
    servicesWebsiteRelated:
      'أعمال ذات صلة: <a href="/work/via-holidays.html">موقع VIA Holidays السياحي</a> و<a href="/work/lodiamo.html">موقع Lodiamo المؤسسي</a>.',
    servicesCommerceExtra: "للتجزئة والجملة ومتاجر العلامات التي تحتاج أكثر من صفحة تعريف.",
    servicesCommerceRelated:
      'أعمال ذات صلة: <a href="/work/nourvive.html">متجر Nourvive</a>، و<a href="/work/corolla.html">متجر Corolla</a>، و<a href="/work/uruz.html">تجارة URUZ الفاخرة</a>.',
    servicesSaasExtra: "نوضح متى يكون منتج SaaS الشكل الصحيح، ومتى يكفي موقع أو أداة تشغيل أبسط.",
    servicesSaasRelated: 'أعمال ذات صلة: <a href="/work/availio.html">برمجيات Availio لتشغيل العقارات</a>.',
    servicesOpsExtra: "تحل محل الدفاتر وملفات Excel والمحادثات المتفرقة عندما يتجاوز التشغيل ذلك.",
    servicesOpsRelated:
      'أعمال ذات صلة: <a href="/work/haseb.html">نظام 7aseb للتشغيل والمالية</a> و<a href="/work/availio.html">ضبط حجوزات Availio</a>.',
    servicesFinal: "إذا كنت تبحث عن شركة برمجيات في القاهرة، أو استوديو يبني منتجات بلغتين للخليج، ابدأ باستشارة عشرين دقيقة.",
    servicesMetaTitle: "خدمات تطوير المواقع والبرمجيات في القاهرة | Power Shift",
    servicesMetaDesc: "تبني Power Shift مواقع مخصصة ومتاجر إلكترونية ومنتجات SaaS وأنظمة تشغيل للشركات في مصر والخليج.",
    contactH1: "تواصل معنا",
    contactLead:
      "قل لنا ما تحتاجه، ونحوّل الطلب إلى واتساب والتفاصيل مكتوبة. POWER SHIFT في القاهرة، مصر، وتبني للشركات في مصر والخليج.",
    contactMetaTitle: "تواصل معنا | Power Shift القاهرة",
    contactMetaDesc: "تواصل مع Power Shift. استوديو برمجيات في القاهرة — مواقع ومتاجر وSaaS وأنظمة تشغيل لمصر والخليج.",
    errorCode: "404",
    errorH1: "هذه الصفحة غير متاحة.",
    errorLead: "ربما نُقل الرابط، أو لم يكن موجودًا. الاستوديو والأعمال والاستشارة ما زالت هنا.",
    errorHome: "العودة إلى الصفحة الرئيسية",
    errorWork: "شاهد أعمالنا",
    errorMetaTitle: "الصفحة غير موجودة | POWER SHIFT",
    errorMetaDesc: "هذه الصفحة غير متاحة. عد إلى الرئيسية أو الأعمال أو تواصل معنا.",
  },
};
