export const ORIGIN = "https://www.powershift.space";

export const CATEGORIES = [
  { id: "websites", en: "Websites", ar: "المواقع" },
  { id: "seo", en: "SEO", ar: "الظهور على جوجل" },
  { id: "conversion", en: "Leads", ar: "تحويل الزوار" },
  { id: "ecommerce", en: "E-commerce", ar: "التجارة الإلكترونية" },
  { id: "strategy", en: "Strategy", ar: "الاستراتيجية" },
];

export const UI = {
  en: {
    home: "Home",
    blog: "Blog",
    kicker: "Notes",
    h1: "Power Shift Blog — Clear Answers Before You Build",
    lead: "For owners who already have a business, and now need a website, a shop, or a system. What to build, what can wait, and how customers are supposed to find you.",
    seoTitle: "Blog | Websites, Search & Software Notes from Power Shift",
    seoDescription:
      "Practical notes from Power Shift in Cairo: website cost in Egypt, Facebook versus a site, Google visibility, speed, leads, shops, and when to build software.",
    featured: "Start here",
    latest: "All notes",
    popular: "Also useful",
    searchLabel: "Search",
    searchPlaceholder: "Cost, Google, WhatsApp, shop…",
    all: "All",
    empty: "Nothing matches that search. Try a shorter phrase, or browse the list.",
    read: "Read the note",
    author: "Nasser Ahmed",
    published: "Published",
    updated: "Updated",
    toc: "In this note",
    related: "Keep reading",
    ctaKicker: "Next",
    ctaTitle: "If the next step is a build",
    ctaBody:
      "A 20-minute scope call is enough to say whether you need a site, a shop, or an operations tool — and what can wait.",
    ctaButton: "Book a Scope Call",
  },
  ar: {
    home: "الرئيسية",
    blog: "المدونة",
    kicker: "ملاحظات",
    h1: "مدونة Power Shift — إجابات واضحة قبل ما تبني",
    lead: "لأصحاب الشركات اللي عندهم نشاط قائم، ويحتاجون موقعًا أو متجرًا أو نظامًا. ماذا تبني، وماذا يمكن أن ينتظر، وكيف يجدك العميل.",
    seoTitle: "المدونة | ملاحظات عن المواقع والبحث والبرمجيات من Power Shift",
    seoDescription:
      "ملاحظات عملية من Power Shift في القاهرة: تكلفة الموقع في مصر، فيسبوك مقابل الموقع، الظهور على جوجل، السرعة، تحويل الزوار، المتاجر، ومتى تبني برنامجًا.",
    featured: "ابدأ من هنا",
    latest: "كل الملاحظات",
    popular: "مفيد أيضًا",
    searchLabel: "بحث",
    searchPlaceholder: "تكلفة، جوجل، واتساب، متجر…",
    all: "الكل",
    empty: "لا توجد نتيجة لهذا البحث. جرّب كلمة أقصر، أو تصفّح القائمة.",
    read: "اقرأ الملاحظة",
    author: "ناصر أحمد",
    published: "نُشر",
    updated: "حُدّث",
    toc: "في هذه الملاحظة",
    related: "اقرأ أيضًا",
    ctaKicker: "بعد ذلك",
    ctaTitle: "إذا كانت الخطوة التالية هي البناء",
    ctaBody: "استشارة عشرين دقيقة تكفي لنقول إن كنت تحتاج موقعًا أو متجرًا أو أداة تشغيل — وما يمكن أن ينتظر.",
    ctaButton: "تواصل معنا",
  },
};

export const ARTICLES = [
  {
    id: "website-cost-egypt",
    slug: "how-much-does-a-website-cost-in-egypt",
    featured: true,
    popular: true,
    category: "websites",
    tone: "navy",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["facebook-or-website", "what-business-website-needs", "choose-web-company-egypt"],
    en: {
      title: "How much does a website cost in Egypt?",
      h1: "How much does a website cost in Egypt?",
      seoTitle: "How Much Does a Website Cost in Egypt? | Power Shift",
      seoDescription:
        "What actually changes website cost in Egypt: pages, languages, shop, and software. No fake price list — how to brief a studio without getting a guess.",
      excerpt: "There is no honest single number. Cost follows the job: a brochure, a bilingual site, a shop, or software staff will use every day.",
      ogAlt: "Note on website cost in Egypt from Power Shift",
      primaryKeyword: "website cost Egypt",
      secondaryKeywords: ["how much does a website cost in Egypt", "business website price Egypt", "website development cost"],
      ctaTitle: "Need a number that matches your brief?",
      ctaBody: "Send what you sell, who should enquire, and which language the site must speak. We will say what should be built — not a price invented before the job is clear.",
      body: [
        ["p", "Owners ask this before they ask anything else, and they are right to. A website is a real expense. The unhelpful answer is a single figure pulled from a Facebook ad. The useful answer is what changes the figure, so you can tell a serious quote from a guess."],
        ["p", "POWER SHIFT does not publish a rate card. Work is scoped after a short brief. What follows is how cost actually moves in Egypt — not a disguised price list."],
        ["h2", "Why one price is almost always wrong"],
        ["p", "A five-page company site in one language is not the same job as a bilingual catalogue, a shop that takes payment, or software that replaces spreadsheets. If two quotes are far apart, they are usually describing two different products. Ask each company to write down the pages, languages, and what happens after someone clicks."],
        ["p", "Cheap templates exist. They look finished until you need Arabic done properly, a WhatsApp path that does not dump people into a generic form, or a change six months later. The rebuild then costs more than doing the first version with a clear brief."],
        ["h2", "What actually changes the cost"],
        ["ul", [
          "Scope: a few marketing pages versus a catalogue, booking, or checkout.",
          "Language: English only is simpler. Arabic with correct RTL, plus English, is a different build — see <a href=\"/blog/bilingual-arabic-english-website-egypt-gcc.html\">why bilingual sites for Egypt and the GCC are their own problem</a>.",
          "Content: you writing the copy versus the studio inventing it. Invented copy is slow and usually wrong.",
          "Integrations: payments, shipping, inventory, or a booking calendar.",
          "Who maintains it: a site you cannot edit becomes expensive the first time a price changes.",
        ]],
        ["h2", "Four jobs people confuse with “a website”"],
        ["h3", "A brochure"],
        ["p", "Who you are, what you sell, how to contact you. This is the smallest serious site. It still needs clear pages and a path to a call or WhatsApp. It is not a shop."],
        ["h3", "A marketing site with real structure"],
        ["p", "Service or destination pages, maybe two languages, maybe a simple enquiry flow. This is what most established companies actually need. Read <a href=\"/blog/what-a-business-website-needs.html\">what a business website actually needs</a> before you add extras."],
        ["h3", "A shop"],
        ["p", "Products, stock, checkout or wholesale enquiry. That is <a href=\"/services#ecommerce\">e-commerce work</a>, not a brochure with a buy button stuck on. <a href=\"/blog/ecommerce-website-or-catalogue-egypt.html\">A catalogue and a shop are different jobs</a>."],
        ["h3", "Software"],
        ["p", "If staff will log in every day — invoices, bookings, inventory — you are not buying a website. You are buying <a href=\"/blog/website-or-custom-software.html\">a system</a>."],
        ["h2", "How to brief a studio without wasting a week"],
        ["ol", [
          "One sentence: what should happen after someone visits (call, WhatsApp, order, booking).",
          "Languages the public must see on day one.",
          "Who will update prices and photos after launch.",
          "Anything that is not a website: payments, stock, staff logins.",
        ]],
        ["p", "If a company quotes before those four points are written down, they are guessing. <a href=\"/blog/how-to-choose-a-website-company-in-egypt.html\">Choosing a web company in Egypt</a> is mostly about whether they can describe the job in your words."],
        ["h2", "Facebook is not the price comparison"],
        ["p", "A page is cheaper than a site. It is also rented space with weaker search presence and no page you own. If most enquiries already come from WhatsApp, a site still has a job: to look like a company when someone checks you on Google. That is a different article: <a href=\"/blog/facebook-or-website-for-business-egypt.html\">Facebook or a website for a business in Egypt</a>."],
        ["h2", "What to do this week"],
        ["p", "Write the four-point brief. Decide whether you need a brochure, a shop, or software. Then book a scope call. We will tell you if the job is a <a href=\"/services#website\">custom website</a> — or if you should wait."],
      ],
    },
    ar: {
      title: "كم تكلفة عمل موقع إلكتروني في مصر؟",
      h1: "كم تكلفة عمل موقع إلكتروني في مصر؟",
      seoTitle: "تكلفة عمل موقع إلكتروني في مصر | Power Shift",
      seoDescription:
        "ما الذي يغيّر تكلفة الموقع في مصر فعليًا: الصفحات واللغة والمتجر والبرنامج. بلا قائمة أسعار مختلقة — كيف توجّز الاستوديو دون تخمين.",
      excerpt: "لا يوجد رقم صادق واحد. التكلفة تتبع العمل: موقع تعريفي، موقع بلغتين، متجر، أو برنامج يستخدمه الموظفون كل يوم.",
      ogAlt: "ملاحظة عن تكلفة المواقع في مصر من Power Shift",
      primaryKeyword: "تكلفة موقع إلكتروني في مصر",
      secondaryKeywords: ["سعر تصميم موقع في مصر", "تكلفة عمل موقع شركة", "أسعار تصميم المواقع"],
      ctaTitle: "تحتاج رقمًا يناسب موجزك؟",
      ctaBody: "أرسل ماذا تبيع، ومن يفترض أن يتواصل، وبأي لغة يظهر الموقع. نقول ما يستحق البناء — لا سعرًا قبل وضوح العمل.",
      body: [
        ["p", "صاحب الشركة يسأل عن السعر قبل أي شيء، وهذا مفهوم. الموقع مصروف حقيقي. الإجابة الضعيفة رقم واحد من إعلان. المفيد أن تعرف ما الذي يحرّك الرقم، فتميّز العرض الجاد من التخمين."],
        ["p", "POWER SHIFT لا تنشر قائمة أسعار. نحدد النطاق بعد موجز قصير. ما يلي يوضح كيف تتحرك التكلفة في مصر — وليس قائمة متنكّرة."],
        ["h2", "لماذا السعر الواحد غالبًا خطأ"],
        ["p", "موقع من خمس صفحات بلغة واحدة ليس نفس عمل كتالوج بلغتين، أو متجر يدفع منه العميل، أو برنامج يغني عن Excel. إذا تباعد عرضان، فالغالب أنهما يصفان منتجين مختلفين. اطلب من كل شركة كتابة الصفحات واللغات وما يحدث بعد الضغط."],
        ["p", "القوالب الرخيصة موجودة. تبدو جاهزة إلى أن تحتاج عربيًا مضبوطًا، أو مسار واتساب لا يرمي الناس في نموذج عام، أو تعديلًا بعد أشهر. إعادة البناء حينها أغلى من النسخة الأولى بموجز واضح."],
        ["h2", "ما الذي يغيّر التكلفة فعلًا"],
        ["ul", [
          "النطاق: صفحات تسويق قليلة مقابل كتالوج أو حجز أو إتمام شراء.",
          "اللغة: الإنجليزي وحده أبسط. العربي مع RTL صحيح مع الإنجليزي بناء مختلف — راجع <a href=\"/ar/blog/bilingual-arabic-english-website-egypt-gcc.html\">لماذا الموقع بلغتين لمصر والخليج مشكلة مستقلة</a>.",
          "المحتوى: أنت تكتب النصوص أم الاستوديو يخترعها. النص المخترع بطيء وغالبًا خطأ.",
          "الربط: دفع أو شحن أو مخزون أو تقويم حجوزات.",
          "من يصون الموقع: موقع لا تستطيع تعديله يصبح غاليًا أول ما يتغيّر سعر.",
        ]],
        ["h2", "أربعة أعمال يخلطها الناس باسم «موقع»"],
        ["h3", "موقع تعريفي"],
        ["p", "من أنتم، ماذا تبيعون، كيف يتواصل العميل. هذا أصغر موقع جاد. ما زال يحتاج صفحات واضحة ومسارًا لمكالمة أو واتساب. وهو ليس متجرًا."],
        ["h3", "موقع تسويق بهيكل حقيقي"],
        ["p", "صفحات خدمات أو وجهات، وربما لغتان، وربما مسار استفسار بسيط. هذا ما تحتاجه أغلب الشركات القائمة. اقرأ <a href=\"/ar/blog/what-a-business-website-needs.html\">ماذا يحتاج موقع الشركة فعلًا</a> قبل إضافة الزوائد."],
        ["h3", "متجر"],
        ["p", "منتجات ومخزون ودفع أو طلب جملة. هذا <a href=\"/services#ecommerce\">عمل تجارة إلكترونية</a>، لا بروشور عليه زر شراء. <a href=\"/ar/blog/ecommerce-website-or-catalogue-egypt.html\">الكتالوج والمتجر عملان مختلفان</a>."],
        ["h3", "برنامج"],
        ["p", "إذا كان الموظفون سيدخلون كل يوم — فواتير أو حجوزات أو مخزون — فأنت لا تشتري موقعًا. تشتري <a href=\"/ar/blog/website-or-custom-software.html\">نظامًا</a>."],
        ["h2", "كيف توجّز الاستوديو دون إضاعة أسبوع"],
        ["ol", [
          "جملة واحدة: ماذا يحدث بعد الزيارة (اتصال، واتساب، طلب، حجز).",
          "اللغات التي يجب أن يراها الجمهور من اليوم الأول.",
          "من سيحدّث الأسعار والصور بعد الإطلاق.",
          "أي شيء ليس موقعًا: دفع، مخزون، دخول موظفين.",
        ]],
        ["p", "إذا سعّرت شركة قبل كتابة هذه النقاط، فهي تخمّن. <a href=\"/ar/blog/how-to-choose-a-website-company-in-egypt.html\">اختيار شركة مواقع في مصر</a> في جوهره: هل يصفون العمل بكلامك أنت."],
        ["h2", "فيسبوك ليس مقارنة سعر"],
        ["p", "الصفحة أرخص من الموقع. وهي أيضًا مساحة مستأجرة، أضعف في البحث، بلا صفحة تملكها. إذا كانت الاستفسارات من واتساب، فالموقع ما زال له عمل: أن تبدو شركة حين يبحث عنك أحد على جوجل. هذا موضوع آخر: <a href=\"/ar/blog/facebook-or-website-for-business-egypt.html\">فيسبوك أم موقع لنشاطك في مصر</a>."],
        ["h2", "ماذا تفعل هذا الأسبوع"],
        ["p", "اكتب الموجز من أربع نقاط. قرر إن كنت تحتاج موقعًا تعريفيًا أو متجرًا أو برنامجًا. ثم احجز استشارة نطاق. نقول لك إن كان العمل <a href=\"/services#website\">موقعًا مخصصًا</a> — أو إن كان الانتظار أصح."],
      ],
    },
  },
  {
    id: "facebook-or-website",
    slug: "facebook-or-website-for-business-egypt",
    popular: true,
    category: "websites",
    tone: "mint",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-cost-egypt", "what-business-website-needs", "website-visitors-to-leads"],
    en: {
      title: "Do you need a website if you already have Facebook?",
      h1: "Do you need a website if you already have Facebook?",
      seoTitle: "Facebook or a Website for Your Business in Egypt? | Power Shift",
      seoDescription:
        "When Facebook is enough for an Egyptian business, and when a website starts to matter for trust, Google, and enquiries you own.",
      excerpt: "Most Egyptian SMEs live in Facebook and WhatsApp. A website is not automatically the next step — unless someone is already trying to check you.",
      ogAlt: "Note on Facebook versus a website from Power Shift",
      primaryKeyword: "Facebook or website for business Egypt",
      secondaryKeywords: ["do I need a website if I have Facebook", "business website vs Facebook", "website for small business Egypt"],
      body: [
        ["p", "If your orders already arrive as WhatsApp voice notes, a website can feel like an expensive brochure. Sometimes it is. The question is not “is Facebook outdated?” It is: what happens when a serious buyer looks you up and Facebook is all they find."],
        ["h2", "What Facebook is actually good at"],
        ["ul", [
          "Reach people who already scroll there.",
          "Show daily proof: stock, offers, replies.",
          "Start a chat without a form.",
        ]],
        ["p", "For a stall, a one-person trade, or a brand that only sells to people who already follow it, that can be the whole machine. Do not buy a site to feel modern."],
        ["h2", "Where Facebook stops"],
        ["p", "You do not own the URL. Pages get restricted. Search on Google often shows a messy profile instead of a clear sentence about what you sell. A procurement officer, a GCC buyer, or a hotel supplier will not send a deposit from a Facebook screenshot."],
        ["p", "Facebook is also a weak place to explain anything longer than a caption: delivery rules, wholesale terms, destinations, certifications. That copy belongs on pages you control."],
        ["h2", "The check that decides it"],
        ["p", "Search your company name plus what you sell. If the first useful result is a Facebook page with no hours, no address, and a chat button, you are asking strangers to trust a profile. If you already get “send us your website” in email, you are late."],
        ["p", "A site does not replace the page. It sits behind it: the link in the bio, the thing you send when WhatsApp is not enough. <a href=\"/blog/how-to-turn-website-visitors-into-leads.html\">The site still has to turn a visit into a message</a> — usually WhatsApp in this market."],
        ["h2", "What a first website should not try to be"],
        ["p", "It should not be a second Instagram. It needs <a href=\"/blog/what-a-business-website-needs.html\">a small set of pages that answer the buying questions</a>, load on a phone, and lead to one action. If you also need Arabic and English for the Gulf, that is not a Facebook about section — it is <a href=\"/blog/bilingual-arabic-english-website-egypt-gcc.html\">a bilingual build</a>."],
        ["h2", "A practical split"],
        ["ul", [
          "Stay on Facebook if every customer already knows you and never asks for a link.",
          "Add a site when you quote companies, export, hire, or want to appear for the service you sell — not only your brand name.",
        ]],
        ["p", "Cost still follows the job. Read <a href=\"/blog/how-much-does-a-website-cost-in-egypt.html\">what changes website cost in Egypt</a> before you compare Facebook ads to a build. If you want the public face done properly, that is <a href=\"/services#website\">custom website work</a>."],
      ],
    },
    ar: {
      title: "هل أحتاج موقعًا إذا كان عندي صفحة فيسبوك؟",
      h1: "هل أحتاج موقعًا إذا كان عندي صفحة فيسبوك؟",
      seoTitle: "فيسبوك أم موقع لنشاطك في مصر؟ | Power Shift",
      seoDescription:
        "متى يكفي فيسبوك لنشاط مصري، ومتى يبدأ الموقع في أن يهم للثقة وجوجل والاستفسارات التي تملكها.",
      excerpt: "أغلب الشركات الصغيرة في مصر تعيش على فيسبوك وواتساب. الموقع ليس الخطوة التالية تلقائيًا — إلا إذا كان أحدهم يحاول يتأكد منك.",
      ogAlt: "ملاحظة عن فيسبوك مقابل الموقع من Power Shift",
      primaryKeyword: "هل أحتاج موقع إذا عندي فيسبوك",
      secondaryKeywords: ["فيسبوك أم موقع إلكتروني", "موقع لنشاط تجاري في مصر", "الفرق بين الصفحة والموقع"],
      body: [
        ["p", "إذا كانت الطلبات تصل كرسائل صوتية على واتساب، فالموقع قد يبدو بروشورًا غاليًا. أحيانًا يكون كذلك. السؤال ليس «هل فيسبوك انتهى؟» بل: ماذا يحدث حين يبحث مشترٍ جاد عنك ولا يجد إلا الصفحة."],
        ["h2", "في ماذا ينفع فيسبوك فعلًا"],
        ["ul", [
          "الوصول لمن يتصفح هناك أصلًا.",
          "إثبات يومي: بضاعة وعروض وردود.",
          "بدء محادثة بلا نموذج.",
        ]],
        ["p", "لبسطة أو تجارة فرد أو علامة تبيع فقط لمتابعيها، قد تكون هذه الآلة كلها. لا تشترِ موقعًا كي تبدو حديثًا."],
        ["h2", "أين يتوقف فيسبوك"],
        ["p", "أنت لا تملك الرابط. الصفحات تُقيَّد. البحث على جوجل كثيرًا ما يُظهر ملفًا فوضويًا بدل جملة واضحة عما تبيع. مسؤول مشتريات أو مشترٍ من الخليج أو مورّد فندق لن يحوّل عربونًا من صورة شاشة."],
        ["p", "فيسبوك أيضًا مكان ضعيف لشرح ما هو أطول من تعليق: شروط التوصيل، الجملة، الوجهات، الشهادات. هذا النص مكانه صفحات تملكها."],
        ["h2", "الاختبار الذي يحسم الأمر"],
        ["p", "ابحث باسم شركتك مع ما تبيعه. إذا كانت أول نتيجة مفيدة صفحة بلا مواعيد ولا عنوان وفيها زر محادثة فقط، فأنت تطلب من الغريب أن يثق بملف. إذا وصلك «ابعثوا الموقع» في الإيميل، فأنت متأخر."],
        ["p", "الموقع لا يلغي الصفحة. يقف خلفها: رابط في النبذة، وما ترسله حين لا يكفي واتساب. <a href=\"/ar/blog/how-to-turn-website-visitors-into-leads.html\">والموقع ما زال عليه أن يحوّل الزيارة إلى رسالة</a> — وغالبًا واتساب في هذا السوق."],
        ["h2", "ماذا لا يجب أن يكون أول موقع"],
        ["p", "ليس إنستجرامًا ثانيًا. يحتاج <a href=\"/ar/blog/what-a-business-website-needs.html\">صفحات قليلة تجيب أسئلة الشراء</a>، تفتح على الموبايل، وتؤدي إلى فعل واحد. إذا احتجت عربيًا وإنجليزيًا للخليج، فهذه ليست نبذة فيسبوك — هذا <a href=\"/ar/blog/bilingual-arabic-english-website-egypt-gcc.html\">بناء بلغتين</a>."],
        ["h2", "تقسيم عملي"],
        ["ul", [
          "ابقَ على فيسبوك إذا كان كل عميل يعرفك ولا يطلب رابطًا.",
          "أضف موقعًا حين تسعّر لشركات، أو تصدّر، أو توظّف، أو تريد الظهور بخدمتك لا باسمك فقط.",
        ]],
        ["p", "التكلفة ما زالت تتبع العمل. اقرأ <a href=\"/ar/blog/how-much-does-a-website-cost-in-egypt.html\">ما الذي يغيّر تكلفة الموقع في مصر</a> قبل أن تقارن إعلانات فيسبوك ببناء موقع. إذا أردت الواجهة العامة مضبوطة، فهذا <a href=\"/services#website\">عمل مواقع مخصصة</a>."],
      ],
    },
  },
  {
    id: "what-business-website-needs",
    slug: "what-a-business-website-needs",
    category: "websites",
    tone: "paper",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-vs-landing-page", "website-visitors-to-leads", "website-cost-egypt"],
    en: {
      title: "What a business website actually needs",
      h1: "What a business website actually needs",
      seoTitle: "What a Business Website Actually Needs | Power Shift",
      seoDescription:
        "The pages, proof, and contact path a company site needs — without a blog, a slider, or features that do not help a buyer decide.",
      excerpt: "Most business sites fail because they are decorated, not because they are missing features. Here is the short list that has to be true.",
      ogAlt: "Note on what a business website needs from Power Shift",
      primaryKeyword: "what a business website needs",
      secondaryKeywords: ["business website pages", "company website requirements", "professional website checklist"],
      body: [
        ["p", "A business website has one job: let a stranger decide whether to contact you. Everything else is optional. Sliders, stock photos of handshakes, and a blog you will never update do not do that job."],
        ["h2", "Pages that earn their keep"],
        ["ul", [
          "Home: who you are, who you serve, what happens next — in the first screen on a phone.",
          "What you sell: services or products as separate pages if people search for them, not one paragraph dumping everything.",
          "Proof: live work, not adjectives. If you cannot show work, say what you do in concrete sentences.",
          "How to start: one path. In Egypt that is often WhatsApp plus a form, not five competing buttons.",
        ]],
        ["p", "If you only need a campaign for one offer, you may need a <a href=\"/blog/website-vs-landing-page.html\">landing page instead of a full site</a>. If you sell many things to returning customers, you need the site."],
        ["h2", "Trust without fake claims"],
        ["p", "Do not invent client logos, visitor counts, or awards. A clear address city, a real phone number, and work you can open in a browser beat a “500+ happy clients” line that nobody can check. POWER SHIFT shows live products on the <a href=\"/work\">work page</a> for the same reason."],
        ["h2", "Language and the phone"],
        ["p", "If your buyers read Arabic, the site must be Arabic — not an English site with a translate widget. RTL done badly looks like the company did not care. If you sell to the GCC as well, plan both languages from the start: <a href=\"/blog/bilingual-arabic-english-website-egypt-gcc.html\">bilingual sites are a structure decision</a>, not a toggle."],
        ["p", "More than half of visits will be on a phone. Tiny type, sticky popups, and click-to-call that is not the real number waste the visit. Speed is part of this: <a href=\"/blog/why-website-speed-matters-for-business.html\">a slow site is a closed shop on 4G</a>."],
        ["h2", "What to leave out of version one"],
        ["ul", [
          "A blog with no editor and no topics.",
          "Member logins “for later”.",
          "A shop when you still confirm every order in chat — unless you are ready for <a href=\"/blog/ecommerce-website-or-catalogue-egypt.html\">catalogue versus checkout</a>.",
          "Animations that delay the first useful sentence.",
        ]],
        ["h2", "After they arrive"],
        ["p", "The page is wasted if the next step is vague. <a href=\"/blog/how-to-turn-website-visitors-into-leads.html\">Turning visits into leads</a> is copy and one obvious action, not a CRM you will not use. When the list above is true, you are ready to talk about <a href=\"/services#website\">building the site</a> — not about themes."],
      ],
    },
    ar: {
      title: "ماذا يحتاج موقع الشركة فعلًا؟",
      h1: "ماذا يحتاج موقع الشركة فعلًا؟",
      seoTitle: "ماذا يحتاج موقع الشركة؟ | Power Shift",
      seoDescription:
        "الصفحات والإثبات ومسار التواصل التي يحتاجها موقع شركة — بلا مدونة وبلا شريط صور وبلا خصائص لا تساعد المشتري على القرار.",
      excerpt: "أغلب مواقع الشركات تفشل لأنها مزخرفة، لا لأنها ناقصة خصائص. هذه القائمة القصيرة التي يجب أن تتحقق.",
      ogAlt: "ملاحظة عن ما يحتاجه موقع الشركة من Power Shift",
      primaryKeyword: "ماذا يحتاج موقع الشركة",
      secondaryKeywords: ["محتويات موقع شركة", "صفحات الموقع التجاري", "موقع احترافي للشركات"],
      body: [
        ["p", "موقع الشركة له عمل واحد: أن يقرر الغريب إن كان سيتواصل. كل ما عدا ذلك اختياري. الشرائح وصور المصافحة ومدونة لن تُحدَّث لا تقوم بهذا العمل."],
        ["h2", "صفحات تستحق وجودها"],
        ["ul", [
          "الرئيسية: من أنتم، من تخدمون، ماذا بعد ذلك — في أول شاشة على الموبايل.",
          "ماذا تبيعون: خدمات أو منتجات في صفحات مستقلة إذا كان الناس يبحثون عنها، لا فقرة واحدة تكبّ كل شيء.",
          "إثبات: عمل يمكن فتحه، لا صفات. إن لم يكن لديك عمل معروض، اكتب ما تفعله بجمل ملموسة.",
          "كيف يبدأ العميل: مسار واحد. في مصر غالبًا واتساب مع نموذج، لا خمسة أزرار تتنافس.",
        ]],
        ["p", "إذا كنت تحتاج حملة لعرض واحد، فقد تحتاج <a href=\"/ar/blog/website-vs-landing-page.html\">صفحة هبوط لا موقعًا كاملًا</a>. إذا كنت تبيع أشياء كثيرة لعملاء يعودون، فأنت تحتاج الموقع."],
        ["h2", "ثقة بلا ادّعاءات"],
        ["p", "لا تخترع شعارات عملاء ولا أرقام زوار ولا جوائز. مدينة واضحة ورقم حقيقي وعمل يُفتح في المتصفح أقوى من سطر «أكثر من 500 عميل سعيد» لا يمكن التحقق منه. POWER SHIFT تعرض منتجات حية في <a href=\"/work\">صفحة الأعمال</a> للسبب نفسه."],
        ["h2", "اللغة والموبايل"],
        ["p", "إذا كان المشتري يقرأ بالعربي، فالموقع عربي — لا موقعًا إنجليزيًا عليه زر ترجمة. RTL المنفَّذ بشكل سيئ يبدو كأن الشركة لا تكترث. إذا كنت تبيع للخليج أيضًا، خطط للغتين من البداية: <a href=\"/ar/blog/bilingual-arabic-english-website-egypt-gcc.html\">الموقع بلغتين قرار هيكل</a> لا مفتاح."],
        ["p", "أكثر الزيارات من الموبايل. الخط الصغير والنوافذ اللاصقة وزر اتصال برقم غير حقيقي يضيّعان الزيارة. السرعة جزء من هذا: <a href=\"/ar/blog/why-website-speed-matters-for-business.html\">الموقع البطيء محل مغلق على شبكة الجوال</a>."],
        ["h2", "ماذا تترك من النسخة الأولى"],
        ["ul", [
          "مدونة بلا محرّر وبلا موضوعات.",
          "حسابات أعضاء «للاحقًا».",
          "متجر وأنت ما زلت تؤكد كل طلب في الشات — إلا إذا كنت جاهزًا لـ<a href=\"/ar/blog/ecommerce-website-or-catalogue-egypt.html\">الكتالوج مقابل إتمام الشراء</a>.",
          "حركات تؤخر أول جملة مفيدة.",
        ]],
        ["h2", "بعد وصول الزائر"],
        ["p", "الصفحة تضيع إذا كانت الخطوة التالية غامضة. <a href=\"/ar/blog/how-to-turn-website-visitors-into-leads.html\">تحويل الزيارة إلى استفسار</a> نص وفعل واحد واضح، لا نظام متابعة لن تستخدمه. عندما تصدق القائمة أعلاه، تكون جاهزًا للحديث عن <a href=\"/services#website\">بناء الموقع</a> — لا عن القوالب."],
      ],
    },
  },
  {
    id: "website-vs-landing-page",
    slug: "website-vs-landing-page",
    category: "websites",
    tone: "mint",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["what-business-website-needs", "website-visitors-to-leads", "when-to-redesign"],
    en: {
      title: "Website vs landing page: which does your business need?",
      h1: "Website vs landing page: which does your business need?",
      seoTitle: "Website vs Landing Page: Which Do You Need? | Power Shift",
      seoDescription:
        "A landing page is for one offer and one action. A website is for a company people return to. How to choose without building both badly.",
      excerpt: "A landing page sells one thing. A website holds the company. Mixing them is how you get a slow home page that converts nothing.",
      ogAlt: "Note on websites versus landing pages from Power Shift",
      primaryKeyword: "website vs landing page",
      secondaryKeywords: ["landing page vs website", "do I need a landing page", "business landing page"],
      body: [
        ["p", "People use the words as if they were the same size. They are not. A landing page has one job on one URL. A website is a small set of URLs that still make sense next year."],
        ["h2", "What a landing page is for"],
        ["p", "One offer, one audience, one action: book a call, send WhatsApp, register. You send paid traffic or a campaign link there. Extra navigation is usually a leak. If you are running a single course, a seasonal product, or a waitlist, start here."],
        ["h2", "What a website is for"],
        ["p", "People who type your name, compare you to someone else, or return in six months. They need services, work, and a way to contact you that is not tied to last month’s promo. That is <a href=\"/blog/what-a-business-website-needs.html\">the company site checklist</a>."],
        ["h2", "When companies pick the wrong one"],
        ["p", "A factory with four product lines stuffed onto one long scroll is not a landing page — it is a site that refused to have URLs. A company that only ever needs leads from one ads campaign does not need a 12-page site first."],
        ["p", "If Google is supposed to find several services, those services need pages. A single landing URL cannot rank for five unrelated searches without becoming mush."],
        ["h2", "Can you have both?"],
        ["p", "Yes. The site is the home. The landing page is a campaign door that still feels like the same company. Do not send ad traffic to a cluttered home page and hope. Do not replace the whole site with a page that cannot explain who you are when the campaign ends."],
        ["h2", "How to decide this week"],
        ["ul", [
          "One offer, paid traffic, short life: landing page.",
          "Name searches, several services, hiring, wholesale: website.",
          "Both: site first if you have no URL you own; landing page first if a campaign starts before the company story is ready — then do not pretend the landing page is the company.",
        ]],
        ["p", "If the build is a public site, see <a href=\"/services#website\">custom websites</a>. If the problem is that visits do not message you, read <a href=\"/blog/how-to-turn-website-visitors-into-leads.html\">visitors to leads</a> before you add more pages."],
      ],
    },
    ar: {
      title: "موقع أم صفحة هبوط: ماذا يحتاج نشاطك؟",
      h1: "موقع أم صفحة هبوط: ماذا يحتاج نشاطك؟",
      seoTitle: "موقع أم صفحة هبوط لنشاطك؟ | Power Shift",
      seoDescription:
        "صفحة الهبوط لعرض واحد وفعل واحد. الموقع للشركة التي يعود الناس إليها. كيف تختار دون أن تبني الاثنين بشكل سيئ.",
      excerpt: "صفحة الهبوط تبيع شيئًا واحدًا. الموقع يحمل الشركة. خلطهما يعطيك صفحة رئيسية بطيئة لا تحوّل أحدًا.",
      ogAlt: "ملاحظة عن الموقع مقابل صفحة الهبوط من Power Shift",
      primaryKeyword: "موقع أم صفحة هبوط",
      secondaryKeywords: ["الفرق بين الموقع وصفحة الهبوط", "هل أحتاج لاندنج بيدج", "صفحة هبوط للشركات"],
      body: [
        ["p", "الناس تستخدم الكلمتين كأنهما نفس الحجم. ليستا كذلك. صفحة الهبوط عمل واحد على رابط واحد. الموقع مجموعة روابط صغيرة ما زالت منطقية السنة القادمة."],
        ["h2", "لماذا تُستخدم صفحة الهبوط"],
        ["p", "عرض واحد، جمهور واحد، فعل واحد: حجز مكالمة، واتساب، تسجيل. ترسل إليها زيارات مدفوعة أو رابط حملة. التنقل الزائد غالبًا تسرّب. إذا كان عندك دورة واحدة أو منتج موسمي أو قائمة انتظار، ابدأ من هنا."],
        ["h2", "لماذا يُستخدم الموقع"],
        ["p", "من يكتب اسمك، أو يقارنك بغيرك، أو يعود بعد أشهر. يحتاج خدماتًا وأعمالًا وطريقة تواصل غير مربوطة بعرض الشهر الماضي. هذا <a href=\"/ar/blog/what-a-business-website-needs.html\">قائمة موقع الشركة</a>."],
        ["h2", "متى تختار الشركات الخيار الخطأ"],
        ["p", "مصنع بأربعة خطوط إنتاج محشورة في تمرير طويل ليس صفحة هبوط — إنه موقع رفض أن يكون له روابط. وشركة لا تحتاج إلا عملاء من حملة إعلانات واحدة لا تحتاج موقعًا من اثنتي عشرة صفحة أولًا."],
        ["p", "إذا كان على جوجل أن يجد عدة خدمات، فهذه الخدمات تحتاج صفحات. رابط هبوط واحد لا يحتل خمس عمليات بحث غير مترابطة دون أن يصبح هلامًا."],
        ["h2", "هل يمكن الاثنان؟"],
        ["p", "نعم. الموقع هو البيت. صفحة الهبوط باب الحملة ويظل بنفس شعور الشركة. لا ترسل زيارات الإعلان إلى رئيسية مزدحمة وتتمنى. ولا تستبدل الموقع كله بصفحة لا تشرح من أنتم حين تنتهي الحملة."],
        ["h2", "كيف تقرر هذا الأسبوع"],
        ["ul", [
          "عرض واحد، زيارات مدفوعة، عمر قصير: صفحة هبوط.",
          "بحث بالاسم، خدمات عدة، توظيف، جملة: موقع.",
          "الاثنان: الموقع أولًا إن لم يكن لديك رابط تملكه؛ صفحة الهبوط أولًا إن بدأت الحملة قبل قصة الشركة — ثم لا تعامل صفحة الهبوط وكأنها الشركة.",
        ]],
        ["p", "إذا كان البناء موقعًا عامًا، راجع <a href=\"/services#website\">المواقع المخصصة</a>. إذا كانت المشكلة أن الزيارات لا تراسل، اقرأ <a href=\"/ar/blog/how-to-turn-website-visitors-into-leads.html\">من الزائر إلى الاستفسار</a> قبل أن تضيف صفحات."],
      ],
    },
  },
  {
    id: "why-website-not-on-google",
    slug: "why-isnt-my-website-showing-on-google",
    popular: true,
    category: "seo",
    tone: "navy",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-speed-business", "bilingual-website-egypt-gcc", "what-business-website-needs"],
    en: {
      title: "Why isn’t my website showing on Google?",
      h1: "Why isn’t my website showing on Google?",
      seoTitle: "Why Isn’t My Website Showing on Google? | Power Shift",
      seoDescription:
        "The usual reasons a new site does not appear on Google: the wrong URL, blocked crawling, no Search Console, thin pages, or expecting instant rankings.",
      excerpt: "If you cannot find your own URL, that is an indexing problem. If you find it only when you search the exact address, that is a ranking problem. They are not the same.",
      ogAlt: "Note on Google indexing from Power Shift",
      primaryKeyword: "website not showing on Google",
      secondaryKeywords: ["why is my website not on Google", "Google not indexing my site", "new website not appearing in search"],
      body: [
        ["p", "Two different failures get called “we are not on Google.” One: Google has not stored your pages. Two: Google stored them, but they lose to other results. Fix the first before you buy ads or a “SEO package” with no diagnosis."],
        ["h2", "Check the simple things first"],
        ["ol", [
          "Search <code>site:yourdomain.com</code>. Zero results usually means not indexed, or the domain Google sees is not the one you type.",
          "Open the URL you share. If it redirects to another host, Google may be indexing the old one. POWER SHIFT had this class of problem when a preview host stayed live beside the real domain — the public site and the search listing must be the same URL.",
          "Confirm https and the www versus non-www version. Two live copies split attention.",
        ]],
        ["h2", "Technical blocks"],
        ["p", "A robots.txt that disallows the whole site, a noindex tag left from staging, or a language redirect that sends crawlers to the wrong page will hide you. JavaScript-only pages with no HTML text are harder to trust. The blog and services on this site are real HTML for that reason."],
        ["p", "Search Console is not optional if you care. It shows whether Google can fetch the homepage, and whether you submitted a sitemap that lists the URLs you actually want. Asking for a ranking report before the homepage is indexed wastes everyone’s time."],
        ["h2", "Thin or duplicate pages"],
        ["p", "A new site with one paragraph copied from a template gives Google nothing to rank. Two language versions that claim the same English canonical are worse: you taught Google to ignore the Arabic URL. Hreflang has to point at real alternate URLs, not at a JS toggle."],
        ["p", "Speed is not the first reason a brand-new URL is missing — but once you are in the index, a painful mobile load still loses the click. <a href=\"/blog/why-website-speed-matters-for-business.html\">Speed is a business issue after you exist in search</a>."],
        ["h2", "Ranking is slower than indexing"],
        ["p", "Being indexed for your brand name can happen relatively quickly. Ranking for “website company Cairo” against established results does not. That takes pages that match the query, links from your own site, and time. There is no honest overnight switch."],
        ["h2", "What to do this week"],
        ["ul", [
          "Pick one canonical host and redirect the rest.",
          "Open Search Console, inspect the homepage, submit the sitemap.",
          "Write one useful page per service you actually sell — see <a href=\"/blog/what-a-business-website-needs.html\">what the site needs</a>.",
        ]],
        ["p", "If the site was built as a visual mock and never set up for search, the fix is often the build — <a href=\"/services#website\">website work</a> — not a plugin. We do not sell ranking guarantees. We do build pages search engines can read."],
      ],
    },
    ar: {
      title: "لماذا لا يظهر موقعي على جوجل؟",
      h1: "لماذا لا يظهر موقعي على جوجل؟",
      seoTitle: "لماذا لا يظهر موقعي على جوجل؟ | Power Shift",
      seoDescription:
        "الأسباب المعتادة لعدم ظهور موقع جديد على جوجل: الرابط الخطأ، حجب الزحف، غياب Search Console، صفحات ضعيفة، أو انتظار ترتيب فوري.",
      excerpt: "إن لم تجد رابطك أصلًا، فهذه مشكلة فهرسة. إن وجدته فقط حين تكتب العنوان كاملًا، فهذه مشكلة ترتيب. ليستا واحدة.",
      ogAlt: "ملاحظة عن ظهور المواقع على جوجل من Power Shift",
      primaryKeyword: "موقعي لا يظهر على جوجل",
      secondaryKeywords: ["الموقع لا يظهر في البحث", "جوجل لا يفهرس موقعي", "موقع جديد لا يظهر على جوجل"],
      body: [
        ["p", "هناك فشلان يُسمَّيان «نحن لسنا على جوجل». الأول: جوجل لم يخزّن صفحاتك. الثاني: خزّنها لكنها تخسر أمام نتائج أخرى. أصلح الأول قبل شراء إعلانات أو «باقة سيو» بلا تشخيص."],
        ["h2", "افحص البسيط أولًا"],
        ["ol", [
          "ابحث <code>site:yourdomain.com</code>. صفر نتائج يعني غالبًا أنه غير مفهرس، أو أن النطاق الذي يراه جوجل ليس الذي تكتبه.",
          "افتح الرابط الذي تنشروه. إذا حوّل إلى استضافة أخرى، فقد يفهرس جوجل القديمة. واجهت POWER SHIFT هذا النوع حين بقي عنوان معاينة حيًا بجانب النطاق الحقيقي — الموقع العلني ونتيجة البحث يجب أن يكونا نفس الرابط.",
          "تأكد من https ومن نسخة www مقابل بدونها. نسختان حيتان تشقّان الانتباه.",
        ]],
        ["h2", "عوائق تقنية"],
        ["p", "ملف robots يحظر الموقع كله، أو وسم noindex باقٍ من التجربة، أو تحويل لغة يرسل الزاحف للصفحة الخطأ — كلها تخفيك. الصفحات التي لا نص HTML فيها أصعب في الثقة. المدونة والخدمات هنا HTML حقيقي لهذا السبب."],
        ["p", "Search Console ليس اختياريًا إن كنت تهتم. يُظهر إن كان جوجل يجلب الرئيسية، وإن كنت أرسلت خريطة روابط تريدها فعلًا. طلب تقرير ترتيب قبل فهرسة الرئيسية إضاعة وقت."],
        ["h2", "صفحات ضعيفة أو مكررة"],
        ["p", "موقع جديد بفقرة منسوخة من قالب لا يعطي جوجل ما يرتبه. نسختان لغويتان تدّعيان نفس الرابط الإنجليزي أسوأ: علّمت جوجل أن يتجاهل الرابط العربي. hreflang يجب أن يشير إلى روابط بديلة حقيقية، لا إلى تبديل بجافاسكربت."],
        ["p", "السرعة ليست أول سبب لاختفاء رابط جديد — لكن بعد دخول الفهرس، تحميل مؤلم على الموبايل يخسر النقرة. <a href=\"/ar/blog/why-website-speed-matters-for-business.html\">السرعة مسألة عمل بعد أن توجد في البحث</a>."],
        ["h2", "الترتيب أبطأ من الفهرسة"],
        ["p", "الفهرسة باسم علامتك قد تحدث بسرعة نسبية. الترتيب على «شركة مواقع القاهرة» أمام نتائج قائمة لا يحدث. هذا يحتاج صفحات تطابق البحث، وربطًا داخليًا، ووقتًا. لا يوجد مفتاح صادق بين ليلة وضحاها."],
        ["h2", "ماذا تفعل هذا الأسبوع"],
        ["ul", [
          "اختر استضافة قانونية واحدة وحوّل الباقي إليها.",
          "افتح Search Console، افحص الرئيسية، أرسل الخريطة.",
          "اكتب صفحة مفيدة لكل خدمة تبيعها فعلًا — راجع <a href=\"/ar/blog/what-a-business-website-needs.html\">ماذا يحتاج الموقع</a>.",
        ]],
        ["p", "إذا بُني الموقع كمجسّم بصري ولم يُعدّ للبحث، فالإصلاح غالبًا في البناء — <a href=\"/services#website\">عمل المواقع</a> — لا في إضافة. لا نبيع ضمانات ترتيب. نبني صفحات يستطيع محرك البحث قراءتها."],
      ],
    },
  },
  {
    id: "website-speed-business",
    slug: "why-website-speed-matters-for-business",
    category: "seo",
    tone: "paper",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["why-website-not-on-google", "when-to-redesign", "what-business-website-needs"],
    en: {
      title: "Why website speed matters for your business",
      h1: "Why website speed matters for your business",
      seoTitle: "Why Website Speed Matters for Business | Power Shift",
      seoDescription:
        "Slow sites lose mobile visitors before the pitch. What speed actually means for an Egyptian business site — and what to fix first.",
      excerpt: "On a phone in traffic, a heavy homepage is a closed door. Speed is not a developer hobby. It is whether the first sentence ever appears.",
      ogAlt: "Note on website speed from Power Shift",
      primaryKeyword: "why website speed matters",
      secondaryKeywords: ["slow website business", "website performance Egypt", "Core Web Vitals business"],
      body: [
        ["p", "You do not need a lab number to know a slow site. You feel it: the logo sits there, then a video autoplays, then the phone gets warm. The visitor already opened WhatsApp to message a competitor."],
        ["h2", "What “slow” usually is"],
        ["ul", [
          "Uncompressed hero images and slider libraries.",
          "Scripts for chat, pixels, and animations loading before the text.",
          "A page built as a design file, then exported, instead of HTML a phone can paint quickly.",
        ]],
        ["p", "Core Web Vitals are Google’s names for this experience. You do not need to memorise the acronyms. You need the first useful sentence on screen without a fight. That also helps search once the page is indexed — see <a href=\"/blog/why-isnt-my-website-showing-on-google.html\">indexing versus ranking</a>."],
        ["h2", "Egypt and the GCC are mobile-first"],
        ["p", "Owners review sites on a laptop. Buyers often do not. A site that is “fine in the office” can be unusable on 4G. Bilingual pages that load two full copies of everything make it worse if the unused language is not deferred."],
        ["h2", "What not to do"],
        ["p", "Do not install five speed plugins on a bloated theme. Do not hide the problem with a loading animation. Do not claim a score you screenshotted once in ideal conditions."],
        ["h2", "What to fix first"],
        ["ol", [
          "One hero image, sized for phones, not a 4MB desktop photograph.",
          "Text in HTML, not trapped inside a canvas or a delayed slider.",
          "Chat widgets after the page is readable, if you need them at all. WhatsApp links are lighter.",
        ]],
        ["p", "If the site is old, slow, and you are already rewriting the offer, that is often a <a href=\"/blog/when-to-redesign-your-business-website.html\">redesign moment</a>, not another overlay. For a new build, speed is part of <a href=\"/services#website\">the website job</a>, not a phase you buy later."],
      ],
    },
    ar: {
      title: "لماذا تهم سرعة الموقع لنشاطك؟",
      h1: "لماذا تهم سرعة الموقع لنشاطك؟",
      seoTitle: "لماذا تهم سرعة الموقع للعمل؟ | Power Shift",
      seoDescription:
        "المواقع البطيئة تخسر زائر الموبايل قبل العرض. ماذا تعني السرعة لموقع شركة في مصر — وما الذي تصلحه أولًا.",
      excerpt: "على موبايل في الطريق، الصفحة الثقيلة باب مغلق. السرعة ليست هواية مطوّر. هي: هل تظهر الجملة الأولى أصلًا.",
      ogAlt: "ملاحظة عن سرعة المواقع من Power Shift",
      primaryKeyword: "أهمية سرعة الموقع",
      secondaryKeywords: ["موقع بطيء للشركات", "أداء الموقع في مصر", "Core Web Vitals للشركات"],
      body: [
        ["p", "لا تحتاج رقم مختبر لتعرف أن الموقع بطيء. تشعر به: الشعار واقف، ثم فيديو يعمل وحده، ثم يسخن الهاتف. الزائر فتح واتساب لمنافس."],
        ["h2", "ما هو «البطء» عادة"],
        ["ul", [
          "صور غلاف غير مضغوطة ومكتبات شرائح.",
          "سكربتات للدردشة والبكسل والحركة قبل النص.",
          "صفحة مبنية كملف تصميم ثم تُصدَّر، لا HTML يرسمه الموبايل بسرعة.",
        ]],
        ["p", "Core Web Vitals أسماء جوجل لهذه التجربة. لا تحتاج حفظ الاختصارات. تحتاج أول جملة مفيدة على الشاشة بلا عراك. هذا يساعد البحث بعد الفهرسة — راجع <a href=\"/ar/blog/why-isnt-my-website-showing-on-google.html\">الفهرسة مقابل الترتيب</a>."],
        ["h2", "مصر والخليج موبايل أولًا"],
        ["p", "صاحب الشركة يراجع الموقع على لابتوب. المشتري غالبًا لا يفعل. موقع «مقبول في المكتب» قد يكون غير صالح على 4G. الصفحات بلغتين التي تحمّل نسختين كاملتين تزيد الأمر إن لم تُؤجَّل اللغة غير المستخدمة."],
        ["h2", "ما لا تفعله"],
        ["p", "لا تثبّت خمس إضافات سرعة على قالب متخم. لا تخفِ المشكلة بشاشة تحميل. لا تدّعِ درجة التقطتها مرة في ظرف مثالي."],
        ["h2", "ما الذي تصلحه أولًا"],
        ["ol", [
          "صورة غلاف واحدة بحجم الموبايل، لا صورة سطح مكتب بعدة ميغابايت.",
          "النص في HTML، لا محبوسًا في لوحة أو شريحة متأخرة.",
          "أدوات الدردشة بعد أن تُقرأ الصفحة، إن لزمت. روابط واتساب أخف.",
        ]],
        ["p", "إذا كان الموقع قديمًا وبطيئًا وأنت تعيد كتابة العرض، فهذه غالبًا <a href=\"/ar/blog/when-to-redesign-your-business-website.html\">لحظة إعادة تصميم</a> لا طبقة فوق القديمة. في بناء جديد، السرعة جزء من <a href=\"/services#website\">عمل الموقع</a>، لا مرحلة تشتريها لاحقًا."],
      ],
    },
  },
  {
    id: "website-visitors-to-leads",
    slug: "how-to-turn-website-visitors-into-leads",
    category: "conversion",
    tone: "mint",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["what-business-website-needs", "facebook-or-website", "website-vs-landing-page"],
    en: {
      title: "How to turn website visitors into leads",
      h1: "How to turn website visitors into leads",
      seoTitle: "How to Turn Website Visitors into Leads | Power Shift",
      seoDescription:
        "Visits are not enquiries. For Egyptian businesses, the usual path is one clear action — often WhatsApp — not a maze of forms and popups.",
      excerpt: "If people browse and leave, the site did not fail at design first. It failed at saying what to do next in a way a busy owner will actually do.",
      ogAlt: "Note on turning website visits into leads from Power Shift",
      primaryKeyword: "turn website visitors into leads",
      secondaryKeywords: ["website lead generation", "WhatsApp button on website", "convert website traffic"],
      body: [
        ["p", "Traffic without a message is a brochure. In this market the message is usually WhatsApp, sometimes a short form, rarely a long application. The site’s job is to make that step feel obvious, not clever."],
        ["h2", "One action per page"],
        ["p", "Home can offer a call or WhatsApp. A service page should not also push a newsletter, a PDF, and a chatbot. Competing CTAs are how nothing gets tapped. A campaign URL can be stricter: that is a <a href=\"/blog/website-vs-landing-page.html\">landing page</a>."],
        ["h2", "Put the next step where the thumb is"],
        ["p", "A floating bar is fine if it does not cover the sentence people came to read. The number must be the real business number. A form that asks for a novel before WhatsApp will sit empty. POWER SHIFT’s own site takes briefs to WhatsApp after a short wizard — because that is where the conversation already lives."],
        ["h2", "Write the reason to contact"],
        ["p", "“Submit” is not a reason. “Send the sizes you need” or “Ask about wholesale packing” is. Service pages should end with the same honesty as <a href=\"/blog/what-a-business-website-needs.html\">the rest of the site</a>: who it is for, and what you need from them to reply."],
        ["h2", "Do not fake proof"],
        ["p", "Popup testimonials you cannot stand behind train people to ignore you. Show work, a city, a way to reach a human. If Facebook already converts, the site should repeat that path, not invent a funnel from a US blog post. See <a href=\"/blog/facebook-or-website-for-business-egypt.html\">how the site sits behind the page</a>."],
        ["h2", "Measure something small"],
        ["p", "Count messages that mention the site, or form starts, if you have them. Do not install a dashboard you will not open. If nobody contacts you and you have traffic, read the page on a phone and try to enquire in under fifteen seconds. If you cannot, neither can they."],
        ["p", "When the path is clear and the pages still cannot hold the company, the build is the constraint — <a href=\"/services#website\">a site meant to take enquiries</a>, not a theme with a plugin button."],
      ],
    },
    ar: {
      title: "كيف تحوّل زوار الموقع إلى استفسارات؟",
      h1: "كيف تحوّل زوار الموقع إلى استفسارات؟",
      seoTitle: "تحويل زوار الموقع إلى عملاء محتملين | Power Shift",
      seoDescription:
        "الزيارات ليست استفسارات. في السوق المصري المسار المعتاد فعل واحد واضح — غالبًا واتساب — لا متاهة نماذج ونوافذ.",
      excerpt: "إذا تصفّح الناس وخرجوا، فالموقع لم يفشل أولًا في الشكل. فشل في قول ماذا يفعلون بعد ذلك بطريقة ينفّذها صاحب مشغول.",
      ogAlt: "ملاحظة عن تحويل زيارات الموقع من Power Shift",
      primaryKeyword: "تحويل زوار الموقع إلى عملاء",
      secondaryKeywords: ["توليد عملاء من الموقع", "زر واتساب في الموقع", "تحويل زيارات الموقع"],
      body: [
        ["p", "زيارات بلا رسالة بروشور. في هذا السوق الرسالة غالبًا واتساب، وأحيانًا نموذج قصير، ونادرًا طلب طويل. عمل الموقع أن يجعل الخطوة بديهية لا ذكية."],
        ["h2", "فعل واحد في الصفحة"],
        ["p", "الرئيسية قد تعرض اتصالًا أو واتساب. صفحة الخدمة لا تدفع في الوقت نفسه نشرة وملفًا ومحادثة آلية. الأزرار المتنافسة سبب ألا يُضغط شيء. رابط الحملة يمكن أن يكون أضيق: هذه <a href=\"/ar/blog/website-vs-landing-page.html\">صفحة هبوط</a>."],
        ["h2", "ضع الخطوة التالية حيث الإبهام"],
        ["p", "شريط ثابت مقبول إن لم يغطِّ الجملة التي جاء من أجلها الزائر. الرقم يجب أن يكون رقم النشاط الحقيقي. نموذج يطلب رواية قبل واتساب سيبقى فارغًا. موقع POWER SHIFT نفسه ينقل الموجز إلى واتساب بعد خطوات قصيرة — لأن الحوار هناك أصلًا."],
        ["h2", "اكتب سبب التواصل"],
        ["p", "«إرسال» ليس سببًا. «أرسل المقاسات» أو «اسأل عن تعبئة الجملة» سبب. صفحات الخدمة تنتهي بنفس صراحة <a href=\"/ar/blog/what-a-business-website-needs.html\">باقي الموقع</a>: لمن هي، وما تحتاجه للرد."],
        ["h2", "لا تختلق إثباتًا"],
        ["p", "شهادات منبثقة لا تقدر أن تقف خلفها تعلّم الناس أن يتجاهلوك. اعرض عملًا ومدينة وطريقًا لإنسان. إذا كان فيسبوك يحوّل أصلًا، فالموقع يكرر ذلك المسار لا يخترع قمعًا من مقال أمريكي. راجع <a href=\"/ar/blog/facebook-or-website-for-business-egypt.html\">كيف يقف الموقع خلف الصفحة</a>."],
        ["h2", "قِس شيئًا صغيرًا"],
        ["p", "عدّ الرسائل التي تذكر الموقع، أو بدء النموذج إن وُجد. لا تثبّت لوحة لن تفتحها. إذا لم يتواصل أحد ولديك زيارات، اقرأ الصفحة على موبايل وحاول الاستفسار في أقل من خمس عشرة ثانية. إن لم تستطع، فهم لن يستطيعوا."],
        ["p", "عندما يكون المسار واضحًا والصفحات ما زالت لا تحمل الشركة، فالقيد في البناء — <a href=\"/services#website\">موقع مصمم لاستقبال الاستفسار</a>، لا قالب عليه زر إضافة."],
      ],
    },
  },
  {
    id: "when-to-redesign",
    slug: "when-to-redesign-your-business-website",
    category: "websites",
    tone: "navy",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-speed-business", "what-business-website-needs", "website-cost-egypt"],
    en: {
      title: "When should you redesign your business website?",
      h1: "When should you redesign your business website?",
      seoTitle: "When to Redesign Your Business Website | Power Shift",
      seoDescription:
        "Redesign when the site cannot tell the truth about the business, cannot be edited, or fails on phones — not because a template looks dated.",
      excerpt: "A redesign is expensive. Do it when the current site blocks enquiries or misrepresents the work — not because a competitor launched a darker theme.",
      ogAlt: "Note on website redesign from Power Shift",
      primaryKeyword: "when to redesign a website",
      secondaryKeywords: ["business website redesign", "website refresh vs rebuild", "outdated website"],
      body: [
        ["p", "Owners feel embarrassed by an old site before they feel the operational pain. Embarrassment is not a brief. The brief is: what can this URL not do that the business now needs."],
        ["h2", "Signals that justify a rebuild"],
        ["ul", [
          "Nobody on the team can change a price or a photo without calling the original developer — who is gone.",
          "The site is English-only and the buyers are not.",
          "It is slow or broken on phones. See <a href=\"/blog/why-website-speed-matters-for-business.html\">why that costs you the visit</a>.",
          "You now sell a shop or a system and the site is still a 2018 brochure.",
          "Google shows an old host, or the pages are not in the index. Start with <a href=\"/blog/why-isnt-my-website-showing-on-google.html\">indexing</a> before you restyle.",
        ]],
        ["h2", "Signals that do not"],
        ["p", "A trend in rounded corners. A founder who saw a Dribbble shot. A request to “make it more premium” with no change in offer, proof, or contact path. You can waste a full project budget and keep the same empty inbox."],
        ["h2", "Refresh versus rebuild"],
        ["p", "If the URLs, languages, and conversion path are right, you may only need clearer writing and lighter images. If the structure is a single scrolling poster, start from <a href=\"/blog/what-a-business-website-needs.html\">the pages a company site needs</a>. Cost still follows that scope: <a href=\"/blog/how-much-does-a-website-cost-in-egypt.html\">what changes the price</a>."],
        ["h2", "Do not throw away what ranks"],
        ["p", "If a service URL already brings the right enquiries, keep the path. Redesign the template around it. A full domain change for taste is how you reset search to zero."],
        ["p", "When the site must match a live product again, that is <a href=\"/services#website\">website work</a> — sometimes with <a href=\"/work\">examples of shipped products</a> as the proof, not a moodboard."],
      ],
    },
    ar: {
      title: "متى تعيد تصميم موقع شركتك؟",
      h1: "متى تعيد تصميم موقع شركتك؟",
      seoTitle: "متى تعيد تصميم موقع الشركة؟ | Power Shift",
      seoDescription:
        "أعد التصميم حين يعجز الموقع عن قول حقيقة النشاط، أو عن التعديل، أو عن العمل على الموبايل — لا لأن القالب يبدو قديمًا.",
      excerpt: "إعادة التصميم مكلفة. افعلها عندما يعيق الموقع الاستفسارات أو يسيء تمثيل العمل — لا لأن منافسًا أطلق ثيمًا أغمق.",
      ogAlt: "ملاحظة عن إعادة تصميم المواقع من Power Shift",
      primaryKeyword: "متى أعيد تصميم الموقع",
      secondaryKeywords: ["تحديث موقع الشركة", "إعادة بناء الموقع", "موقع قديم للشركات"],
      body: [
        ["p", "صاحب الشركة يخجل من الموقع القديم قبل أن يشعر بألم التشغيل. الخجل ليس موجزًا. الموجز: ماذا لا يستطيع هذا الرابط أن يفعله مما يحتاجه النشاط الآن."],
        ["h2", "إشارات تبرر إعادة البناء"],
        ["ul", [
          "لا أحد في الفريق يغيّر سعرًا أو صورة دون الاتصال بالمطوّر الأصلي — وهو غير موجود.",
          "الموقع إنجليزي فقط والمشترون ليسوا كذلك.",
          "بطيء أو مكسور على الموبايل. راجع <a href=\"/ar/blog/why-website-speed-matters-for-business.html\">لماذا يكلّفك ذلك الزيارة</a>.",
          "أنت تبيع متجرًا أو نظامًا والموقع ما زال بروشور 2018.",
          "جوجل يُظهر استضافة قديمة، أو الصفحات ليست في الفهرس. ابدأ من <a href=\"/ar/blog/why-isnt-my-website-showing-on-google.html\">الفهرسة</a> قبل تغيير الشكل.",
        ]],
        ["h2", "إشارات لا تبرر"],
        ["p", "موضة الزوايا المستديرة. مؤسس رأى لقطة على Dribbble. طلب «اجعله أفخم» بلا تغيير في العرض أو الإثبات أو مسار التواصل. يمكن إهدار ميزانية مشروع كاملة ويبقى الصندوق الوارد فارغًا."],
        ["h2", "تحديث مقابل إعادة بناء"],
        ["p", "إذا كانت الروابط واللغات ومسار التحويل صحيحة، فقد تحتاج نصًا أوضح وصورًا أخف فقط. إذا كان الهيكل ملصقًا واحدًا طويلاً، ابدأ من <a href=\"/ar/blog/what-a-business-website-needs.html\">صفحات موقع الشركة</a>. التكلفة ما زالت تتبع هذا النطاق: <a href=\"/ar/blog/how-much-does-a-website-cost-in-egypt.html\">ما الذي يغيّر السعر</a>."],
        ["h2", "لا ترمِ ما يظهر في البحث"],
        ["p", "إذا كان رابط خدمة يجلب الاستفسار الصحيح، أبقِ المسار. صمّم القالب حوله. تغيير النطاق بالكامل من أجل الذوق يعيد البحث إلى صفر."],
        ["p", "عندما يجب أن يطابق الموقع منتجًا حيًا من جديد، فهذا <a href=\"/services#website\">عمل مواقع</a> — أحيانًا مع <a href=\"/work\">أمثلة منتجات مسلَّمة</a> كإثبات، لا لوحة أمزجة."],
      ],
    },
  },
  {
    id: "ecommerce-or-catalogue",
    slug: "ecommerce-website-or-catalogue-egypt",
    category: "ecommerce",
    tone: "mint",
    wizard: "ecommerce",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-vs-landing-page", "website-or-custom-software", "website-cost-egypt"],
    en: {
      title: "Do you need an e-commerce site or a catalogue?",
      h1: "Do you need an e-commerce site or a catalogue?",
      seoTitle: "E-commerce Website or Catalogue in Egypt? | Power Shift",
      seoDescription:
        "A catalogue shows products. A shop takes payment or structured orders. How Egyptian brands should choose before paying for checkout they will not use.",
      excerpt: "If every order is still confirmed in WhatsApp, a full checkout can wait. If you need stock, prices, and a cart that matches reality, you need a shop.",
      ogAlt: "Note on e-commerce versus catalogue from Power Shift",
      primaryKeyword: "e-commerce website vs catalogue",
      secondaryKeywords: ["online store vs catalogue Egypt", "do I need Shopify", "wholesale enquiry website"],
      body: [
        ["p", "Beauty, food, and trade companies in Egypt often ask for “a shop” when they mean “put the products online.” Those are different builds. Checkout, shipping rules, and stock are the expensive part. A catalogue with a wholesale or WhatsApp path can be the honest first version."],
        ["h2", "A catalogue is enough when"],
        ["ul", [
          "Prices change in chat anyway.",
          "You sell B2B and the next step is a quote, not a card payment.",
          "You have twenty SKUs and a person who answers the phone.",
        ]],
        ["p", "The site still needs clear product pages, photos you own, and one action. POWER SHIFT has shipped this shape as a corporate catalogue, for example on <a href=\"/work/lodiamo.html\">Lodiamo</a>, and as shops when the brand actually sells online — <a href=\"/work/nourvive.html\">Nourvive</a>, <a href=\"/work/corolla.html\">Corolla</a>, <a href=\"/work/uruz.html\">URUZ</a>."],
        ["h2", "You need a shop when"],
        ["ul", [
          "Customers expect to pay without waiting for a message.",
          "You cannot keep stock straight in a notebook.",
          "Retail and wholesale need different paths on the same site.",
        ]],
        ["p", "That is <a href=\"/services#ecommerce\">e-commerce development</a>, not a website with a buy button that emails you. If staff must manage invoices and inventory beyond the storefront, you may be crossing into <a href=\"/blog/website-or-custom-software.html\">operations software</a>."],
        ["h2", "Do not copy a US checkout onto a WhatsApp business"],
        ["p", "If your buyers will not complete a guest checkout, do not pay for one yet. Build the catalogue, measure whether people still insist on chat, then add payment. Cost follows that sequence — <a href=\"/blog/how-much-does-a-website-cost-in-egypt.html\">not a single “shop price”</a>."],
        ["p", "A landing page can sell one drop. A shop is for a catalogue that will still be there next season. <a href=\"/blog/website-vs-landing-page.html\">Do not confuse the two</a>."],
      ],
    },
    ar: {
      title: "هل تحتاج متجرًا إلكترونيًا أم كتالوجًا؟",
      h1: "هل تحتاج متجرًا إلكترونيًا أم كتالوجًا؟",
      seoTitle: "متجر إلكتروني أم كتالوج في مصر؟ | Power Shift",
      seoDescription:
        "الكتالوج يعرض المنتجات. المتجر يأخذ دفعًا أو طلبًا منظمًا. كيف تختار العلامة المصرية قبل أن تدفع ثمن إتمام شراء لن تستخدمه.",
      excerpt: "إذا كان كل طلب ما زال يُؤكد على واتساب، يمكن أن ينتظر إتمام الشراء. إذا احتجت مخزونًا وأسعارًا وسلة تطابق الواقع، فأنت تحتاج متجرًا.",
      ogAlt: "ملاحظة عن المتجر مقابل الكتالوج من Power Shift",
      primaryKeyword: "متجر إلكتروني أم كتالوج",
      secondaryKeywords: ["متجر أونلاين في مصر", "هل أحتاج شوبيفاي", "موقع طلبات جملة"],
      body: [
        ["p", "شركات الجمال والأغذية والتجارة في مصر تطلب «متجرًا» وهي تعني «ضع المنتجات أونلاين». هذان بناءان مختلفان. الدفع والشحن والمخزون الجزء الغالي. كتالوج مع مسار جملة أو واتساب قد يكون النسخة الأولى الصادقة."],
        ["h2", "الكتالوج يكفي عندما"],
        ["ul", [
          "الأسعار تتغير في الشات على أي حال.",
          "تبيع للشركات والخطوة التالية عرض سعر لا بطاقة.",
          "عندك عشرات الأصناف وشخص يرد الهاتف.",
        ]],
        ["p", "الموقع ما زال يحتاج صفحات منتج واضحة وصورًا تملكها وفعلًا واحدًا. POWER SHIFT سلّمت هذا الشكل ككتالوج مؤسسي مثل <a href=\"/work/lodiamo.html\">Lodiamo</a>، وكمتاجر حين تبيع العلامة أونلاين فعلًا — <a href=\"/work/nourvive.html\">Nourvive</a> و<a href=\"/work/corolla.html\">Corolla</a> و<a href=\"/work/uruz.html\">URUZ</a>."],
        ["h2", "تحتاج متجرًا عندما"],
        ["ul", [
          "العميل يتوقع أن يدفع دون انتظار رسالة.",
          "لا تستطيع ضبط المخزون في دفتر.",
          "التجزئة والجملة يحتاجان مسارين على نفس الموقع.",
        ]],
        ["p", "هذا <a href=\"/services#ecommerce\">تطوير تجارة إلكترونية</a>، لا موقعًا عليه زر شراء يرسل إيميلًا. إذا كان الموظفون سيديرون فواتير ومخزونًا أبعد من الواجهة، فقد تعبر إلى <a href=\"/ar/blog/website-or-custom-software.html\">برمجيات التشغيل</a>."],
        ["h2", "لا تنسخ إتمام شراء أمريكيًا على نشاط واتساب"],
        ["p", "إذا كان المشتري لن يُكمل الشراء كضيف، فلا تدفع ثمنه بعد. ابنِ الكتالوج، قِس إن كانوا يصرّون على الشات، ثم أضف الدفع. التكلفة تتبع هذا التسلسل — <a href=\"/ar/blog/how-much-does-a-website-cost-in-egypt.html\">لا «سعر متجر» واحد</a>."],
        ["p", "صفحة هبوط تبيع إصدارًا واحدًا. المتجر لكتالوج سيبقى الموسم القادم. <a href=\"/ar/blog/website-vs-landing-page.html\">لا تخلط بينهما</a>."],
      ],
    },
  },
  {
    id: "bilingual-website-egypt-gcc",
    slug: "bilingual-arabic-english-website-egypt-gcc",
    category: "strategy",
    tone: "paper",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["facebook-or-website", "why-website-not-on-google", "what-business-website-needs"],
    en: {
      title: "Bilingual Arabic and English websites for Egypt and the GCC",
      h1: "Bilingual Arabic and English websites for Egypt and the GCC",
      seoTitle: "Bilingual Arabic-English Websites for Egypt & GCC | Power Shift",
      seoDescription:
        "A translate button is not a bilingual site. How Arabic RTL and English should be structured so both languages can be found and trusted.",
      excerpt: "If you sell in Cairo and quote in the Gulf, you need two real language versions — not English copy pasted into a plugin.",
      ogAlt: "Note on bilingual websites from Power Shift",
      primaryKeyword: "bilingual website Arabic English",
      secondaryKeywords: ["Arabic English website Egypt", "RTL website GCC", "bilingual company website"],
      body: [
        ["p", "Companies that work Egypt-to-GCC often ship an English site and promise Arabic later. Later rarely comes. Or they bolt on a widget that breaks layout and produces machine Arabic a buyer will not trust."],
        ["h2", "Two audiences, two pages"],
        ["p", "Arabic and English are not a coat of paint. RTL changes navigation, numbers, and forms. The Arabic should be written, not reverse-translated from marketing English. The English should sound like a person who sells the work, not a subtitle file."],
        ["p", "For search, each language needs its own URL. A JS toggle that never changes the address teaches Google there is only one page. That is a common reason <a href=\"/blog/why-isnt-my-website-showing-on-google.html\">the Arabic version never ranks</a>."],
        ["h2", "What we actually ship"],
        ["p", "POWER SHIFT builds bilingual products as a default for this studio — sites such as <a href=\"/work/via-holidays.html\">VIA Holidays</a> and <a href=\"/work/lodiamo.html\">Lodiamo</a>, and storefronts that switch language for shoppers. We do not claim offices in every GCC capital. We do build for teams who sell there."],
        ["h2", "When one language is enough"],
        ["p", "A purely local trade that never quotes abroad can stay in Arabic. A Czech or English-only audience does not need Arabic for politeness. Adding a language you will not maintain is how both versions rot."],
        ["h2", "Brief it as structure, not as a feature"],
        ["p", "Say which language is default, who writes each, and whether hreflang should pair the URLs. That belongs in the same conversation as <a href=\"/blog/what-a-business-website-needs.html\">what the site needs</a> and <a href=\"/blog/how-much-does-a-website-cost-in-egypt.html\">what changes cost</a>. The service is <a href=\"/services#website\">custom websites</a> — with RTL treated as part of the build, not an extra sticker."],
      ],
    },
    ar: {
      title: "مواقع عربي وإنجليزي لمصر والخليج",
      h1: "مواقع عربي وإنجليزي لمصر والخليج",
      seoTitle: "موقع عربي وإنجليزي لمصر والخليج | Power Shift",
      seoDescription:
        "زر الترجمة ليس موقعًا بلغتين. كيف يُبنى العربي RTL والإنجليزي كي يُوجد الاثنان ويُوثق بهما.",
      excerpt: "إذا كنت تبيع في القاهرة وتسعّر في الخليج، تحتاج نسختين لغويتين حقيقيتين — لا نصًا إنجليزيًا في إضافة.",
      ogAlt: "ملاحظة عن المواقع ثنائية اللغة من Power Shift",
      primaryKeyword: "موقع عربي وإنجليزي",
      secondaryKeywords: ["موقع ثنائي اللغة مصر", "موقع RTL للخليج", "موقع شركة بالعربي والإنجليزي"],
      body: [
        ["p", "شركات تعمل من مصر إلى الخليج تطلق موقعًا إنجليزيًا وتعد بالعربي لاحقًا. اللاحق نادرًا ما يأتي. أو تلصق أداة تكسر التخطيط وتُخرج عربيًا آليًا لا يثق به المشتري."],
        ["h2", "جمهوران، صفحتان"],
        ["p", "العربي والإنجليزي ليسا طبقة طلاء. RTL يغيّر التنقل والأرقام والنماذج. العربي يُكتب، لا يُعكس من إنجليزي تسويقي. والإنجليزي يبدو كمن يبيع العمل، لا كملف ترجمة."],
        ["p", "في البحث، كل لغة تحتاج رابطها. تبديل بجافاسكربت لا يغيّر العنوان يعلّم جوجل أن هناك صفحة واحدة. هذا سبب شائع لـ<a href=\"/ar/blog/why-isnt-my-website-showing-on-google.html\">ألا تُرتَّب النسخة العربية أبدًا</a>."],
        ["h2", "ما نُسلّمه فعلًا"],
        ["p", "POWER SHIFT تبني منتجات بلغتين كإعداد افتراضي لهذا الاستوديو — مواقع مثل <a href=\"/work/via-holidays.html\">VIA Holidays</a> و<a href=\"/work/lodiamo.html\">Lodiamo</a>، وواجهات متاجر تبدّل اللغة للمتسوق. لا ندّعي مكاتب في كل عاصمة خليجية. نبني لفرق تبيع هناك."],
        ["h2", "متى تكفي لغة واحدة"],
        ["p", "تجارة محلية لا تسعّر للخارج يمكن أن تبقى بالعربي. جمهور إنجليزي أو تشيكي فقط لا يحتاج عربيًا للمجاملة. إضافة لغة لن تصونها هي طريق لفساد النسختين."],
        ["h2", "وجّزه كهيكل لا كخاصية"],
        ["p", "قل أي لغة هي الافتراضية، ومن يكتب كل نسخة، وهل يجب أن يربط hreflang العناوين. هذا في نفس حديث <a href=\"/ar/blog/what-a-business-website-needs.html\">ماذا يحتاج الموقع</a> و<a href=\"/ar/blog/how-much-does-a-website-cost-in-egypt.html\">ما الذي يغيّر التكلفة</a>. الخدمة <a href=\"/services#website\">مواقع مخصصة</a> — وRTL جزء من البناء لا ملصقًا إضافيًا."],
      ],
    },
  },
  {
    id: "website-or-custom-software",
    slug: "website-or-custom-software",
    category: "strategy",
    tone: "navy",
    wizard: "bms",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["ecommerce-or-catalogue", "choose-web-company-egypt", "what-business-website-needs"],
    en: {
      title: "Website or custom software: which does your company need?",
      h1: "Website or custom software: which does your company need?",
      seoTitle: "Website vs Custom Software for Your Business | Power Shift",
      seoDescription:
        "A website is the public face. Software is what staff use every day. How to tell them apart before you pay for the wrong one.",
      excerpt: "If strangers must understand you, you need a site. If the team is drowning in Excel and chat, you need a system. Many companies need a sequence, not both on day one.",
      ogAlt: "Note on websites versus custom software from Power Shift",
      primaryKeyword: "website vs custom software",
      secondaryKeywords: ["business needs software or website", "custom operations system", "SaaS vs website"],
      body: [
        ["p", "Studios get asked for “an app” when the company has no URL, and for “a website” when the real pain is overlapping bookings. Naming the job wrongly is the most expensive part of the brief."],
        ["h2", "A website is the public face"],
        ["p", "It explains, proves, and takes an enquiry. Staff do not live in it. If that face does not exist, start there — <a href=\"/blog/what-a-business-website-needs.html\">the pages that have to be true</a>, then <a href=\"/services#website\">the website service</a>."],
        ["h2", "Software is the operating layer"],
        ["p", "Logins, roles, invoices, inventory, occupancy. POWER SHIFT’s examples are <a href=\"/work/availio.html\">Availio</a> for property operations and <a href=\"/work/haseb.html\">7aseb</a> for invoicing and stock. That is <a href=\"/services#saas\">SaaS</a> or <a href=\"/services#bms\">operations systems</a>, not a prettier homepage."],
        ["h2", "A shop sits in between"],
        ["p", "Customers complete an order; staff still need a back office. Decide <a href=\"/blog/ecommerce-website-or-catalogue-egypt.html\">catalogue versus checkout</a> before you specify software. Do not build a custom ERP to sell twenty products."],
        ["h2", "A simple test"],
        ["ul", [
          "If the next user is a stranger on a phone: website.",
          "If the next user is an employee every morning: software.",
          "If both: public site first unless operations are already breaking deals.",
        ]],
        ["p", "We will say when a system should wait. A 20-minute call is for that sequencing, not for pretending every brief is a mobile app. <a href=\"/blog/how-to-choose-a-website-company-in-egypt.html\">Pick a company that can tell the difference</a>."],
      ],
    },
    ar: {
      title: "موقع أم برنامج مخصص: ماذا تحتاج الشركة؟",
      h1: "موقع أم برنامج مخصص: ماذا تحتاج الشركة؟",
      seoTitle: "موقع أم برنامج مخصص لشركتك؟ | Power Shift",
      seoDescription:
        "الموقع هو الوجه العام. البرنامج ما يستخدمه الموظفون كل يوم. كيف تفرّق بينهما قبل أن تدفع ثمن الشيء الخطأ.",
      excerpt: "إذا كان على الغرباء أن يفهموك، فأنت تحتاج موقعًا. إذا كان الفريق يغرق في Excel والشات، فأنت تحتاج نظامًا. كثير من الشركات تحتاج تسلسلًا لا الاثنين في اليوم الأول.",
      ogAlt: "ملاحظة عن الموقع مقابل البرنامج من Power Shift",
      primaryKeyword: "موقع أم برنامج مخصص",
      secondaryKeywords: ["الشركة تحتاج موقع أم سوفتوير", "نظام تشغيل مخصص", "SaaS أم موقع"],
      body: [
        ["p", "الاستوديوهات تُطلب منها «تطبيق» والشركة بلا رابط، و«موقع» والألم الحقيقي تداخل الحجوزات. تسمية العمل خطأ هي أغلى جزء في الموجز."],
        ["h2", "الموقع هو الوجه العام"],
        ["p", "يشرح ويثبت ويستقبل الاستفسار. الموظفون لا يعيشون فيه. إذا لم يكن هذا الوجه موجودًا، ابدأ منه — <a href=\"/ar/blog/what-a-business-website-needs.html\">الصفحات التي يجب أن تصدق</a> ثم <a href=\"/services#website\">خدمة المواقع</a>."],
        ["h2", "البرنامج طبقة التشغيل"],
        ["p", "دخول وصلاحيات وفواتير ومخزون وإشغال. أمثلة POWER SHIFT: <a href=\"/work/availio.html\">Availio</a> لتشغيل العقارات و<a href=\"/work/haseb.html\">7aseb</a> للفواتير والمخزون. هذا <a href=\"/services#saas\">SaaS</a> أو <a href=\"/services#bms\">أنظمة تشغيل</a>، لا صفحة رئيسية أجمل."],
        ["h2", "المتجر في المنتصف"],
        ["p", "العميل يُكمل طلبًا؛ والموظف ما زال يحتاج مكتبًا خلفيًا. قرر <a href=\"/ar/blog/ecommerce-website-or-catalogue-egypt.html\">الكتالوج مقابل إتمام الشراء</a> قبل أن توصّف البرنامج. لا تبنِ ERP مخصصًا لبيع عشرين منتجًا."],
        ["h2", "اختبار بسيط"],
        ["ul", [
          "إذا كان المستخدم التالي غريبًا على موبايل: موقع.",
          "إذا كان المستخدم التالي موظفًا كل صباح: برنامج.",
          "إذا كان الاثنان: الموقع العام أولًا إلا إذا كان التشغيل يُفسد الصفقات أصلًا.",
        ]],
        ["p", "نقول متى يجب أن ينتظر النظام. استشارة عشرين دقيقة لهذا الترتيب، لا للادعاء أن كل موجز تطبيق جوال. <a href=\"/ar/blog/how-to-choose-a-website-company-in-egypt.html\">اختر شركة تفرّق بينهما</a>."],
      ],
    },
  },
  {
    id: "choose-web-company-egypt",
    slug: "how-to-choose-a-website-company-in-egypt",
    popular: true,
    category: "strategy",
    tone: "paper",
    wizard: "website",
    publishedAt: "2026-08-31",
    updatedAt: "2026-08-31",
    related: ["website-cost-egypt", "what-business-website-needs", "website-or-custom-software"],
    en: {
      title: "How to choose a website company in Egypt",
      h1: "How to choose a website company in Egypt",
      seoTitle: "How to Choose a Website Company in Egypt | Power Shift",
      seoDescription:
        "Judge an Egyptian web studio by live work, a written scope, and who maintains the site — not by a cheap package or a mockup alone.",
      excerpt: "The useful filter is not the lowest quote. It is whether they can describe your job, show something live, and say who fixes it after launch.",
      ogAlt: "Note on choosing a web company in Egypt from Power Shift",
      primaryKeyword: "choose website company Egypt",
      secondaryKeywords: ["best website company Cairo", "how to choose web developer Egypt", "website agency Egypt"],
      body: [
        ["p", "Egypt has cheap packages, freelance groups, and studios that only make mockups. The way to choose is boring: live URLs, a written scope, and a named person after launch. POWER SHIFT is one studio in Cairo. This is the checklist we would want if we were buying, not a claim that we are the only option."],
        ["h2", "Ask to open the work"],
        ["p", "Screenshots are easy. Click the link. If the portfolio is all foreign templates with no relation to the case study, keep walking. Our own work is listed on <a href=\"/work\">the work page</a> so you can judge the same way."],
        ["h2", "Make them write the job"],
        ["p", "Pages, languages, what happens after click, who edits later. If they quote before that, they are selling a package. Read <a href=\"/blog/how-much-does-a-website-cost-in-egypt.html\">what actually changes cost</a> so you can hear when two quotes are not comparable. If you are not sure you need a site versus software, start with <a href=\"/blog/website-or-custom-software.html\">that split</a>."],
        ["h2", "Arabic is not a checkbox"],
        ["p", "Ask who writes Arabic and whether RTL is in the build. A plugin is not a bilingual site — <a href=\"/blog/bilingual-arabic-english-website-egypt-gcc.html\">structure and URLs matter</a>."],
        ["h2", "Maintenance is part of the product"],
        ["p", "Who changes a price in month four? If the answer is “you will need us for every comma,” price that in. If the answer is “you cannot,” do not launch."],
        ["h2", "Ignore theatre"],
        ["p", "Guaranteed first-page rankings, fake reviews, and 48-hour full e-commerce are theatre. Search takes time even when the site is indexable — <a href=\"/blog/why-isnt-my-website-showing-on-google.html\">indexing is the first bar</a>."],
        ["p", "When you have a brief, <a href=\"/contact\">book a scope call</a>. We will tell you if the fit is a <a href=\"/services#website\">website</a>, a <a href=\"/services#ecommerce\">shop</a>, or a system — including when you should not hire us."],
      ],
    },
    ar: {
      title: "كيف تختار شركة تصميم مواقع في مصر",
      h1: "كيف تختار شركة تصميم مواقع في مصر",
      seoTitle: "كيف تختار شركة مواقع في مصر | Power Shift",
      seoDescription:
        "احكم على استوديو مصري من عمل حي ونطاق مكتوب ومن يصون الموقع بعد الإطلاق — لا من باقة رخيصة أو مجسّم وحده.",
      excerpt: "المرشّح المفيد ليس أرخص عرض. هو: هل يصفون عملك، ويعرضون شيئًا حيًا، ويقولون من يصلحه بعد الإطلاق.",
      ogAlt: "ملاحظة عن اختيار شركة مواقع في مصر من Power Shift",
      primaryKeyword: "اختيار شركة تصميم مواقع في مصر",
      secondaryKeywords: ["أفضل شركة مواقع القاهرة", "كيف أختار مطور مواقع", "شركة تصميم مواقع مصر"],
      body: [
        ["p", "في مصر باقات رخيصة وجروبات مستقلين واستوديوهات تصنع مجسّمات فقط. طريقة الاختيار مملة: روابط حية، نطاق مكتوب، وشخص مسمّى بعد الإطلاق. POWER SHIFT استوديو واحد في القاهرة. هذه قائمة كنا نريدها لو كنا نشتري، لا ادّعاء أننا الخيار الوحيد."],
        ["h2", "اطلب فتح العمل"],
        ["p", "لقطات الشاشة سهلة. اضغط الرابط. إذا كان المعرض قوالب أجنبية لا علاقة لها بدراسة الحالة، أكمل طريقك. أعمالنا معروضة في <a href=\"/work\">صفحة الأعمال</a> لتحكم بالطريقة نفسها."],
        ["h2", "اجعلهم يكتبون العمل"],
        ["p", "الصفحات، اللغات، ماذا بعد الضغط، من يعدّل لاحقًا. إذا سعّروا قبل ذلك فهم يبيعون باقة. اقرأ <a href=\"/ar/blog/how-much-does-a-website-cost-in-egypt.html\">ما الذي يغيّر التكلفة فعلًا</a> كي تسمع متى لا يُقارن عرضان. إذا لم تكن واثقًا أنك تحتاج موقعًا مقابل برنامج، ابدأ من <a href=\"/ar/blog/website-or-custom-software.html\">هذا الفصل</a>."],
        ["h2", "العربي ليس خانة"],
        ["p", "اسأل من يكتب العربي وهل RTL داخل البناء. الإضافة ليست موقعًا بلغتين — <a href=\"/ar/blog/bilingual-arabic-english-website-egypt-gcc.html\">الهيكل والروابط مهمان</a>."],
        ["h2", "الصيانة جزء من المنتج"],
        ["p", "من يغيّر سعرًا في الشهر الرابع؟ إذا كان الجواب «ستحتاجنا لكل فاصلة»، احسب ذلك في السعر. إذا كان «لا تستطيع»، لا تُطلق."],
        ["h2", "تجاهل المسرح"],
        ["p", "ضمان الصفحة الأولى، ومراجعات مختلقة، ومتجر كامل في 48 ساعة مسرح. البحث يأخذ وقتًا حتى عندما يكون الموقع قابلاً للفهرسة — <a href=\"/ar/blog/why-isnt-my-website-showing-on-google.html\">الفهرسة هي العتبة الأولى</a>."],
        ["p", "عندما يكون لديك موجز، <a href=\"/contact\">احجز استشارة نطاق</a>. نقول إن كان الأنسب <a href=\"/services#website\">موقعًا</a> أو <a href=\"/services#ecommerce\">متجرًا</a> أو نظامًا — بما في ذلك متى لا يجب أن توظّفنا."],
      ],
    },
  },
];
